### ISSUE TITLE
Failing tableselection tests

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#1944]
## Are you reporting a feature request or a bug?

Failing tests

## Provide detailed reproduction steps (if any)

1. Run unit tests:
```
http://10.0.2.2:1030/tests/plugins/tableselection/integrations/core/selection
http://10.0.2.2:1030/tests/plugins/tableselection/integrations/tabletools/tabletools
http://10.0.2.2:1030/tests/plugins/tableselection/tableselection
```

### Expected result

Whole test cases passes.

### Actual result

Some of the tests fails:

![2018-05-03_14 46 55](https://user-images.githubusercontent.com/10279586/39577465-b2719180-4ee1-11e8-85f8-e643d266c6a3.png)
![2018-05-03_14 47 25](https://user-images.githubusercontent.com/10279586/39577466-b2b49520-4ee1-11e8-9f86-46d959ed7dde.png)
![2018-05-03_14 48 22](https://user-images.githubusercontent.com/10279586/39577467-b2ee071a-4ee1-11e8-8a04-341f1fa70e14.png)
![2018-05-03_14 48 48](https://user-images.githubusercontent.com/10279586/39577468-b3167754-4ee1-11e8-9bbd-a43b90768b32.png)

## Other details

* Browser: Edge 42.17134.1.0/17.17134
* OS: Windows 10
* CKEditor version: 4.9.2/4.10.0
* Installed plugins: tableselection

**Comment by Comandeer** [comment]
Could you provide more info about Edge version? I can't reproduce it on 41.16299.371.0/16.16299.

**Comment by jacekbogdanski** [comment]
Sure, it's 42.17134.1.0/17.17134. It's the latest MSEdge VM from Microsoft.

**Comment by mlewand** [comment]
In 4.10.0 we ignored these tests, but we need to review what happened in edge that the tests started to fail.

**Comment by Comandeer** [comment]
Seems like at least part of tests (ones in `tests/plugins/tableselection/integrations/core/selection`) fails due to the change in the way, how Edge is selecting table cells.

All other browsers, except Safari and IE8, hook selection into the row element, selecting the whole cell. In case of Edge, it seems like only text node inside cell is selected (the start and end container of the selection is the cell itself and offsets indicate that one node – the text one – is selected).

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
