### ISSUE TITLE
[Edge] Error thrown when dropping at the end of editor

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#2842]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open test tests/plugins/clipboard/manual/droponmargin on build version.
1. Open browsers console.
1. Select all.
1. Drag and drop in the editor right above elementspath.

### Expected result

No errors thrown.

### Actual result

Error thrown:
`SCRIPT5007: Unable to get property 'type' of undefined or null reference`
![feb-21-2019 10-57-51](https://user-images.githubusercontent.com/23366849/53163936-76413c80-35cf-11e9-86d3-d58b81187d3b.gif)

## Other details

* Browser: Microsoft Edge 42.17134.1.0
* OS: Windows
* CKEditor version: 4.11.3
* Installed CKEditor plugins: full-all

**Comment by jacekbogdanski** [comment]
I can reproduce the issue on IE10. Although, the error is a bit different:
![image](https://user-images.githubusercontent.com/10279586/53194727-6bf56180-3614-11e9-87a3-b518aed4eca3.png)

**Comment by msamsel** [comment]
From analysis which was made during testing phase:
issue is caused because there is missing selection in editor. This situation throws error, because editor cannot create bookmark during saving snaphoshot.
https://github.com/ckeditor/ckeditor-dev/blob/dba5aab2e0871ef4e234b76dab72da82d9f40b55/plugins/clipboard/plugin.js#L1925

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
