### ISSUE TITLE
Not able to find Plugin.js for bbcode on the cdn

### ISSUE THREAD

**Issue by DevyaniSethi** [ckeditor/ckeditor4#3414]
## Type of report

Task

Resource not found error for bbcode plugin when i am using thr ckeditor cdn 

https://cdn.ckeditor.com/4.12.1/full/plugins/bbcode/plugin.js?t=J5S8 => give 404 not found

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Plugins that are not automatically enabled in presets are in `-all` packages, so instead of `full` you have to use `full-all` → https://cdn.ckeditor.com/4.12.1/full-all/plugins/bbcode/plugin.js

Additionally please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
