### ISSUE TITLE
Paste from google docs results in different content

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3435]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open `/tests/plugins/pastefromgdocs/manual/pastefromgdocs`
2. Proceed with test steps.

### Expected result

The test should succeed where the pasted content style is the same as a Google docs document.

### Actual result

Test fails.

![pfg](https://user-images.githubusercontent.com/10279586/65150040-8fa24e00-da23-11e9-945e-dfc3b3698189.gif)

## Other details

* Browser: IE11
* CKEditor version: 4.13.0

Not sure if it's just failing test or partial IE11 support, cc @Comandeer

**Comment by Dumluregn** [comment]
In FF there is an issue with subscript and superscript.

Expected:
![Screenshot 2019-09-18 at 16 14 22](https://user-images.githubusercontent.com/10883184/65156730-e150d580-da2f-11e9-887b-9f2c110c2423.png)

Actual:
![Screenshot 2019-09-18 at 16 14 10](https://user-images.githubusercontent.com/10883184/65156751-e7df4d00-da2f-11e9-99f3-36cf4fb21722.png)

**Comment by Comandeer** [comment]
1. Issue with non-centered image is unfixable, as GDocs just strips off info about centering.
2. Subscript and supscript is apparently switched off in filter: https://github.com/ckeditor/ckeditor4/blob/c48f3ba4a409f43fbc2e50fbc9937d59831d6f7f/plugins/pastefromgdocs/filter/default.js#L57 Subscript and supscript are supported in GDocs via `vertical-align` style, which we skip in CKE4. Probably some additional filter for it should be applied, as most of the time value of this style is totally useless to us.

**Comment by Comandeer** [comment]
There is also issue with pasting tables: https://docs.google.com/document/d/1a9YzJidjxRPrxY9BL4ZReNFkPAgd_ItnZoFxcjSiJ4U/edit

<img width="883" alt="Content pasted from GDocs: table is floating on left instead of being block element" src="https://user-images.githubusercontent.com/1078728/65251715-1fb1c780-daf8-11e9-83ae-24b708403db2.png">

Content copied from GDocs contains table surrounded by `div[align=left]`, which is converted to `div[style="float: left"]` on our side.

**Comment by Comandeer** [comment]
I've extracted IE11 issue with background color in heading to separate issue, #3464.
