### ISSUE TITLE
Lock Ratio Checkbox Does Not Save State

### ISSUE THREAD

**Issue by rkarina94** [ckeditor/ckeditor4#3447]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Add an image.
2. Right click on the image and open up properties.
3. Untick Lock Ratio and save.
4. Re-open properties.

### Expected result

Our clients are expecting the Lock Ratio checkbox to be unticked, i.e. Previous state is saved.

### Actual result

Lock Ratio checkbox is still ticked.

![LockRatioIssue](https://user-images.githubusercontent.com/28332589/65216821-8386c100-daf5-11e9-9520-f8360441c8a8.PNG)

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.11.4
* Installed CKEditor plugins: {
		'a11yhelp' : 1,
		'autolink' : 1,
		'backgrounds' : 1,
		'base64image' : 1,
		'basicstyles' : 1,
		'bgimage' : 1,
		'blockquote' : 1,
		'chart' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'contextmenu' : 1,
		'docprops' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'image' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imagerotate' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'lineheight' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'maxheight' : 1,
		'pagebreak' : 1,
		'panelbutton' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'print' : 1,
		'quicktable' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'scayt' : 1,
		'showblocks' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'textsignature' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'zoom' : 1
	}

**Comment by Dumluregn** [comment]
Hello!
I see you are using [`Base64 Image`](https://ckeditor.com/cke4/addon/base64image) plugin,  which as you can check it is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
