### ISSUE TITLE
CKEditor not working in MS EDGE

### ISSUE THREAD

**Issue by mathan05** [ckeditor/ckeditor4#3479]
## Type of report

We have integrate the CKEditor in our project. The Entire toolbar is not give any actions, we can't do anything in CKEditor tool in MS EDGE.  All contents are placed in iframe in CKEDitor, but it is not working in MS Edge. We verfiied the sample html in Edge, it was working fine. What needs to be added to work in MS Edge

## Provide detailed reproduction steps (if any)

1. Open CKEditor in MS EDGE, Which is integrated in our project.
2. It is not working.

### Expected result

CKEditor needs to working good in MS EDGE as expected

### Actual result

CKEditor not working in MS EDGE

## Other details

* Browser: MS EDGE
* OS: Windows 10
* CKEditor version: 4.11.4

**Comment by jacekbogdanski** [comment]
CKEditor4 is thoroughly tested with MS Edge and other [supported browsers](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html). I believe that the issue is on your configuration side and I strongly encourage to read our [Quick start guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html) for information on how to correctly configure editor.

If you, despite correct configuration still have an issue with CKEditor4, please open a new ticket with information which could help us to reproduce the issue, like browser version, code sample (you could use http://codepen.io or similar online editor for that), reproduction steps etc.
