### ISSUE TITLE
pastefromword plugin options negatively impact pastefromgdocs

### ISSUE THREAD

**Issue by JamoCA** [ckeditor/ckeditor4#3502]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Enable both pastefromword & pastefromgdocs plugins.
2. Set "pasteFromWordRemoveFontStyles" and/or "pasteFromWordCleanupFile" to true.
3. Paste content from Word & GoogleDocs.

### Expected result

Word & Google Docs content w/styles retained; the ability for both plugins to be enabled with their own configuration options without impacting each other

*What is the expected result of the above steps?*

Pasted Word content is acceptablely styled.  Google Docs content retains style.

### Actual result

Word content retains styles, but Google Docs is pasted as plain text (when "pasteFromWordRemoveFontStyles" is enabled.)

*What is the actual result of the above steps?*

Unstyled Google Docs content.

## Other details

* Browser: Chrome 77.0.3865.90
* OS: Windows 10
* CKEditor version: 4.13
* Installed CKEditor plugins: pastefromword,pastefromgdocs,pastetools

**Comment by wwalc** [comment]
@JamoCA https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFromWordCleanupFile cannot be set to `true`, it should contain a path to the file that provides the Microsoft Word cleanup function for pasting operations.

**Comment by Comandeer** [comment]
As @wwalc already mentioned, `pasteFromWordCleanupFile` cannot be set to `true`. However I've also checked if loading custom Paste from Word filter changes the behaviour of the new Paste from Google Docs plugin and I wasn't able to reproduce it.

As for the other option, `pasteFromWordRemoveFontStyles`, it was replaced by the newer [`pasteTools_removeFontStyles` option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteTools_removeFontStyles) and it applies to both Paste from Word and Paste from Google Docs plugins. When designing the new feature, we assumed that if someone want to strip font styles from one source, they probably want to strip it from all sources. Additionally please note that both these options are deprecated (with `pasteFromWordRemoveFontStyles` being deprecated since version 4.6.0) and it's recommended to use [Advanced Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) instead to remove font styles. Therefore, as the much better alternative exists and it allows user to create separate handling of font styles for Word and Google Docs, we won't be altering the behaviour of this option.

**Comment by JamoCA** [comment]
Thanks for the quick responses.

I think we made the mistake of using `true` when the pastefromword plugin was first released.

I read that `CKEDITOR.config.pasteFromWordRemoveFontStyles` was to be deprecated soon, but the plugin page didn't mention a Word-specific replacement or indicate that future usage could be problematic.

"Advanced Content Filters" sounds like it will accomplish what we want to do.  Clearing Word fonts is often more critical because the fonts used aren't univeral, replacements didn't look right and code seemed invalid.

**Example**

    <span style="font-family:&quot;Century Gothic&quot;,sans-serif">EDUCATION</span>

Is there an documentation (or a demo) with separate unqiue rules for both Word & Google Docs?

**Comment by Comandeer** [comment]
> Is there an documentation (or a demo) with separate unqiue rules for both Word & Google Docs?

Unfortunately no, I created appropriate issue for that, #3511.
