### ISSUE TITLE
hi I have a question about uploading images.

### ISSUE THREAD

**Issue by s2s22** [ckeditor/ckeditor4#3513]
## Type of report

Task

## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser:  chrome
* OS:window10
* CKEditor version: 4.12.1
* Installed CKEditor plugins:font family

hi~
Even if you don't save images separately to a database, you can see the images if you check what you've written.
But it is not visible when it is operated in another place.
Then, I wonder if I need to use the database or if I can see it when I distribute the website that I created.
thank you

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
