### ISSUE TITLE
Firefox with divarea plugin : duplicate toolbars, instances and copy/paste

### ISSUE THREAD

**Issue by hunteer** [ckeditor/ckeditor4#3519]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

This bug happens with Symfony 3.4 using Ckeditor bundle with divarea plugin on a Firefox Quantum 60.9.0esr (no bug on others navigators and  no bug without divarea plugin).

The problem is that when we copy/paste something on firefox, the content pasted is duplicated, and firefox also add a duplicate toolbar on each editors. So I checked the DOM and I realized that Firefox load ckeditor.js multiple times, and creates sort of duplicate toolbars which appears when you click on the text field.

To compare, these are screens of the DOM of one specific page  : 

- On chrome (normal)

![chrome](https://user-images.githubusercontent.com/12373326/65885172-72ae3900-e39a-11e9-89e2-4a84b0a6fce0.png)

- And then on firefox

![firefox](https://user-images.githubusercontent.com/12373326/65885119-57432e00-e39a-11e9-89a3-970441b11cd4.png)

So you can see that firefox creates what I think are duplicate ckeditor instances. Which leads to a duplicate toolbar when you click on each editors, and so duplicate pasted contents. You can see the duplicate toolbar on this picture : 

![duplicate toolbars](https://user-images.githubusercontent.com/12373326/65885509-1992d500-e39b-11e9-9bb5-3d2a049a92c1.png)

I really don't understand why this only happens with Firefox, this is so weird, do you have any idea to fix this ?

## Other details

* Browser:  Firefox Quantum 60.9.0esr 
* OS: Linux
* CKEditor version: Ckeditor Symfony Bundle (v4.12.1)
* Installed CKEditor plugins: divarea, language

**Comment by hunteer** [comment]
Precision : if I click source button then reclick on it, problems disappear on current editor (no duplicate toolbars and copy/paste...), maybe it can help

**Comment by jacekbogdanski** [comment]
If I understand correctly, you are using 3rd party integration with Symfony (probably this one https://github.com/FriendsOfSymfony/FOSCKEditorBundle)?

If so, the software you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the code author who should be able to review the problem and suggest a solution.

If, however, after contacting the code maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by svem1** [comment]
This bug happens and on clear js, for example on site https://mygoal.one

**Comment by f1ames** [comment]
@svem1 is any CKEditor instance present on the page you linked so we can check the issue there too? I don't see it there anywhere 🤔
