### ISSUE TITLE
key event doesn't catch Enter, NumpadEnter, Backspace and Del keys if one or more table cells are selected

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#3541]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://jsfiddle.net/kndyxaLh/1/
2. Select one or more table cells
3. Press Enter, NumpadEnter, Backspace or Delete key

### Expected result

An alert is displayed with message 'key pressed'

### Actual result

No message is displayed

## Other details

* Browser: Firefox 69 x64, Chrome 77 x32
* OS: Windows 7 SP1 x64
* CKEditor version: 4.13.0
* Installed CKEditor plugins: full

**Comment by jacekbogdanski** [comment]
Table Selection plugin needs to cancel these events, so the rest of the CKEditor logic doesn't execute as it would change expected behavior (see https://github.com/ckeditor/ckeditor-dev/blob/5fa2a5b5f5b06d139ecaf8d47f5444734244e5b9/plugins/tableselection/plugin.js#L1147-L1151). It's not the best way to handle this issue, but for this moment it's the simplest one requiring no additional refactor between plugins.

If you really need to execute some logic for the listed keystrokes, you can do it before Table Selection plugin steal `keydown` event: https://codepen.io/jacekbogdanski/pen/GRRgKaq
