### ISSUE TITLE
how can I set the background-image of an Element(not the editor itself)?

### ISSUE THREAD

**Issue by followfire** [ckeditor/ckeditor4#3564]
I've tried "CKEDITOR.dom.setStyle('background-image','url(someUrl)');" in the beginning, but when I use CKEDITOR.instance.getData(),the quote in the url was excaped to "\&quote\;"

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
