### ISSUE TITLE
How to disable/enable iframely embed for some pages

### ISSUE THREAD

**Issue by bobc82** [ckeditor/ckeditor4#3574]
Hi, I'm using CKEditor version 4.7.

In the config.js file i integrated some plugins for auto embed link on external sites (es. youtube, twitter, facebook, etc.).

```
CKEDITOR.editorConfig = function( config ) {
	config.extra_plugins = 'widgetselection,notificationaggregator,notification,clipboard,lineutils,widget,dialogui,dialog,embedbase,embed';
};
```

However, for some pages, i saw there is an auto-embed behavior when i copy an url on the text section on ckeditor. and i need to disable it, it would be better if it would be to have this behavior only when I click on the specific icon on the tab. There is a way to appear the iframely embedded only when i click that icon and not when i simply paste the link url on CKEditor?

**Comment by Dumluregn** [comment]
Hello!

1. Auto-embed behaviour you described is provided by [`Auto Embed plugin`](https://ckeditor.com/cke4/addon/autoembed), so make sure it is not loaded somewhere else.

2. Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
