### ISSUE TITLE
Firefox: Cannot minimize, toolbar is missing after maximize button

### ISSUE THREAD

**Issue by rixs** [ckeditor/ckeditor4#3584]
When the editor contains a long text (eg. more than as many lines as your screen can display) and the cursor position is at the beginning of the text - one can maximize the the content but the toolbar disappears.

Workaround: we need to type ctrl+"-" several times until the toolbar shows up. Then hit ctrl+"+" as many times as needed to get to the original size.

The problem remains also in the version 4.13.0
I use a customized build and attached the build-config.js (as text file).
[build-config.txt](https://github.com/ckeditor/ckeditor4/files/3737995/build-config.txt)

I use FF 69.0.3 (64bit)
In IE looks good.

**Comment by laumed** [comment]
Start Firefox in Safe Mode {web link} by holding down the
<Shift> (Mac=Options) key, and then starting [Firefox](https://www.laumed.org/blog-details.php?MD-or-MBBS-in-America-&-USA:-Advantages-&-Disadvantages&Gid=43).

A small dialog should appear. Click
Start In [Safe Mode](https://www.laumed.org) (not Refresh).
Is the problem still there?

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by Lorantus** [comment]
Hello.
The bug is "closed" but I am facing the same bug with FF (83.0 64bit on Linux 5.4.0-54-generic/Ubuntu 20.04).
It appear when the preloaded text is longer (more lines) that the input area.
The toolbar is visible when I use the devtool to change the CSS of the element with .cke_maximized rule to "uncheck top: 0px;".
Note : the toolbar is visible and working well in fullscreen if I click anywhere in the input area.
Any idea ?
Thanks for consideration.
