### ISSUE TITLE
Q: Is there a way to re-configure an editor that had been attached inline?

### ISSUE THREAD

**Issue by CarstenLeue** [ckeditor/ckeditor4#3592]
## Type of report

Question

## Provide description of the task

We register the CK editor using the `inline` method. How can we change the config of a particular editor instance without destroying and re-constructing it? Using `replace` does not work.

## Other details

* CKEditor version: 4

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
