### ISSUE TITLE
No access to CKEditor ("This site can't be reached")

### ISSUE THREAD

**Issue by keenminded** [ckeditor/ckeditor4#3596]
## Type of report

Task

## Provide detailed reproduction steps (if any)

The code I am working with uses https://cdn.ckeditor.com.
I try to access https://ckeditor.com or https://cdn.ckeditor.com.

### Expected result

See the editor plugin load, or the website displayed.

### Actual result

The editor fails to load. The website does not open and produces browser errors, either the host cannot be reached or the host cannot be resolved.

## Other details

The site is accessible through other IP addresses. The editor plugin loads fine through other IP addresses. This is very similar to #2495, and I left a comment there, however opening a new ticket since that report has been already closed.

Please PM me for our IP address, or flush the server side DNS as described in #2495.

* Browser: Irrelevant
* OS: Irrelevant
* CKEditor version: Irrelevant
* Installed CKEditor plugins: Irrelevant

**Comment by f1ames** [comment]
@vokiel could you take a look on this one?

**Comment by vokiel** [comment]
Our main website is hosted on a different server, with different IP addresses than the CDN (both from different CDN providers). So the IP depends on the zone one is connecting from.

The issue may happen because of different reasons.

Usually, it's the DNS resolver from the ISP. In such case it's easy to fix - just set another one like `1.1.1.1` (CloudFlare), `208.67.222.222` (OpenDNS) or `8.8.8.8` and `8.8.4.4` (Google). Flush the DNS cache and test the address again.

There is a second, most common case - forced DNSSEC on client router/OS. Which unfortunately we can not support now because of one of our CDN providers. If it's the case - then turn off forcing DNSSEC in your network settings and check again.

Third, the most common case is when the firewall detects threads and blocks the user. To verify that we would need your IP addresses list.

**Comment by keenminded** [comment]
Thank you for the prompt response and for pointing me in the right direction. Turned off DNSSEC setting in our router configuration, flushed the DNS cache and everything is accessible now. Maybe this will help someone.

Keep up the great work!
