### ISSUE TITLE
Table cell width size issue

### ISSUE THREAD

**Issue by Vivek2393** [ckeditor/ckeditor4#3614]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a table (3*3) 
2. Right click on any cell, go to Cell Properties.
3. set width to 170px. 
4. Press OK

### Expected result

* When user inserts data into cell without space, data should get wrapped up with cell maximum width 170px, and should not keep on expanding with data.

### Actual result

* When user insert data into cell without space, cell gets expanded more than 170px.

## Other details

* Browser:Chrome
* OS:Windows 10/8
* CKEditor version: 4.11.4
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
This is connected with the way [how `[width]` is interpreted in case of table cells](https://www.w3.org/TR/CSS22/tables.html#width-layout).

The issue can be fixed by [adding additional style to the `table`s in CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss):

```javascript
CKEDITOR.addCss( 'table { table-layout: fixed; }' );
```

Such style should be added before creating any CKEditor 4 instance.
