### ISSUE TITLE
Ckeditor Problem with loop

### ISSUE THREAD

**Issue by XaibiAslam** [ckeditor/ckeditor4#3620]
## Type of report

I just added ckeditor cdn and its working fine. But when i add in foreach code, the 2nd editor is not working, cant type in it. 

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
