### ISSUE TITLE
Smarty syntax in a template

### ISSUE THREAD

**Issue by eddi13** [ckeditor/ckeditor4#3621]
## Type of report

Task

## Provide description of the task
Is there a way to use the '{' and '}' symbols in a template?
I want to have a smarty variable '{$smartyVar}' in output.
```javascript
var template = new CKEDITOR.template('{${varName}}');
window.console.log(template.output({varName: 'smartyVar'}));//->{${varName}}
var template = new CKEDITOR.template('\{${varName}\}');
window.console.log(template.output({varName: 'smartyVar'}));//->{${varName}}
```

## Other details

* Browser: FF 70
* OS: Win
* CKEditor version: 4.13.0
* Installed CKEditor plugins: autocomplete, placeholder

**Comment by Comandeer** [comment]
You can replace the whole expression:

```javascript
var template = new CKEDITOR.template( '{smarty}' );
console.log( template.output( { smarty: '${smartyVar}' } ) );
```

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your subsequent questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
