### ISSUE TITLE
Paste from word not working on Firefox Windows (works on Linux)

### ISSUE THREAD

**Issue by leonardorame** [ckeditor/ckeditor4#3629]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a simple Word or Wordpad document containing text and one image. For example this:

![image](https://user-images.githubusercontent.com/1405017/68207997-fe753f80-ffae-11e9-98ba-f21f02f5652a.png)

2. Select all and copy to clipboard.
3. Open a CKEditor on Firefox Windows, in my case Firefox Quantum 70.0.1 64bit
4. Click on the Paste From Word icon and Ctrl + v to paste. The result doesn't show the image, as you can see:

![image](https://user-images.githubusercontent.com/1405017/68208196-6deb2f00-ffaf-11e9-8869-576b8b5f115a.png)
 
### Expected result

The resulting paste should include the image, as the original document.

### Actual result

As shown in step 4.

## Other details

* Browser: Firefox Quantum 70.0.1
* OS: Windows 7
* CKEditor version: 4.13
* Installed CKEditor plugins: CKEditor Standard Package.

**Comment by jacekbogdanski** [comment]
As far as I know, paste dialog opens only on mobile devices and the only exception is when you are using a touch screen on a laptop. Could you confirm that you are using touch screen to reproduce issue steps?

**Comment by leonardorame** [comment]
Hi Jacek, I confirm I used a PC (Windows and Linux) for this.

Enviado desde Yahoo Mail para Android 
 
  El mié., 6 de nov. de 2019 a la(s) 6:15, Jacek Bogdański<notifications@github.com> escribió:   
As far as I know, paste dialog opens only on mobile devices and the only exception is when you are using a touch screen on a laptop. Could you confirm that you are using touch screen to reproduce issue steps?

**Comment by jacekbogdanski** [comment]
Thanks, but it's more about if you are using **touch** screen to reproduce the issue or do you have a custom configuration that forces clipboard dialog?

**Comment by leonardorame** [comment]
Why do you insist about *touch*?, I'm using a desktop PC, nothing related to touch. I just click on Paste from Word and that dialog appears. But  even if I press ctrl+v the document is pasted WITHOUT IMAGES, just the text from Word.

**Comment by jacekbogdanski** [comment]
Because only touch devices are handled by clipboard dialog, which is visible on the screenshot you provided. The dialog shouldn't appear on button click using a mouse. In that case, could you provide a demo (e.g. using https://codepen.io) with the issue, where dialog can be opened using desktop PC?

Such a case overall shouldn't exist, as you shouldn't be able to open clipboard dialog. CTRL/CMD+V should correctly work here without opening a dialog. You can see correct behavior on the same browser (Windows7, latest Firefox) you provided:

![clipboard](https://user-images.githubusercontent.com/10279586/68654066-730b2980-052d-11ea-8a7d-17903debac63.gif)

Leaving aside Word content, you can see on the attached gif that clicking buttons show up a notification about `CTRL + V` shortcuts.

**Comment by leonardorame** [comment]
Ok, the dialog appears to have been there since an older version of CKEditor, now I completely wiped out the ckeditor directory and installed it again.

Now the dialog does not show (I get the message "Press Ctrl+V to paste. Your browser doesn‘t support pasting with the toolbar button or context menu option." exactly as your animated gif), but the main issue (images in a Word/Wordpad document not copied) isn't working.

**Comment by leonardorame** [comment]
I made this video from a Windows 7 PC, using Firefox Quantum 70.0.1 and the example from CKEditor 4.13:

![screencast](https://user-images.githubusercontent.com/1405017/68674555-db113e00-0534-11ea-8c01-f5553107f2c1.gif)

As you can see, when I try to paste the copied selection only the text is pasted, but not the image.

**Comment by jacekbogdanski** [comment]
Thanks for clarifying that. We have already reported ticket for the issue with PFW images and as we already know that the issue is not connected to clipboard dialog, please follow https://github.com/ckeditor/ckeditor4/issues/2800 issue for more information about image support. It would be nice if you could share there your Word document which is not correctly handled by Paste From World plugin, so we can test issue fix using your sample also.
