### ISSUE TITLE
Multiple

### ISSUE THREAD

**Issue by TarikAzizov** [ckeditor/ckeditor4#3648]
## Type of report

Task

## Provide description of the task

I have such a document constructor and the ability to add blocks:
![image](https://user-images.githubusercontent.com/47244715/68746411-30b31c80-0601-11ea-87e5-77a9e6f5813e.png)

As I understand it, in order for all the fields to work together with the editor, I supposedly need to redefine them, that is, remove the instances and re-define, BUT this also removes the entered information in all the redefined blocks. Question: is it possible somehow when adding a new block to simply add it to the list of instances, without overwriting the rest?

**Comment by Dumluregn** [comment]
Hello, if I understand your problem correctly you can just use [CKEDITOR.inline()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-inline) (for inline editor) or [CKEDITOR.replace()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-replace) (for classic editor) on the element when it's created.

However please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
