### ISSUE TITLE
The content has only one image and the result is empty

### ISSUE THREAD

**Issue by Hubmayun123** [ckeditor/ckeditor4#3657]
![QQ截图20191116130352](https://user-images.githubusercontent.com/25675858/68988418-02884380-0872-11ea-86c0-43167a4d724b.png)

'Description'   empty

**Comment by f1ames** [comment]
Hell @Hubmayun123,
how did you added the image to editor content? Was it by drag and drop? If so, it's most probably related to CKEditor 4 issue - https://github.com/ckeditor/ckeditor4/issues/1180.

**Comment by Hubmayun123** [comment]
> 地狱@ Hubmayun123，
> 您如何将图像添加到编辑器内容中？是拖放吗？如果是这样，则很可能与CKEditor 4问题- [＃1180有关](https://github.com/ckeditor/ckeditor4/issues/1180)。
Yes, you're right,Is there any solution

**Comment by Hubmayun123** [comment]
> Hell @Hubmayun123,
> how did you added the image to editor content? Was it by drag and drop? If so, it's most probably related to CKEditor 4 issue - #1180.

Yes, you're right,Is there any solution

**Comment by Hubmayun123** [comment]
@f1ames 
Yes, you're right,Is there any solution

**Comment by f1ames** [comment]
The issue is that [`change`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-change) event which is responsible for two-way data binding is fired by upload mechanisms before image HTML is inserted and so outdated (without image) content is propagated (this is what mentioned #1180 should fixed).

The possible workaround is to manually trigger `change` event after upload is done to "refresh" two-way data binding:

```js
editor.on( 'fileUploadResponse', function( evt ) {
    setTimeout( function() {
        evt.editor.fire( 'change' ) 
    }, 0 );
} );
```

To add this listener in the more inline manner through Angular Ckeditor 4 component config you can use [`config.on` property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-on).

**Comment by Dumluregn** [comment]
```plaintext
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
```
