### ISSUE TITLE
Printed content is different than the content in print preview

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3661]
## Type of report

Feature request

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html.
2. Insert page break in the content.
3. Click editors print button.

### Expected result

Page break creates new page / page separation in printable document.

### Actual result

Page break creates new page / page separation in printable document. Page break element is visible in the document on the preceding page.

![image](https://user-images.githubusercontent.com/1061942/69047889-7fdfbf80-09fc-11ea-87ea-e2c88d96aea9.png)

## Other details

* Browser: Tested on Chrome.
* OS: Linux
* CKEditor version: 4.13.0 (4.10.0)
* Installed CKEditor plugins: `pagebreak,print`

**Comment by Comandeer** [comment]
The issue is present for every other fake object inside the editor, e.g. anchor or iframe placeholder: 
<img width="141" alt="" src="https://user-images.githubusercontent.com/1078728/69066507-b54ad400-0a21-11ea-8594-6d149bbb1ef8.png">

It's connected with the fact that our `print` plugin just invokes native print command: https://github.com/ckeditor/ckeditor4/blob/438226ead21db605ffd2e1dc5483621e2d7bf0dd/plugins/print/plugin.js#L37-L41

Therefore it's more of a feature request than bug.

OTOH it also means that for years our `preview` plugin has been totally useless…

**Comment by Comandeer** [comment]
Probably the best course of action will be to join `print` and `preview` plugins. There will be still two buttons: preview one will just open the page with preview and print one – open the page and invoke printing it.
