### ISSUE TITLE
How to prevent CKEditor from stripping < and > (greater-than/less-than) symbol

### ISSUE THREAD

**Issue by vilassagar26** [ckeditor/ckeditor4#3673]
Object Descriptions with ">" or "<" causes "Random" Text
My config Setting is

Expected result is I can use < or > symbol in my editor .

CKEDITOR.editorConfig = function (config) {
	// Define changes to default configuration here.
	// For complete reference see:
	// http://docs.ckeditor.com/#!/api/CKEDITOR.config

    config.htmlEncodeOutput = true;
}

**Comment by msamsel** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
