### ISSUE TITLE
Changing skin

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor4#3703]
Am I able to change skin? I'm creating angular app, that has light and dark theme. I have prepared two ckeditor skins. But even if I destroy ck instance, next instance has previuos skin - not current.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by piernik** [comment]
I've posted but with `ckeditor4.x` tag. Thanks.
