### ISSUE TITLE
Copyformatting Cursor not showing in ie and Edge

### ISSUE THREAD

**Issue by lumills** [ckeditor/ckeditor4#3735]
## Are you reporting a feature request or a bug?

Bug, the copyformatting cursor.svg does not get downloaded (not seen on network trace) and does not appear on the ie and edge browsers, works fine in chrome, firefox, and edge beta.

## Provide detailed reproduction steps (if any)
Do once in edge and once in chrome
1. Go to the ckeditor 4 demo page.
2. Go to document editor tab
3. click on copyformatting button 
![image](https://user-images.githubusercontent.com/58861998/70825492-6894b780-1d99-11ea-80a8-7175e5f98470.png)

### Expected result

*What is the expected result of the above steps?*
When moving your cursor into the document body, it should look like the following:
![image](https://user-images.githubusercontent.com/58861998/70825545-895d0d00-1d99-11ea-9958-aecccf9ffa84.png)

### Actual result

Normal cursor appearance

## Other details
Functionally it works fine
* Browser: 
Chrome: Version 78.0.3904.108 (Official Build) (64-bit)
Edge: Microsoft Edge 44.18362.449.0       Microsoft EdgeHTML 18.18363
IE: Version: 11.535.18362.0

* OS: …
* CKEditor version: 4
* Installed CKEditor plugins: copyformatting

**Comment by Comandeer** [comment]
As it's stated in Copy Formatting styles: [https://github.com/ckeditor/ckeditor4/blob/cc1939111a2cddfec9019b9105dbde2a84372a1e/plugins/copyformatting/styles/copyformatting.css#L10-L13](https://github.com/ckeditor/ckeditor4/blob/cc1939111a2cddfec9019b9105dbde2a84372a1e/plugins/copyformatting/styles/copyformatting.css#L10-L13)

Unfortunately linked issue tracker is no longer available. Additionally both Internet Explorer and Edge based on EdgeHTML are no longer developed. Therefore the mentioned issue can't be fixed in any sensible way.
