### ISSUE TITLE
Moving text inside of table by dragging

### ISSUE THREAD

**Issue by elatedstar** [ckeditor/ckeditor4#3745]
Normally, a user can highlight text words and then click and drag them elsewhere in the text. However, this is not possible with text inside a table. Words inside a table can be highlighted, but then when trying to drag them elsewhere in the table the highlighted term does not move.

CK Editor is not supporting dragging the content inside the table. We have tried with CK editor version 4 and 5. 

Steps to reproduce: 

1. …Insert Table with few rows/columns
2. …Add some contents in cells
3. …Select consents and try to move around

Expected result:
Editor should allow user to move contents.

Actual Results:
Contents are not moved, drag/drop doesn't work.

* Browser: …Chrome 78
* OS: …Windows 10
* CKEditor version: …7.1
* Installed CKEditor plugins: …standard default plugins downloaded as part of package.

**Comment by msamsel** [comment]
Hi @elatedstar,

the case described in you issue sounds more like a new feature request rather than a bug. Please give me info if I understand you correctly.

As a user, you would like to have possibility to drag and drop table cells selected with a tableselection (tablesection plugin allows to select cells vertically)?
For example in a case like this:
![Screenshot 2019-12-19 at 15 30 28](https://user-images.githubusercontent.com/9017322/71181538-9f287180-2274-11ea-9790-73c695cbe851.png)
You would like to have the possibility to move the content around and drop it in a new place.

Should it be available only in the table or should it be possible to drop content outside the table also and create a new one from such content?
Should the content be cut or copied?

Please share you thoughts how this behavior should work.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
