### ISSUE TITLE
What do you recommend are the best practices for integrating ckeditor5 in angular applications 

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor4#3762]
We wold like to customize the editor (add plugins, styles etc.) and not integrate as a sealed package
thanks

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
