### ISSUE TITLE
Upload tab in Link dialog problem

### ISSUE THREAD

**Issue by MoveSv** [ckeditor/ckeditor4#3763]
When I want to set Upload tab in the link dialog as selected it is not working. When I do this with the image dialog it works fine.

This is the code I used to achive what I want:
if (dialogName == 'link') {
            dialogDefinition.onShow = function() {
                this.selectPage( 'Upload' );
            };
        }

* Browser: newest version of Chrome 
* OS: Windows 10
* CKEditor version: 4

**Comment by msamsel** [comment]
There is no `'Upload'` tab in link dialog, there is `'upload'` tab:
https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/plugins/link/dialogs/link.js#L794

I hope it solves this case ;)

**Comment by MoveSv** [comment]
Thanks for your quick response!

But unfortunalety it's not working and i'm getting this screen:
![image](https://user-images.githubusercontent.com/56591689/72239542-9f046300-35e1-11ea-8a10-f7fa0c3fe21e.png)

**Comment by msamsel** [comment]
Because `onShow` function in link dialog definition is used to properly build the dialog and you overwrite it. If you really need to add something during dialog show, then much better solution will be using [`show event`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog.html#event-show).
However, for this particular case, the dialog for the link will bring back focus to `url` field because of `onFocus` method, which is executed after processing `show` related stuff. And I suspect the `onFocus` method is the one which you would like to overwrite.
https://github.com/ckeditor/ckeditor4/blob/8794f9fdd9bcd4cbbd75530dc94e3ca3148731d3/plugins/link/dialogs/link.js#L1037-L1045

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
