### ISSUE TITLE
How can disable CTRL+C and CTRL+V in Ck-editor 4.4.7

### ISSUE THREAD

**Issue by harishebizon** [ckeditor/ckeditor4#3776]
## request for support
How can disable CTRL+C and CTRL+V in Ck-editor 4.4.7

I have used ckeditor library with version 4.4.7 with wysiwyg . My concern is that i want to disable CTRL+C and CTRL+V. The Content will paste only through pastefromword plugin ,not direct copy and paste method using keystroke .

*What steps should be taken to fulfil the task?*

CKEDITOR.editorConfig = function( config ) {
        config.pasteFromWord = true;
        config.pastetext = false;
        config.keystrokes = [[CKEDITOR.CTRL + 86, 'pastefromword']];
};

## Other details
* Browser: Google Chrome
* OS: Apache
* CKEditor version: 4.4.7
* Installed CKEditor plugins: a11yhelp, about, clipboard, colordialog, dialog, div, find, flash, forms, htmlwriter, iframe, image, link, liststyle, magicline, notification, pagebreak, pastefromword, preview, scayt, showblocks, smiley, specialchar, table, tabletools, templates, wordcount, wsc

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by harishebizon** [comment]
Thanks for update
