### ISSUE TITLE
LibreOffice docs

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3797]
## Type of report

Docs

## Provide a description of requested docs changes

After merging #3624 we should prepare simple documentation for PfLO (similar to GDocs one).

**Comment by f1ames** [comment]
PfLO is fully supported in modern browsers - Chrome, Firefox and Edge. In Safari and IEs there is no way to differentiate the content from LO (due to browser native clipboard limitations) and so the plugin is not supported there. However, with PFW enabled (and even without it) many of the styles and formatting is preserved upon pasting (semantic HTML FTW!) for those browsers.

I think it will be good to mention in the docs that Safari and IEs doesn't have full support and some styles may not be preserved, but still the coverage is quite good supporting most popular styles/elements.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs#288.
