### ISSUE TITLE
Some of the styles cannot be copied from external sources

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#3808]
## Normally, if we copy from external Sources, We could be able to copy most of the styles, like font size, color, indent and also background color if any.

Not able to copy, Background color, from the External sources(Paragraph content)

Steps to reproduce.
Copy Some Paragraph contnets wit hsome background color) from an external sources websites
PAste the Contnet into Ck editor

Observe only contnet pasted, but not the background color from the external website.

### Expected result
Wanted the background color also to be retained from te hexternal Websites.

Browser: …Chrome 79
OS: …Windows 10
CKEditor version: …7.1
Installed CKEditor plugins: …standard default plugins downloaded as part of package.

**Comment by Comandeer** [comment]
It's the expected behaviour as there is a default paste filter in Chrome, `'semantic-content'`, which removes most of the styles from copied HTML. It's connected with the fact that Chrome produces very polluted HTML and we decided to filter it before pasting.

This behaviour can be configured via [`pasteFilter` config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter):

```javascript
CKEDITOR.replace( 'editor', {
	pasteFilter: null
} );
```
