### ISSUE TITLE
Is it possible to update a plugin only

### ISSUE THREAD

**Issue by luiznasciment0** [ckeditor/ckeditor4#3839]
Question

I'm using CKEditor 4.3. Is it possible to update only "pastefromword" plugin?

I can't paste text or table from Word to the editor and I think it's because I'm using an old version that was updated for the last time in 2011. I can't upgrade it all.

What should I do?

This is the text in Word:
![image](https://user-images.githubusercontent.com/55008532/73775836-6d586500-4765-11ea-8fbf-c7edbd108441.png)

This is what's happening when I paste it (using Ctrl + Shift + V):
![image](https://user-images.githubusercontent.com/55008532/73775998-bf00ef80-4765-11ea-8876-61896152ddee.png)

Browser: Chrome
CKEditor version: 4,3
Installed CKEditor plugins: Standard

**Comment by f1ames** [comment]
Hello @luiznasciment0,

updating the plugin only is sometimes doable - if there were no changes in the core in the meantime required for the new version of the plugin to work. However, since `pastefromword` had been completely rewritten in CKEditor `4.6` (see [4.6 Changelog entry](https://github.com/ckeditor/ckeditor4/blob/major/CHANGES.md#ckeditor-46)), it not doable since there were some changes in other areas of the editor which are needed for the plugin to work.

Can you tell us, what is your particular case that blocks you from updating entire CKEditor 4 to latest version?

**Comment by luiznasciment0** [comment]
Hey @f1ames thank you for the quick answer!

What's actually blocking me from updating entire CKEditor is that other people made code changes to custom the editor manually (like i18n for example). Then these people leaved and that update turned more complex than it should be.

**Comment by luiznasciment0** [comment]
Plus I tried to update it and it just stopped to work since I lost those changes

**Comment by f1ames** [comment]
I see, that's not an easy situation. Most of CKEditor 4 releases doesn't introduce any breaking changes so upgrading is usually smooth. However, since you have some custom changes in CKEditor 4 files, you will most proboably lost these changes during update as you mentioned.

The best way to introduce any custom changes to the editor is to extract them to separate plugins (or files in case of e.g. CSS) so one can safetly update to a new version. You may try updating version by version - `4.3` -> `4.4` -> `4.5` to see if it helps, but it still will be a cumbersome process :crossed\_fingers: 

Closing this issue as we probably won't be able to help any further, but still feel free to drop a comment.
