### ISSUE TITLE
Include all official plugins in yarn node package

### ISSUE THREAD

**Issue by PseudoNinja** [ckeditor/ckeditor4#3859]
## Type of report

Feature request

## Provide a description of the new feature

When installing CKEditor4 via Yarn, not all plugins are available (ie. `pastefromword`) which causes additional compatibility issues when maintaining the client supported package.

## workaround 
use package source from github instead of yarnpkg

**Comment by f1ames** [comment]
The `ckeditor4` NPM package uses [standard-all preset](https://www.npmjs.com/package/ckeditor4#presets) which means all official plugins are included but some are not enabled by default - so [`extraPlugins` config](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins) should be used to add them. However, `pastefromword` is included in `standard` preset so maybe the issue is somewhere else in your case? Could you share more details?

**Comment by PseudoNinja** [comment]
Went back and reviewed my install appeared stuff was missing when it came out of GitHub, disregard.
