### ISSUE TITLE
Background color is not preserved by 'Print' plugin

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3880]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [CDN](http://cdn.ckeditor.com/4.13.1/full-all/samples/)
2. Paste the following into source mode:
```
<p><span style="background-color:#c0392b">Hello!</span></p>

<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td style="background-color:#66ffff; border-color:#33ff66">a</td>
			<td>s</td>
		</tr>
		<tr>
			<td style="background-color:#66ffff; border-color:#33ff66">d</td>
			<td>d</td>
		</tr>
		<tr>
			<td>d</td>
			<td>f</td>
		</tr>
	</tbody>
</table>
```
3. Click Print button

### Expected result

Background color for text and cell are preserved.

### Actual result

Background color is lost.

## Other details

Note that preview for this content is correct (both displayed after clicking `Preview` button and after clicking `Print` button), so it may not be possible to fix it on our side.

* Browser: all
* OS: macOS
* CKEditor version: `4.14.0`, `4.10.0`
* Installed CKEditor plugins: Print

**Comment by Dumluregn** [comment]
I updated issue title and description as it turned out that it also concerns text background color.

**Comment by f1ames** [comment]
It is more complex issue as it depends on the browser (and print settings) too. In Chrome by default background is not printed. Special option needs to be enabled:

![](https://rewordify.com/images/PC%20and%20mac-chrome.gif)

Then it looks good:
![Zrzut ekranu z 2020-02-20 15-44-22](https://user-images.githubusercontent.com/1061942/74945626-5ddd4b00-53f8-11ea-865d-c0394e4eb87d.png)

And e.g. in FF, I wasn't able to find such option and it looks like this:
![Zrzut ekranu z 2020-02-20 15-39-13](https://user-images.githubusercontent.com/1061942/74945666-6cc3fd80-53f8-11ea-8a47-811dcdfd5496.png)

but maybe it's Linux only because I can see the similar option is generally available in Firefox too.

Let's close it as upstream issue.
