### ISSUE TITLE
Update Browser Compatibility Docs by info about Edge Chromium and Edge edgehtml

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3882]
## Type of report

Docs

## Provide a description of requested docs changes

As a follow-up of #3655 we should update [Browser Compatibility docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html#officially-supported-browsers) to indicate we support both newest Edge version (Chromium-based) as well as the last version using the old `edgehtml` engine.

**Comment by f1ames** [comment]
Recently, I have installed new Edge Chromium on Windows 10 and it simply replaced the older EdgeHTML version. So probably the beta channels can be installed separately but the stable version replaces the old Edge (good for us IMHO). So we may probably say in our docs the we support latest version (so same as for Chrome, Firefox, Safari).

And the Edge compatibility/legacy/IE mode uses IE11 underneath (see https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#what-is-ie-mode), so it should work fine since we support IE11.

Btw (see [here](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#ie-mode-doesnt-support-the-following-internet-explorer-functionality)):

> ### **IE mode doesn't support the following Internet Explorer functionality**
> 
> *   IE11 or Microsoft Edge F12 developer tools

:point\_up: Sounds like fun to debug anything there :grimacing:

**Comment by Dumluregn** [comment]
So maybe we don't have to change the docs at all? Or do we want to write explicitly something like `we are aware there is new Edge and we support it fully`?

**Comment by f1ames** [comment]
@Dumluregn since it's stated as "Latest Microsoft Edge" it still makes sense so this part could be left as is. I wonder if we should add Edge compatibility mode somewhere in **Internet Explorer** section :thinking:

**Comment by Dumluregn** [comment]
As 1) it is a part of Edge and not a standalone browser and 2) as it is written in the article you provided this is an edge Edge feature (🍌) (you need hacks to open a webpage in IE mode unless this webpage explicitly tells it is designed for IE) I'd just go with a short inline mention.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs@04c362a.
