### ISSUE TITLE
Toolbar disappears when scroolling down

### ISSUE THREAD

**Issue by bibouu** [ckeditor/ckeditor4#3891]
BUG

hello,

Im working with CkEditor 4.6, and i have a bug when i am scrolling down in the body, the toolbar (with format, font, size buttons) disappears.

How can i make this toolbar fix ?

### Expected result

Toolbar (with format, font, size buttons) not disappears.

### Actual result

Toolball disapear

## Other details

* Browser: Chrome
* CKEditor version: 4.6

**Comment by Dumluregn** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
