### ISSUE TITLE
Outdent doesn't work with some pasted content

### ISSUE THREAD

**Issue by csmaclaga** [ckeditor/ckeditor4#3899]
## Are you reporting a feature request or a bug?
bug

## Provide detailed reproduction steps (if any)
1. Use the full nightly build (https://nightly.ckeditor.com/20-02-27-07-04/full/samples/)
2. Create an html document with the following content, open with a browser and copy the content:
```html
<html>
  <body>
  Line 0<br />
    <div style="margin-left:20px">
      <div>
      Line 1<br />
      Line 2<br />
      Line 3<br />
      </div>
    </div>
  </body>
<html>
```

3. Paste the content into CKEditor. Note that the content is rendered as expected.
4. Place the cursor on Line 1

### Expected result
Should be able to outdent Line 1

### Actual result
Outdent is disabled

## Other details

* Browser: FF 68.4
* OS: macOS 10.14.6
* CKEditor version: nightly
* Installed CKEditor plugins: full
<img width="343" alt="Untitled" src="https://user-images.githubusercontent.com/35376265/75474680-6805c900-5965-11ea-98c9-e2f06199c039.png">

**Comment by Dumluregn** [comment]
Hello,
you can't outdent `Line 1` because you nested the content - check out that 
```html
<p>Line 0</p>

<div style="margin-left:20px">
Line 1<br />
Line 2<br />
Line 3
</div>
```
will have indent button active. Still, it will not work, as default margin for indent is 40px, so you either have to change your value or just pass a config option [`CKEDITOR.config.indentOffset`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-indentOffset) with your custom value.

**Comment by csmaclaga** [comment]
@Dumluregn - I understand that outdent works without the nested content.
Can you provide some explanation (or point me to some documentation) as to why this bug is invalid?

The user would like to be able to paste content from another source, and then work with that content in CKEditor.
The only workaround that we have for them at this point is for them to remove all styling from the impacted content, and then reapply the removed styling with CKEditor

**Comment by csmaclaga** [comment]
@Dumluregn - any response to the question above?

**Comment by Dumluregn** [comment]
Only the indentation of the most inner element is checked, so if you have a nested element which is not indented comparing to it's parent, then you can't outdent it - and this is your case where you have `p` elements inside a `div`. To decrease indentation of the entire `div` element, you would have to place a caret inside the outer `div` but outside the inner one, which is not possible in an example you provided (where one `div` is nested inside the other without any other elements), hence there is no bug or inconsistency in the way CKEditor handles it. And since this issue tracker serves for reporting bugs and new features only, I closed this issue. Still, you can leave your implementation question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues.

Last but not least, if you have CKEditor license, please contact our support team through [a dedicated support channel](https://ckeditor.zendesk.com/agent/).
