### ISSUE TITLE
'CKEDITOR.dom.element.createFromHtml()' method can't create table elements

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3901]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [Codepen](https://codepen.io/dumluregn/pen/wvadxoB?editors=1010)
2. Click button
3. Examine editor contents

### Expected result

Created `td` element should have type `1`

### Actual result

It has type `3`, which means it's not an element but a text node.

## Other details

You can use input below the editor to check that the same issue occurs for e.g. `tr` or `th` elements.

* Browser: all
* OS: macOS
* CKEditor version: 4.13.1 and earlier
* Installed CKEditor plugins: core

**Comment by Comandeer** [comment]
## The issue

Our `CKEDITOR.dom.element#createFromHtml()` is implemented using `innerHTML` setter for newly created `div` element: https://github.com/ckeditor/ckeditor4/blob/411985373e833a0df76e4ebd0afb45f337612725/core/dom/element.js#L60-L66

Such case is described in details in the specification: [The `InnerHTML` mixin](https://w3c.github.io/DOM-Parsing/#the-innerhtml-mixin) definition points to [HTML fragment parsing algorithm](https://html.spec.whatwg.org/multipage/parsing.html#html-fragment-parsing-algorithm), which include [reset the insertion mode appropriately](https://html.spec.whatwg.org/multipage/parsing.html#reset-the-insertion-mode-appropriately) step that requires the ["in body" insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody) for `div` elements. The "in body" insertion mode describes the table cells case as a parse error:

> A start tag whose tag name is one of: "caption", "col", "colgroup", "frame", "head", "tbody", "td", "tfoot", "th", "thead", "tr"
>
> [Parse error](https://html.spec.whatwg.org/multipage/parsing.html#parse-errors). Ignore the token.

The HTML parser behaves the same way for every cell outside of the `table` and `template` elements (as ["in template" insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intemplate) has special handling for table elements) and it can be easily checked by opening some HTML page with a `td` element directly inside the `body` element and inspecting its DOM. Example URL of such page: `data:text/html;charset=utf-8;base64,PCFET0NUWVBFIGh0bWw+PG1ldGEgY2hhcnNldD0iVVRGLTgiPjx0aXRsZT5UZXN0PC90aXRsZT48Ym9keT48dGQ+Q2VsbDwvdGQ+PC9ib2R5Pg==`.

## Proposed solutions

1. Treat it as upstream issue and just close it – the easiest one 😉.

2. Switch from `div` to `template` tag. The latter one would allow us to generate _de facto_ every HTML element. However [`template` is not supported in IE](https://caniuse.com/#feat=template), so a no-go for us 😞.

3. Introduce some heuristics to try guessing if we can use `div` or we need some other, more specialised element. Can be tricky and need much effort (because it would also require some cleaning after creating the element – see the next point), but at the same time wouldn't need any action from the user – they could still just pass their HTML code and the magic would happen.

4. Add `options` parametr to `CKEDITOR.dom.element#createFromHtml()`, which can hold the `context` option:

    ```javascript
    var td = CKEDITOR.dom.element.createFromHtml( '<td>Cell</td>', {
    	context: 'table'
    } );
    ```

    However this approach has two downsides:

    1. We have undocumented `ownerDocument` parameter. Adding `options` one would require some effort to support both old signature (`createFromHtml( html, ownerDocument )`) and the new one (`createFromHtml( html, options)`).

    2. Even with setting `context` to `table`, the user won't get just cell element, as [HTML parser generates additional boilerplate for tables](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intable):

        > A start tag whose tag name is one of: "td", "th", "tr"
        >
        > […]
        >
        > [Insert an HTML element](https://html.spec.whatwg.org/multipage/parsing.html#insert-an-html-element) for a "tbody" start tag token with no attributes, then switch the [insertion mode](https://html.spec.whatwg.org/multipage/parsing.html#insertion-mode) to "[in table body](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-intbody)".
        >
        > Reprocess the current token.

Considering all of the above, I'm for closing the issue as an upstream.

**Comment by Dumluregn** [comment]
Thanks for the interesting research 👍 It seems that treating this as an upstream makes much sense, but... to create e.g. `td` element with some complex inner content I have to use something like this instead:
```javascript
var td = new CKEDITOR.dom.element( 'td' );
td.setHtml( ... );
```
So I thought the `createFromHtml()` method could work in the similar manner, i.e.:
1. Try to create element the old way
2. Use `RegExp` to check if the created element is correct (by comparing expected and actual tags)
3. If they are not the same, use the extracted tag to create new element (which will be a container for the rest of the HTML) as I proposed above: `var element = new CKEDITOR.dom.element( [extracted tag here] );`
4. Set HTML of the created element using the remains of the passed argument (stripped of the most outer tags).

This approach doesn't seem very complicated, but there may be some obstacles I don't see yet. (e.g. I don't know what if passed HTML is invalid). And I'm not sure there is enough use cases to justify my will of saving one line of code 😅 So if you find the solution proposed by me to be too hacky I can live without it.

**Comment by jacekbogdanski** [comment]
Proposed solutions in https://github.com/ckeditor/ckeditor4/issues/3901#issuecomment-594503861 seem hacky or don't work in IE. @Dumluregn does this issue really affects you? I mean, if you have some single case that requires creating `td` element, I would honestly don't care about this issue. `createFromHtml` works correctly with spec and this issue should be treated as upstream.

Also, using regex for HTML manipulation is rather a bad idea and should be avoided if possible. We have a single report about the issue from our own circle which doesn't affect users and can be easily avoided. The only thing I would eventually change here is additional docs description of how this function works and warning that may create invalid results if used incorrectly.

**Comment by Dumluregn** [comment]
So if this didn't bother anyone else and it's not our fault I'm closing this :man\_shrugging:
