### ISSUE TITLE
ckeditor 4 Balloon toolbar for the text selection

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor4#3908]
I want ckeditor 4 Balloon toolbar for the text like in the ckeditor 5. How can I do that. Can anyone guid me.

As in https://ckeditor.com/docs/ckeditor4/latest/examples/balloontoolbar.html this demo ballon toolbar show on link and image, I need to show that on text selection.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
