### ISSUE TITLE
Text font and background colors not copied between broswer tabs

### ISSUE THREAD

**Issue by kichenko** [ckeditor/ckeditor4#3918]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. open first tab (https://ckeditor.com/ckeditor-4/demo/#document)
2. open second tab (https://ckeditor.com/ckeditor-4/demo/#document)
3. on the first tab select some text and set font and backgroud colors
4. select this text and copy on the second tab

### Expected result
 text with font and background colors from first tab copied to the second tab
### Actual result
from the first tab text copied without font and background colors

PS: ckeditor5 support this feature (https://ckeditor.com/ckeditor-5/demo/#document)

## Other details
* Browser: Google Chrome 80.0.3987.132
* OS: windows 10
* CKEditor version: ckeditor4 v4.14.0
* Installed CKEditor plugins: from demo page (https://ckeditor.com/ckeditor-4/demo/#document)

**Comment by Comandeer** [comment]
It's connected with the fact that [Chrome and Safari has default paste filter](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter) that removes every non-semantic content, including color styling. Such default setting was introduced due to the fact that both Chrome and Safari paste very "messy" HTML.
