### ISSUE TITLE
The classes of some tags are deleted

### ISSUE THREAD

**Issue by erelsgl** [ckeditor/ckeditor4#3923]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

See this fiddle:

https://jsfiddle.net/32jcuz8o/3/

It contains a div with some tags with a "test" class.

The test class should make a red background.

In the editor itself, no red background is shown. Moreover, in the source, the "test" class is completely removed from the "p" tag.

### Expected result

Keep the classes on all tags.

### Actual result

Some "class" attributes are gone.

## Other details

* Browser: Firefox 73
* OS: Ubuntu 16.04
* CKEditor version: 4
* Installed CKEditor plugins: N/A

**Comment by Comandeer** [comment]
It works as intended, due to our [Advanced Content Filtering feature](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html): it removes every attribute or style that are not explicitly allowed. You can allow `.test` class using [`extraAllowedContent` config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraAllowedContent).

However such style won't be automatically available inside the editor, as the editable area is inside `iframe` element by default. You'll need to add your CSS into the editor via [`CKEDITOR.addCss()` function](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss) or via [`contentsCss` config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss).

PoC: https://jsfiddle.net/Comandeer/fs81krmq/
