### ISSUE TITLE
CKEDITOR.replaceAll() not working appropriately

### ISSUE THREAD

**Issue by Raja77** [ckeditor/ckeditor4#3956]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm using CKEditor version 4.

I've an issue with CKEDITOR.ReplaceAll(). 
It is giving editor-element-conflict issue.

Actually what is happening, when the page gets partial postback all the content of Editor get rendered in HTML and not changed to the normal text then.

Is there any solution for this in C# with ASP.NET.

Regards,
-Raja

### Expected result

*What is the expected result of the above steps?*
It should be as the text without tags

### Actual result

*What is the actual result of the above steps?*
But the content after rendering is like this with html tags
<p>&npsp;</p> <p> Hello troy</p><p>&nbsp;</p><p>I want to play a game with you!</p>

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
ASP.NET integration has not been developed since CKEditor 3.6.6.2, therefore newer CKEditor versions are not supported. It might be possible to customise it on your side to support newer CKEditor, but it will require some code changes.

You can download CKEditor for .NET at [https://download.cksource.com/CKEditor/CKEditor.NET/](https://download.cksource.com/CKEditor/CKEditor.NET/) however this is legacy software and we’re not encouraging to use it.

Please note that CKEditor is a pure JavaScript application that can be integrated with any other web application (including ASP.NET applications) using a very simple JavaScript API. This is one of the reasons why we stopped maintaining server side integrations. To learn how to integrate CKEditor using JavaScript API, check the quick start guide: https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html

Apart from the official download page [https://ckeditor.com/ckeditor-4/download/](https://ckeditor.com/ckeditor-4/download/) and CDN [https://cdn.ckeditor.com/](https://cdn.ckeditor.com/) The editor (the JavaScript library) is available also as Nuget packages:
* https://www.nuget.org/packages/ckeditor-full/
* https://www.nuget.org/packages/ckeditor-standard/
* https://www.nuget.org/packages/ckeditor-standard-all/
* https://www.nuget.org/packages/ckeditor-basic/

**Comment by Raja77** [comment]
Hello Jacek,

Hope you're doing good today!

I'm using CKEditor version 4 for the application of ASP.NET with C#.
I've an issue with CKEDITOR.ReplaceAll(). It is giving editor-element-conflict issue.

If I had to use it like this: 
**_<CKEditor:CKEditorControl ID="CKEditor1" runat="server"></CKEditor:CKEditorControl>_**
It works fine for me.

However I'm using it **_dynamically_** in my code behind file of C# like this
******************
CKEditor.NET.CKEditorControl txtEditor = new CKEditor.NET.CKEditorControl();
                txtEditor.ID = "txtEd" + (aQuestionID.ToString());
                txtEditor.Height = 300;
                txtEditor.BasePath = "../ckeditor/";
                txtEditor.Toolbar = "Basic";
******************
So in the above code there are many instances after post-back of the page CKEditor gets hide for some time so that is why I'm using CKEDITOR.replaceAll();



Could you please help me in this regard!
