### ISSUE TITLE
add hotkey to bring up the 'emoji' plugin

### ISSUE THREAD

**Issue by weichuan-dong** [ckeditor/ckeditor4#3960]
I've been trying to add a hotkey to bring up "emoji" plugin. However I wasn't successful. I've tried this:
editor.setKeystroke(CKEDITOR.CTRL + 69 /* char 69 = e */, 'emoji');
and
editor.addCommand( 'emoji', {
exec: function( editor, data ) {
//new EmojiDropdown( editor, this );
self.createEmojiBlock();
}
} );
It doesn't work.
I know it's not a bug. But just wondering if someone can point me a direction where should I go?

Thanks!

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
