### ISSUE TITLE
sytle pop div position is upper

### ISSUE THREAD

**Issue by mzxjhx** [ckeditor/ckeditor4#3969]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/12944455/78219428-161b0a80-74f2-11ea-8454-60844a3ed171.png)

 open ckeditor 4 demo on https://ckeditor.com/ckeditor-4/demo/ , and F12. Then i put debug tool to bottom ,click styt button .the positoin of pop div is upper,not the right position.

when import ckeditor in jsp, put some elements like div or somethings above ckeditor, then th style pop div 's position is not right. the positoin can not be right until the ckeditor is the top element.

## Other details

* Browser:chrome
* OS:window 10
* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
The popup menu works as intended: if it has not enough space to be fully visible after opening, it switches to the opening upwards. This is the case from the screen: bottom of the viewport (due to open devtools) is too close to the popup, so it "decided" to open upwards, as the top of the viewport is farer away.
