### ISSUE TITLE
Bootstrap classes

### ISSUE THREAD

**Issue by anabeatrizzz** [ckeditor/ckeditor4#3971]
## Type of report

CKeditor is not seeing my bootstrap classes.

## Provide description of the task

I have elements with the bootstrap class `text-center` and when I put `contenteditable="true"` CKeditor do always the alignment to the right. I also have some others classes with the same issue. How to proceed? I'll wait for answers.

## Other details

* Browser: Google Chrome
* OS: Linux
* CKEditor version: 4

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
