### ISSUE TITLE
UploadFile asp.net core 3.0

### ISSUE THREAD

**Issue by HKhedr** [ckeditor/ckeditor4#3983]
This code work fine in asp.net MVC but not working with asp.net core I get "Image source URL is missing."

c# Code
`        [HttpPost()]
        public ActionResult UploadCkEditorImage(IFormFile upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {

            if (upload.Length <= 0)
                return null;

            var _uploadFilesPath = Path.Combine(_host.WebRootPath, "files");
            if (!Directory.Exists(_uploadFilesPath))
                Directory.CreateDirectory(_uploadFilesPath);
            var _fileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName);
            var _filePath = Path.Combine(_uploadFilesPath, _fileName);
            using (var stream = new FileStream(_filePath, FileMode.Create))
            {
                upload.CopyTo(stream);
            }
            string requestUrl = new Uri(HttpContext.Request.GetDisplayUrl()).GetLeftPart(UriPartial.Authority);

            var url = string.Format("{0}/{1}/{2}", requestUrl, "files", _fileName);

            // passing message success/failure
            const string message = "Image Saved";

            // since it is an ajax request it requires this string
            var output = string.Format(
                "<html><body><script>window.opener.CKEDITOR.tools.callFunction({0}, \"{1}\", \"{2}\");</script></body></html>",
                CKEditorFuncNum, url, message);

            return Content(output);
        }
`

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
