### ISSUE TITLE
Add more than one text editor 

### ISSUE THREAD

**Issue by fatimah-33** [ckeditor/ckeditor4#3986]
## Type of report

Feature request

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*
Can I add multiple of editor on the same page? 
For example, I am using it for a content management system. And I required to add three editors to edit the content of the HTML page. Can I do that?

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them. You may always refer to [CKEditor 4 documentation](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html#adding-ckeditor-to-your-page) too.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
