### ISSUE TITLE
The anchor link navigation is not working.

### ISSUE THREAD

**Issue by hmnshuagarwal** [ckeditor/ckeditor4#3988]
Descriptive summary – We are using the link plugin for navigating to an anchor text but the link does not work. 
In fact none of the anchor links are working on click they seems to be disabled for some reason whether the editor is in editable mode or disables mode.

Steps to reproduce –  Go to nightly build 2. select a text as anchor and provide name. 3. Select any text and link it to the above anchor. 4. try to navigate.

Browser name and OS – Chrome v78

**Comment by Comandeer** [comment]
Can you provide more details? What do you mean by "navigating"?

**Comment by hmnshuagarwal** [comment]
navigation in terms of linking to an anchor i.e. scroll to the linked anchor

**Comment by Comandeer** [comment]
All links inside the editor are disabled to enhance the editing experience. Additionally, due to how anchors are represented inside the editor, it's not possible to navigate to them inside the content being edited. However every links work after exporting data from the editor, e.g. via [`editor#getData()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-getData).
