### ISSUE TITLE
Any text font increase and decrease button

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [ckeditor/ckeditor4#4013]
@bantic  Hello

This is the best and powerful html text editor but currently finding button in toolbar for 
increase font size or decrease font size   

I don't know 
so is this possible in any plugin or is feature ?

Thank you

**Comment by f1ames** [comment]
Please refer to [`font` plugin](https://ckeditor.com/cke4/addon/font).

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
