### ISSUE TITLE
Unminified Source Code for Development

### ISSUE THREAD

**Issue by blackdrago** [ckeditor/ckeditor4#4022]
## Type of report

Feature request

## Provide description of the new feature
Right now, when I include CKEditor in package.json and install with NPM, there is no way for me to get access to any unminified code -- for both ckeditor and ckeditor4.

The project I'm working on is set up to handle assets based on instance location---for example, development instances have unminified assets (for debugging sanity) and production instances have minified assets. But in order for this to work, we need access to unminified vendor assets/source code--which doesn't seem to be possible with CKEditor at the moment.

I've looked into this related thread: https://github.com/ckeditor/ckeditor4-releases/issues/11 -- which describes one solution (building CKEditor locally). I'm considering this, but I am running into these issues:

1. If I build from this Github repo, am I building a stable version of CKEditor? And what version am I building?
2. It seems like I can't use NPM to get the package ckeditor4-presets--which defeats the purpose of using asset management to handle dependencies/upgrades/version conflicts. 

So I suppose my 'feature request' is either unminified source files in the npm packages OR an NPM package for ckeditor4-presets--so I can still use NPM to handle dependencies/etc.

**Comment by f1ames** [comment]
Hello @blackdrago,

you can get unminified CKEditor 4 code in a few way:

*   Via `ckeditor/ckeditor4` repo (so this repo). Each release is tagged properly (e.g. [latest 4.14](https://github.com/ckeditor/ckeditor4/tree/4.14.0)) so you will get stable code, same as released one. Also remember that you can use github tags directly in your `package.json`.
*   Via [`ckeditor4-dev` NPM package](https://www.npmjs.com/package/ckeditor4-dev) - basically the same code as above, but through NPM.

The best approach would be to have `devDependency` for unminified CKEditor 4 version (form one of the sources mentioned above) and then production dependency on minified version - this way you don't have to build it yourself but still will get the same code.

---

As a reminder, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
