### ISSUE TITLE
How to integrate moono skin

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4#4073]
## Type of report
It is a question on integration of moono skin with `ckeditor4-react` full editor.

## Provide description of the task
I integrated the full `CKEditor4` in my react app, `CKEditor.editorUrl = 'https://cdn.ckeditor.com/4.14.0/full/ckeditor.js'`

And now I want to integrate a moono skin , but I don't know how to do it. 

I integrated `wiris mathtype` using 
```
      CKEDITOR.plugins.addExternal('ckeditor_wiris', 'https://ckeditor.com/docs/ckeditor4/4.13.1/examples/assets/plugins/ckeditor_wiris/', 'plugin.js')
```
Is there a way to do like this for `moono skin`?

This is how it looks now.
<img width="713" alt="Screen Shot 2020-05-26 at 5 21 36 PM" src="https://user-images.githubusercontent.com/51118408/82989852-f4c33000-a003-11ea-9845-7fd7d7663562.png">
*What steps should be taken to fulfil the task?*
1. Create React App
2. Add `ckeditor4-react` package
3. Change the editor url to  'https://cdn.ckeditor.com/4.14.0/full/ckeditor.js'
## Other details

* Browser: …
* OS: OSX
* CKEditor version: 4
* Installed CKEditor plugins:

**Comment by jacekbogdanski** [comment]
@henok-tesfaye it's highly recommended to not use CKEditor 4 docs assets as a CDN for MathType plugin, as it supposed to be used only by CKEditor 4 documentation page (https://ckeditor.com/docs/ckeditor4/latest/index.html).

Please, take a look at [MathType integration page on Wiris documentation page](https://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/ckeditor?utm_source=ckeditor&utm_medium=website&utm_campaign=pr_generic#external_integration) - it seems like Wiris exposes some CDN-like service for a plugin. 

> Is there a way to do like this for moono skin?

Moono skin is available in `full` and `full-all` presets, so you just need to update [config.skin](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-skin) property.

---
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by f1ames** [comment]
@henok-tesfaye, as @jacekbogdanski mentioned our docs assets shouldn't be used as CDN as it may change anytime breaking your application. Please refer to MathType integration documentation linked in the comment above.

Please also note that in order to use the MathType Wiris plugin you need to have a valid license, which comes with a dedicated technical support. [Contact us](https://ckeditor.com/contact/) for more details.

**Comment by henok-tesfaye** [comment]
<img width="1663" alt="Screen Shot 2020-05-27 at 11 31 15 PM" src="https://user-images.githubusercontent.com/51118408/83069222-368abf80-a072-11ea-9fb8-d23b85949d97.png">

@jacekbogdanski @f1ames Thank you so much, yes I did.

**Comment by henok-tesfaye** [comment]
<img width="604" alt="Screen Shot 2020-05-28 at 10 04 18 AM" src="https://user-images.githubusercontent.com/51118408/83109771-a5940280-a0ca-11ea-97de-593dfe1319c1.png">

@jacekbogdanski I'm getting this error, Not Found` after adding `sking: moono` to cofig.

**Comment by jacekbogdanski** [comment]
Right, seems like I misinform you, sorry for that. Moono skin is available in `standard-all` and `full-all` presets. You can verify that at https://ckeditor.com/cke4/presets-all

Note that you can also select plugins by your own using our builder app - https://ckeditor.com/cke4/builder

**Comment by henok-tesfaye** [comment]
Thank you, It worked with `full-all` preset.
The online builder is generating many files which is hard to submit as a PR.
