### ISSUE TITLE
Better name for Placeholder Text plugin?

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4086]
## Type of report

Task

## Provide description of the task

Recently we have introduced **Placeholder Text** plugin (see #3793) which is the same thing as [editor placeholder in CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html) and also as [native `placeholder` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder).

However, since we already have [Placeholder](https://ckeditor.com/cke4/addon/placeholder) plugin, the new plugin name might be confusing.

WDYT? Any ideas for different name? cc @AnnaTomanek @Comandeer @jacekbogdanski

**Comment by Dumluregn** [comment]
Maybe something like `Filler Text` would do.

**Comment by jacekbogdanski** [comment]
I can also add `Blank Text / config.blankText`, `Empty Value / config.emptyValue`, but:

The issue with a `placeholder` name is that it's the default attribute for HTML and in most cases, it's also the first name that comes to mind when searching for such feature in WYSIWYG editors. `placeholder` is as a domain unique name - not sure if it won't be more confusing using totally different name instead of current `placeholdertext`. I mean, it may be confusing which one to use between `Placeholder Text` and `Placeholder`, but giving it a different name will make this plugin less discoverable. Some users may just not find the feature they are searching for, thinking it's not implemented.

**Comment by Comandeer** [comment]
Maybe "Editor Placeholder"? It will still be a placeholder and word "editor" will indicate the purpose of it.

**Comment by f1ames** [comment]
I agree with what @jacekbogdanski wrote in https://github.com/ckeditor/ckeditor4/issues/4086#issuecomment-635900707 as `placeholder` is just standard name here. And so to distinguish it from our `placeholder` plugin, @Comandeer proposal seems like a best option here - `Editor Placeholder` sounds better than `Placeholder Text` and should be a little less confusing. At the same time it keeps `placeholder` part in opposite to other proposals. WDYT?

**Comment by AnnaTomanek** [comment]
"Editor placeholder" is something that we use in CKEditor 5 too: https://ckeditor.com/docs/ckeditor5/latest/features/editor-placeholder.html

**Comment by jacekbogdanski** [comment]
LGTM, I suppose in that case we would have:
plugin name: `Editor Placeholder`
configuration option: `config.placeholder` ?

**Comment by f1ames** [comment]
@jacekbogdanski I would stick with the convention we have - consistent API is more intuitive and easier to use/remember. It looks a little less attractive but still better to keep things consistent instead of making an exception to have one more friendly config name.
