### ISSUE TITLE
Content is not showing when double angular brackets are passed in CKeditor 4 data

### ISSUE THREAD

**Issue by kruzalmighty** [ckeditor/ckeditor4#4097]
I need to pass dynamic data using  double angular bracket within ckeditor4 data.
example :  <<mobilenumber>> 
But CKeditor is omitting the content inside the angular bracket. 
When i pass data to server <<mobilenumber>> is replaced with <>

I have used these configs inorder to avoid converting entities into code
**basicEntities:false,
entities: false,
forceSimpleAmpersand: false**

CKeditor4 version 4.13.0
Angular 8

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
