### ISSUE TITLE
style tags inside <em> makes the Italics button not toggle the italics

### ISSUE THREAD

**Issue by fuzeckunkel** [ckeditor/ckeditor4#4102]
Discovered with a document that was originally pasted from word I think probably, but I figured out what was causing it and duplicated it in a new document.

Add a style attribute to an element: `<em style="font-size:18pt;">This is emphasized</em>`
Highlight any of the text (not in source mode)
Click the "I" button in the toolbar to toggle Italics.
✔️ Expected result
Italics should be removed/toggled for the highlighted text

❌ Actual result
Italics is not removed/toggled

📃 Other details
Browser: Chrome
OS: Windows
CKEditor version: 4.14.0
Installed CKEditor plugins: CKFinder

**Comment by jswiderski** [comment]
Styles system in CKEditor works in a way that a given style has has to be exact match in order to be toggled on and off. It is true that CKEditor will not remove the `<em style="font-size:18pt;">` style unless there is such defined in [Styles Dropdown](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_styles.html).

The main problem I have with the validity of this ticket is that you can't get `<em style="font-size:18pt;">` inside the editor (even when pasting from MS Word) unless you have Advanced Content Filter (ACF) disabled and you are inserting/pasting that specific HTML. In cases when developer allows any HTML it is always possible to insert something which will make editor not work as expected thus we cannot really mark this ticket as valid.

A solution here is either adding below style rule to `styles.js` file so that it is possible to add/remove this specific rule:
`
{ name: 'Big Italic',	element: 'em', styles: { 'font-size':'18pt' } },
`
or making your ACF work in a way that it doesn't such styles being pasted into editor.
