### ISSUE TITLE
Can not integrate Spreadsheet plugin to my project.

### ISSUE THREAD

**Issue by armang98** [ckeditor/ckeditor4#4124]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm trying to integrate Spreadsheet plugin to my project but it doesn't work. I get some errors in the console.
When the page is loaded I get this error in the console.
![image](https://user-images.githubusercontent.com/37144283/85621156-ddfd1100-b675-11ea-81fa-6d7942284854.png)

And when trying to create a Spreadsheet table getting these errors in the console.
![image](https://user-images.githubusercontent.com/37144283/85621266-0d138280-b676-11ea-909b-b2f4b304be34.png)

### Expected result

*What am I does wrong? Or what may missed in my project?*

## Other details

* Browser: Google Chrome 
* OS: Windows 10
* CKEditor version: full/4.14.0
* Installed CKEditor plugins: All expected plugins for this plugin (XML,
ajax,
balloonpanel,
balloontoolbar,
mentions,
spreadsheet)

**Comment by f1ames** [comment]
@armang98 could you share more details on your issue and what's the exact problem? Please also refer to [Spreadsheet plugin dev gudies](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_spreadsheets.html) to see how to install and configure the plugin.

**Comment by armang98** [comment]
@f1ames I download manually from the Add-ons Repository and added in plugins/ directory. After this, I'm import plugin from a directory and added as an extra plugin. And when I run my project I got these errors in the console.

**Comment by armang98** [comment]
Can anyone help me?

**Comment by jacekbogdanski** [comment]
@armang98 did you configured license key according to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_spreadsheets.html#enable-the-spreadsheet-plugin? Could you paste console error here?

**Comment by armang98** [comment]
@jacekbogdanski Oh sorry, of course.
![image](https://user-images.githubusercontent.com/37144283/85727349-fc135180-b707-11ea-956f-3fab0c89476b.png)

**Comment by jacekbogdanski** [comment]
@armang98 I downloaded CKEditor 4 with Spreadsheets plugin using [CKEditor 4 Online Builder](https://ckeditor.com/cke4/builder) and everything works fine, the only thing I had to do is just adding license key e.g. using
```js
CKEDITOR.config.spreadsheet_licenseKey = 'xxx';
```
It seems like there is something wrong with your configuration. Could you attach zip file with the whole editor package, of course excluding license keys and everything which could be considered confidential by you? I'm asking for minimal demo which could allow us to find out what's wrong.

I can also recommend contacting CKEditor 4 team using [Support Contact](https://ckeditor.com/contact/) if you would like to avoid sharing your source files publicly.

**Comment by armang98** [comment]
@jacekbogdanski I installed CKEditor using bower install and downloaded Spreadsheet plugin manually from the Add-ons Repository and added in plugins/ directory. 
In config file added plugin like this 
`CKEDITOR.plugins.addExternal('spreadsheet', '<path>/spreadsheet/plugin.js');`
and added as extra plugin. Also spreadsheet_licenseKey added.
Sorry, I can't provide the source code of the project. 
Can you provide a whole required list of plugins for the Spreadsheet plugin? 
I already have these plugins manually.
xml,
ajax,
balloonpanel,
balloontoolbar,
mentions,
spreadsheet)

**Comment by armang98** [comment]
@jacekbogdanski Also I get this warning on console. I thought it may help to get the error.
![image](https://user-images.githubusercontent.com/37144283/85954532-2cb5ee00-b989-11ea-8fbb-dd7ce350b6d2.png)

**Comment by jacekbogdanski** [comment]
@armang98 Spreadsheet requires:

* [toolbar](https://ckeditor.com/cke4/addon/toolbar)
* [widget](https://ckeditor.com/cke4/addon/widget)
* [balloonpanel](https://ckeditor.com/cke4/addon/balloontoolbar)
* [balloontoolbar](https://ckeditor.com/cke4/addon/balloontoolbar)
* [autocomplete](https://ckeditor.com/cke4/addon/autocomplete)
* [mentions](https://ckeditor.com/cke4/addon/mentions)
* [textmatch](https://ckeditor.com/cke4/addon/textmatch)
* [textwatcher](https://ckeditor.com/cke4/addon/textwatcher)
* [ajax](https://ckeditor.com/cke4/addon/ajax)
* [xml](https://ckeditor.com/cke4/addon/xml)

plugins to work. 

You should also make sure that all assets from [Spreadsheet](https://ckeditor.com/cke4/addon/spreadsheet) plugin are available and accessible via the editor. Probably the easiest option is just copying and pasting `spreadsheet` folder (from addons) into `plugins/spreadsheet` path (like for the other plugins). I checked manual installation from addons and it also works for me.

Since the issue is not overall about CKEditor 4 or Spreadsheet plugin bug but support question about editor configuration, I'm closing this ticket.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
