### ISSUE TITLE
Placeholder wigit inverts text for RTL languages

### ISSUE THREAD

**Issue by allen138** [ckeditor/ckeditor4#4131]
## 📝 Provide detailed reproduction steps (if any)

1. Compose text with placeholders in MS Word using a RTL language such as Hebrew
2. Copy/Paste the text into a CKEditor with the placeholder plugin enabled
3. Notice the placeholders are displayed in the opposite direction. 
4. CodePen: https://codepen.io/allen138/pen/xxZPqvP?editors=1010
### ✔️ Expected result
1. The text show follow the same direction as it was composed in MS Word

### ❌ Actual result
1. The placeholders are rendered in the opposite direction as they were composed in word. For example, [[First Name]] [[Middle Name]] [[Last Name]] will be rendered [[Last Name]] [[Middle Name]] [[First Name]]

## 📃 Other details

* Browser: All, but tested on Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4.12.1
* Installed CKEditor plugins: placeholder

Code pen snapshot:
![ckeditor rtl placeholder bug](https://user-images.githubusercontent.com/38701667/86192553-b89d5680-bafe-11ea-8e25-aab70928cd04.PNG)

**Comment by Comandeer** [comment]
This behaviour is connected with native browser implementation of RTL rendering: https://codepen.io/Comandeer/pen/LYGQmyp

If you consider it a bug, you should probably [report a bug directly to the browser vendor](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by allen138** [comment]
Thanks for your response, but I don't believe its a browser issue. The code pen created is missing a critical step. You cannot type direct html in the code pen to reproduce the issue as this issue specifically when copy/paste from word, using placeholders, and using an RTL language. Here is a sample word document you can test with. 
[sample Hebrew RTL.docx](https://github.com/ckeditor/ckeditor4/files/4880054/sample.Hebrew.RTL.docx)

Here is a screenshot from the sample document on word:
![ckeditorBugReport](https://user-images.githubusercontent.com/38701667/86615355-30d5a300-bf69-11ea-9b1f-6e90e721f5e0.png)

Here is a screenshot when I paste the text from word to the ckeditor:
![ckeditor bug report 1](https://user-images.githubusercontent.com/38701667/86616143-46979800-bf6a-11ea-86f4-bade5e0782d9.png)

**Comment by Comandeer** [comment]
Text inside `[[` and `]]` is transformed into inline widgets and this type of widgets has `display: inline-block` applied to them. Element with `inline-block` is treated by a browser as a single chunk of text, so their order is reversed in RTL mode.

Pasting text into native `[contenteditable]` does not trigger this behaviour, because native editable does not transform parts of text to `span`s with `display: inline-block`. That's why I created demo showing the final result – how the text behaves after transforms done by CKEditor 4. I'm sorry for not describing it further earlier.
