### ISSUE TITLE
Able to add default inline css style attribute on img/figure/figcaption tags created by Enhanced Image Plugin (ckeditor 4)

### ISSUE THREAD

**Issue by justlester** [ckeditor/ckeditor4#4132]
Hi! I just want to ask if it is possible to add default inline CSS style attribute on img, figure and figcaption tags created by Enhance Image Plugin. I needed to set these styles for proper display as HTML email.  I look around the documentation of Enhanced Image Plugin and there are no configurations that able to insert inline CSS styles. 

I wanted to have like this:

**For image with caption**

```
<figure style="margin:10px">
<img src="..." />
<figcaption style="text-align:center">...</figcaption>
</figure>
```

**For image without caption**
`
<img src="..." style="margin:10px"/> 
`

A little help would be appreciated. Thanks!

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
