### ISSUE TITLE
[BUG] Integration with GrapesJS

### ISSUE THREAD

**Issue by cartifon** [ckeditor/ckeditor4#4156]
Hey guys! 

I'm trying to add the CKEditor to my Angular 9 project where I'm using GrapesJS framework, there is the option to add a different Rich Text Editor, and because the CKEditor is the best, I want to use it.

I tried to follow this steps on GrapesJS to overwrite the Rich Text [Replace Rich Text](https://grapesjs.com/docs/guides/Replace-Rich-Text-Editor.html). But when I tried to use I got a weird issue.

![image](https://user-images.githubusercontent.com/7103578/87191645-d5861680-c2c2-11ea-93df-1bedd3d8100d.png)

I'm using the `"ckeditor4": "^4.14.1",` and it is trying to download some assets from my local, shouldn't that be on the node_modules folder? Am I doing anything wrong here? 

Thanks in advance guys!

**Comment by jacekbogdanski** [comment]
Thanks, @cartifon for kind words!

It's hard to help you with the issue because we are not maintaining GrapesJS framework, so it's probably best to contact GrapesJS author or just ask a question on [StackOverflow with grapejs tag](https://stackoverflow.com/questions/tagged/grapesjs).

From the error stack you've added, it seems like CKEditor is unable to find it's assets, so there has to be something wrong with the assets path. You should make sure that the editor files are available on the path from error messages.

> I'm using the "ckeditor4": "^4.14.1", and it is trying to download some assets from my local, shouldn't that be on the node_modules folder? Am I doing anything wrong here?

Yes, in the case of node modules, the main editor file which should be attached on a page is located at `node_modules/ckeditor4/ckeditor.js` - the rest files should be automatically resolved based on the given location via `script` tag. E.g.

```html
<script src="./node_modules/ckeditor4/ckeditor.js"></script>
```

You could check out [Installing CKEditor with Package Managers](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_package_managers.html) guide also.
