### ISSUE TITLE
Cannot read property 'icons' of null

### ISSUE THREAD

**Issue by ostrolucky** [ckeditor/ckeditor4#4163]
We get Sentry errors reported, pointing to an issue in CKEditor. Error is:

> Cannot read property 'icons' of null 

https://sentry.io/share/issue/b0bbbcda9252487680bc1ffb3386d0ff/

It's a minified code, but looking at CKEditor source, I think it points to this https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/core/plugins.js#L39

## Other details

* Browser: Chrome 84.0.4147
* OS: Windows 10
* CKEditor version: 4.14.1
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
It seems like the editor is incorrectly configured and missing some icon assets. Please, make sure that you correctly configured the editor according to [Quick Start Guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html).

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
