### ISSUE TITLE
HTML problem with CKEditor

### ISSUE THREAD

**Issue by Lunyyx** [ckeditor/ckeditor4#4182]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Fill in the CKEditor 4 textarea
2. Send the form with MySQL on a Database

### Expected result

<strong>Test</strong>

### Actual result

&amp;lt;p&amp;gt;&amp;lt;strong&amp;gt;Test&amp;lt;/strong&amp;gt;&amp;lt;/p&amp;gt;

## Other details

* Browser: Chrome (Updated)
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins: Complete Edition

**Comment by jacekbogdanski** [comment]
@Lunyyx I suppose that you are using [Save](https://ckeditor.com/cke4/addon/save) plugin for submitting a form? I've checked payload from the editor and it doesn't seem to be anyhow encoded. Editor is sending raw data but encoding may be performed on the server-side. Please, make sure to correctly configure your backend server and report an issue if you find out that the issue is indeed caused by the editor itself, not 3rd party software.

**Comment by Lunyyx** [comment]
The problem was I added htmlspecialchars to send the content,
The solution was to add htmlspecialchars_decode(); when the echo of the content.
More infos here :
https://www.php.net/manual/fr/function.htmlspecialchars.php
https://www.php.net/manual/fr/function.htmlspecialchars-decode.php

Thank you ! Without you I wouldn't have thought this would have been the trouble ! :)
