### ISSUE TITLE
Make an option so remove formatting doesn't get rid of track changes

### ISSUE THREAD

**Issue by esglickman** [ckeditor/ckeditor4#4184]
## Type of report

Feature request

## Provide description of the new feature
Create an option that will omit certain formatting from being removed when clicking the remove format button

*What is the expected behavior of the proposed feature?*
Expected behavior is that you can add a style that will not be removed when clicking the remove format button

**Comment by Dumluregn** [comment]
Hello, CKEditor 4 does not have a track changes feature. Perhaps you meant [CKEditor 5](https://github.com/ckeditor/ckeditor5)?

**Comment by esglickman** [comment]
@Dumluregn I am using this on CKEditor 4.8

**Comment by f1ames** [comment]
@esglickman you are probably using 3rd-party plugin like [LoopIndex Track Changes](https://ckeditor.com/cke4/addon/lite)?

If so this plugin is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
