### ISSUE TITLE
its possible to parsing rtf value in ckeditor?

### ISSUE THREAD

**Issue by vahidsamimi** [ckeditor/ckeditor4#4187]
Hi guys, 

I want to parse rtf value in ckeditor using JQuery. it's possible in ckeditor version 4?
as example I have this string variable

var str = "{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}}
{\*\generator Riched20 10.0.17763}\paperw11906\paperh16838\margl1134\margr1134\margt1134\margb1134\viewkind4\uc1 
\pard\f0\fs20 test\par
}"

CKEDITOR.instances['editor1'].insertText(str) // not working correctly

**Comment by Comandeer** [comment]
No, CKEditor 4 does not have an RTF parser. It uses HTML for both input and output formats.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
