### ISSUE TITLE
SVG split into multiple copies by <text/> when using alignment

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor4#4197]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

CodePen: https://codepen.io/Woody-lxf/pen/eYZpZPB

1. Insert SVG element, contains one or more text element(s).
2. Select the SVG, and set alignment.

### Expected result

The SVG aligns as a whole.

### Actual result

The SVG has been splitted into several by text element.

The splitted items are aligned.

**Comment by jacekbogdanski** [comment]
I'm not sure if this issue should be treated as a bug. Indeed, it doesn't work correctly as you are able to align some parts of SVG element. However, we are not supporting SVG by default, so the feature wasn't implemented in the first place.

@woody-li this issue should be reported as a feature request for support SVG text nodes. You could also just create your own widget with `svg` content - in that case, please refer to [Widgets SDK](https://ckeditor.com/docs/ckeditor4/latest/guide/widget_sdk_intro.html). Since using SVG text nodes in the editor is rare, I can recommend writing your own widget plugin as we are prioritizing features we work on based on community requests and I'm not sure if such feature would be highly upvoted.
