### ISSUE TITLE
Title content is coming in the editor while loading full html string

### ISSUE THREAD

**Issue by geethu-pa** [ckeditor/ckeditor4#4200]
## Type of report

Docs

## Provide a description of requested docs changes
I am using angularjs framework. and ckeditor version of 4.4.7. In my project i am creating a textarea and then replacing it with ckeditor by using textarea id. and assigning value through ng-bind-html with secure filter $sce.trustAsHtml. Some time my html string will contains full html with title, header. In the title will contains file name. Such html string while passing to ckeditor along with body title also visible in the ckeditor edited area. Means starting first paragraph contains file name and then actual body content. Please help me to solve this issue.
*What is the purpose and what should be changed?*

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
