### ISSUE TITLE
content disappears when order of ck-editor is changed in dropped container.

### ISSUE THREAD

**Issue by sanjayshahu** [ckeditor/ckeditor4#4202]
## Type of report

Bug

I have used ng drag and drop module where I am dragging ck editor to droppable container. Also i have used cdk-drag and drop from angular material which helps to sort ck-editors basically change order of multiple ck-editors. But when position of ck-editor is changed content inside it is removed.

![image](https://user-images.githubusercontent.com/26065226/90106183-ae5cb200-dd64-11ea-992f-1540c8ad1f92.png)
![image](https://user-images.githubusercontent.com/26065226/90106384-f4197a80-dd64-11ea-9a71-b7e7e6dfbc8d.png)

### Expected result
content should be visible even if posiiton of text-editor is changed.

### Actual result
![image](https://user-images.githubusercontent.com/26065226/90106774-83bf2900-dd65-11ea-8717-454168fdf08f.png)

![image](https://user-images.githubusercontent.com/26065226/90106684-68ecb480-dd65-11ea-8023-18d95162f98a.png)

## Other details

* Browser: …84.0.4147.105 (Official Build) (64-bit)
* OS: …windows 10 enterprise
* CKEditor version: …"ckeditor4-angular": "^1.2.2",
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Hello @sanjayshahu,

this repository serves for CKEditor 4 issues. Since your issue is related to Angular integration, please report it in [CKEditor 4 Angular Integration](https://github.com/ckeditor/ckeditor4-angular) repository. Also, note that we will need some demo to reproduce the issue steps without 3rd party software (of course except Angular), because we are not able to fix software we don't own.

**Comment by chiragbytes** [comment]
Hello @sanjayshahu 

Have you found any solution where data of ckeditor disappears on drag and drop, we have used the same material cdkDrag library for drag and drop feature with ckeditor in it.

Have you found any solution for this as I am stuck with same scenario?
Thank you
