### ISSUE TITLE
Ckeditor 4.6.2 - crashes editor

### ISSUE THREAD

**Issue by SilverSilencer** [ckeditor/ckeditor4#4203]
I tried to install this plugin on my Ckeditor 4.6.2, but the editor doesn't even show after I use it. Without plugin it works normally.

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
