### ISSUE TITLE
Paste is gone after post update

### ISSUE THREAD

**Issue by ajayambaliya** [ckeditor/ckeditor4#4221]
BUG MAYBE
![Screenshot (79)](https://user-images.githubusercontent.com/70052976/90951399-49960b80-e478-11ea-93de-91bf3d2700b9.png)
![Screenshot (80)](https://user-images.githubusercontent.com/70052976/90951406-5581cd80-e478-11ea-89e6-0ccdb16a7b98.png)ste

1. … if i paste in ckeditor 4.5.1 its showing paste there. but when i update post only 2 or 3 word or some time 30 words appear. i try all method and all browser but same happen everywhere so can you please provide me solution. i m new here.

**Comment by Comandeer** [comment]
It seems to be not connected with the CKEditor itself, but with the backend that is responsible for saving the post content.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
