### ISSUE TITLE
image width and height attribute

### ISSUE THREAD

**Issue by deepaksp** [ckeditor/ckeditor4#4222]
Hi,
ckeditor set width and height in css but AMP requires image html height and width attribute.
i was wondering is there any way to do this ?

currently it does
`<img src="" style="width='';height=''"/>`

want to do something like this

`<img src="" style="width='';height=''" width="" height=""/>`

**Comment by Comandeer** [comment]
To force using attributes instead of styles, you can use [`disallowedContent` config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-disallowedContent) with `'img{width}'` value.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
