### ISSUE TITLE
bbcode plugin how to add custom bbcode

### ISSUE THREAD

**Issue by xillibit** [ckeditor/ckeditor4#4235]
## Type of report

I'am looking for a way to add custom bbcode code in the plugin bbcode 

Is-there a way to do that ?

## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser: …
* OS: …
* CKEditor version: 4
* Installed CKEditor plugins: bbcode

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by xillibit** [comment]
Already asked on Stack Overflow : https://stackoverflow.com/questions/63534821/ckeditor4-custom-bbcode-in-bbocde-plugins but no answer untill now
