### ISSUE TITLE
CK Editor doesn't allow entering more content at the bottom

### ISSUE THREAD

**Issue by asrarmohammed01** [ckeditor/ckeditor4#4236]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Noticed that if tried to put more content at the bottom of any document which already has content, after save & publish, the new content is moved to another place of the content area.

### Expected result

*The newly added content at the bottom should always stay at the bottom*

### Actual result

*the new content is moved to another place of the content area.*

## Other details

* Browser: …
* OS: Windows
* CKEditor version: 4
* Installed CKEditor plugins:

**Comment by Comandeer** [comment]
It seems that the issue is connected with the application in which CKEditor 4 is used. The application you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the application’s author who should be able to review the problem and suggest a solution.
