### ISSUE TITLE
Can't add @wiris/mathtype-ckeditor4 as an external plugin.

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4#4238]
## Type of report
I'm trying to add wiris as an extra plugin following https://www.npmjs.com/package/@wiris/mathtype-ckeditor4#install-instructions to get the latest fix (https://github.com/ckeditor/ckeditor4/issues/3817).

```
export const addWirisPlugin = CKEDITOR => {
  CKEDITOR.plugins.addExternal('ckeditor_wiris', '../../../node_modules/@wiris/mathtype-ckeditor4/', 'plugin.js')
}
```
`Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "ckeditor_wiris" was not found at "https://cdn.ckeditor.com/4.14.0/full-all/../../../node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K24B".
`
I'm getting this error, I think the path is concatenated with `https://cdn.ckeditor.com/4.14.0/full-all` and caused the error.
How can I add locally installed wiris plugin as external plugin?

<img width="1565" alt="Screen Shot 2020-08-31 at 7 48 17 PM" src="https://user-images.githubusercontent.com/51118408/91745003-fd0ea680-ebc2-11ea-80c6-1a07791d5009.png">

### Expected result
CKEditor with wiris mathtype plugin should be displayed.
*What is the expected result of the above steps?*

### Actual result
`Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "ckeditor_wiris" was not found at "https://cdn.ckeditor.com/4.14.0/full-all/../../../node_modules/@wiris/mathtype-ckeditor4/plugin.js?t=K24B".
`
*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: OSX
* CKEditor version: 4.14
* Installed CKEditor plugins: @wiris/mathtype-ckeditor4

**Comment by Dumluregn** [comment]
Hello, installing the `ckeditor4` npm package instead of using the CDN version should solve the problem as the path to the external plugin is relative to the CKEditor engine file (`ckeditor.js`). Then use it like this:
```html
<body>
	<div id="editor">Hello!</div>
	<script src="./node_modules/ckeditor4/ckeditor.js"></script>
	<script>
		CKEDITOR.plugins.addExternal( 'ckeditor_wiris', '../../node_modules/@wiris/mathtype-ckeditor4/plugin.js' );

		CKEDITOR.replace( 'editor', {
			extraPlugins: 'ckeditor_wiris'
		} );
	</script>
</body>
```

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. If you have CKEditor license, please contact our support team.

**Comment by henok-tesfaye** [comment]
Hi thank you, I'm using CKEditor 4 in my react app using https://www.npmjs.com/package/ckeditor4-react, I think that is what adding the CDN path. How can I get a fix for that? Thanks!
