### ISSUE TITLE
Replace link in the ck editor4

### ISSUE THREAD

**Issue by xthboy** [ckeditor/ckeditor4#4260]
## Type of report
I want to use the ckeditor in a use case that I have some initial text, but I wanna replace the link inside the text. 
for example,
```


<textarea name="email1" id="email1" rows="50" cols="150" disabled>
		<a href="https://www.w3schools.com/">Visit </a>
        </textarea> 
<script>
 CKEDITOR.replace('email1');
var links = document.getElementsByTagName('a');
for(var i = 0; i< links.length; i++){
  console.log(links[i].href);
  links[i].setAttribute("href", "javascript:void(0)");
}
</script>
```
If the link is outside the ck editor, then the link is replaced. 

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*
I wonder how I could replace the link or how to select the link inside the ck editor

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
