### ISSUE TITLE
Change wording on anchors-not-found text

### ISSUE THREAD

**Issue by CharlesBelov** [ckeditor/ckeditor4#4274]
Per https://dev.ckeditor.com/ticket/14374, it is expected that if there are two or more instances of CKEditor on a page, anchors in the one instance will be invisible to the other instance unless using the in-line editor. However, if one is not using the in-line editor, the not-found wording is misleading; it indicates the anchor is not present on the page, whereas it is actually not present in the content of the instance.

## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Edit a page that has two or more instances of the CKEditor on it
2. Create an anchor in one of the instances
3. Save the page
4. Re-edit the page
5. In the other instance, select some text.
6. Click the link icon.
7. In the drop-down, choose Link Type: Link to anchor in the text

### Expected result

Error message: (No anchors available in this field)

Note: I am using the word "field" as opposed to "instance" as an end-user is unlikely to understand the term "instance."

### Actual result

Error message: (No anchors available in the document)

## Other details

* Browser: Safari Version 13.1.2 (15609.3.5.1.3)
* OS: macOS 10.15.6
* CKEditor version: 4.11
* Installed CKEditor plugins: 

a11yhelp
about
clipboard
colordialog
copyformatting
dialog
div
find
flash
forms
iframe
image
link
liststyle
magicline
pagebreak
pastefromgdocs
pastefromword
pastetools
preview
scayt
showblocks
smiley
specialchar
table
tableselection
tabletools
templates
widget
wsc

**Comment by Comandeer** [comment]
The "document" refers to the content edited inside the editor. In both classic and Div Editing Area editors the content forms an isolated, self-containing document. In fact, in the classic one it's also technically a different document, due to being based on `iframe` element.

**Comment by CharlesBelov** [comment]
Requesting that this be reopened. The terminology "document" is the technical view. It is not suitable for being shown to a non-technical end-user. A non-technical end user would consider the outer web page to be the "document," not the CKEditor instance.

**Comment by f1ames** [comment]
Hi @CharlesBelov, as far as I understand your issue is that error message is misleading and should be reworded to be easier to understand for end users?

**Comment by CharlesBelov** [comment]
That is correct. All language that appears to end users would best be expressed in the least technical language feasible and not require understanding of CKEditor internals. Terming CKEditor documents as "documents" in the UI runs counter to that, since that is not how the end-user experiences it.

**Comment by f1ames** [comment]
Thanks for clarification @CharlesBelov :+1: 

> All language that appears to end users would best be expressed in the least technical language feasible and not require understanding of CKEditor internals. Terming CKEditor documents as "documents" in the UI runs counter to that, since that is not how the end-user experiences it.

I agree that it should be non-technical, common language. And it is in most cases. As for "document" I would say it depends on the use case, since one may have inline CKEditor 4 over the entire page content (or most of it) which means editor document is the same as user perceived document. Or the UI may indicate that what user is editing is a document (or article, post, etc). So it depends on the use case and how the entire integration works and on external UI wording too.

I agree that for use cases where CKEditor is used more like form input fields the wording may be misleading indeed.

@CharlesBelov as for translations itself, we're using \[Transifex\](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings, so feel free to add your suggestion there.

**Comment by CharlesBelov** [comment]
Thank you. I probably don't want to file that other issue until this one is resolved. So how does this issue get re-opened?

**Comment by f1ames** [comment]
> @CharlesBelov as for translations itself, we're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings, so feel free to add your suggestion there.

As mentioned in https://github.com/ckeditor/ckeditor4/issues/4274#issuecomment-695966287, you may add your suggestions to Transifex where they will be then checked and reviewed. As this is separate process we prefer to keep issues related to translation closed. However, if it turns out that for some reason your translations got rejected, please get back to this issue.
