### ISSUE TITLE
core/scriptloader.js During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

### ISSUE THREAD

**Issue by aldoom** [ckeditor/ckeditor4#4282]
## Type of report

During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

## Provide detailed reproduction steps (if any)

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L61

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L155-L157

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L101-L105

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L79-L86

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L52-L164

1. In the beginning of the scripts array processing
scriptCount = 2;
i = 0;
2. After checking the first file
scriptsCount = 1;
i = 1;
3. Next element of the array isn't checked and isn't executed "doCallback( success );"

### Expected result

*What is the expected result of the above steps?*

All the script array elements must be checked and "doCallback( success );" must be executed.

### Actual result

*What is the actual result of the above steps?*

During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

## Other details

* Browser: all
* OS: all
* CKEditor version: all
* Installed CKEditor plugins: default

**Comment by f1ames** [comment]
Thanks for reporting @aldoom, very interesting finding :thinking:

How did you notice this issue? Are you using `scriptLoader` somewhere in your code?

---

Btw. I wonder if it's not related to our PFW tests failing from time to time because of some filter files not loaded correctly... These tests use `scriptLoader` from what I see:

https://github.com/ckeditor/ckeditor4/blob/aa1e0e7205cab2f4b6f917db1beaf0d438329114/tests/plugins/pastetools/_helpers/ptTools.js#L34-L57

**Comment by f1ames** [comment]
Fixed in #4283.
