### ISSUE TITLE
WordCount plugin working but count isn't being displayed

### ISSUE THREAD

**Issue by Kitwradr** [ckeditor/ckeditor4#4318]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Config being used:
```
config = {
            language: 'en',
            toolbar: [
                { name: 'styles', items: ['Format'] },
                { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'] },
                { name: 'paragraph', items: ['NumberedList', 'BulletedList'] },
                { name: 'align', items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
                { name: 'link', items: ['Link'] },
                { name: 'insert', items: [] },
            ],
            customConfig: '',
            extraAllowedContent: 'img[width,height,align];span[*]{*}(*);span{background}',
            extraPlugins: 'justify,pastefromword,liststyle,autolink,notification,wordcount',
            bodyClass: 'document-editor',
            pasteFilter: null,
            disallowedContent: 'table[border]{*}; tr td',                           //Remove formatting of tables when pasted from elsewhere
            removePlugins: 'table,tabletools,horizontalrule,tableselection',
            removeButtons: 'Subscript,Superscript,Styles',
            wordcount : {
                showWordCount: true,
                showCharCount: true,
                maxCharCount : 30,
                countHTML: false,
            },
        };
```

### Expected result

The count of the characters should be shown in the bottom right corner. Although the plugin works since I am not able to enter more the the cap specified in the config. The count display isn't showing up.

I have added the plugin using the following lines

```
    CKEDITOR.plugins.addExternal('wordcount', '/assets/ckeditor/plugins/wordcount/', 'plugin.js');
    CKEDITOR.plugins.addExternal('notification', '/assets/ckeditor/plugins/notification/', 'plugin.js');
```

### Actual result

*What is the actual result of the above steps?*

Although the plugin works since I am not able to enter more the the cap specified in the config. The count display isn't showing up.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: worcount,notification, rest of preset plugins

**Comment by f1ames** [comment]
Hi @Kitwradr, the wordcount plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution ([issue tracker](https://github.com/w8tcha/CKEditor-WordCount-Plugin/issues)).  
  
If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
