### ISSUE TITLE
Cannot read property 'contains' of null     at CKEDITOR.style.checkApplicable

### ISSUE THREAD

**Issue by XiaoDan12202** [ckeditor/ckeditor4#4330]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
I tried to add an attribute to <img>,but it didn't work and reported an error in console.
The section is 
```
<p><img alt="" src="http://localhost:8080/mtex/file/download/get?getFromNop=1&amp;suf=upload%2FWorkFlowMng%2F41%2F9932%2F26%2F%E4%B8%8B%E8%BD%BD.png&amp;token=2A3E52A2F58AF9F181F3786506B5F48A" style="height:187px; width:119px" /></p>
```

const style = new CKEDITOR.style( { element: 'img', attributes: { 'pic-type': 'zoom-pic' } } );
this.editor.applyStyle(style);

### Expected result
add an attribute to imgs like the following.
```
<p><img alt="" src="http://localhost:8080/mtex/file/download/get?getFromNop=1&amp;suf=upload%2FWorkFlowMng%2F41%2F9932%2F26%2F%E4%B8%8B%E8%BD%BD.png&amp;token=2A3E52A2F58AF9F181F3786506B5F48A" style="height:187px; width:119px" pic-type="zoom-pic" /></p>
```

### Actual result

it reports an error: 'Cannot read property 'contains' of null     at CKEDITOR.style.checkApplicable'.

## Other details

* Browser: …
* OS: …
* CKEditor version:4.15
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
According to the documentation, [`editor.applyStyle`]() applies a specific style to the current editor selection. The error you see is probably caused because you didn't select anything in the editor content. Please, see https://codepen.io/jacekbogdanski/pen/pobEJrM codepen.

I don't know your specific use case, but if you just want to apply a specific attribute to the images on some precondition, you could take a look at [transformations](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter.html#method-addTransformations) API.

Please, tell if that resolves your issue.

**Comment by XiaoDan12202** [comment]
I  selected an img and it wouldn't report an error but the attribute was not added to it.And I tried to add transformations and it works.Thanks a lot
