### ISSUE TITLE
ckeditor not working properly with setData followed by getData function for wiris mathjx plugin

### ISSUE THREAD

**Issue by pawan-khade** [ckeditor/ckeditor4#4342]
I have integrated ckeditor with wiris plugin. When used setData() method to set value of editor from database data/equations is shown properly but when I call getData() method to get value of ckeditor it is giving following error

Uncaught TypeError: e is null
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:1
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:1
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:1
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:1
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:1
    value http://localhost:8000/js/helpers/ckeditor/plugins/ckeditor_wiris/plugin.js?t=K87C:3
    l http://localhost:8000/js/helpers/ckeditor/ckeditor.js:10
    fire http://localhost:8000/js/helpers/ckeditor/ckeditor.js:12
    fire http://localhost:8000/js/helpers/ckeditor/ckeditor.js:13
    getData http://localhost:8000/js/helpers/ckeditor/ckeditor.js:293
![image](https://user-images.githubusercontent.com/16404292/97081372-ad2ae980-161f-11eb-9a6d-dbc7261c408f.png)

Please solve my problem

**Comment by Comandeer** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please [redirect your question to the plugin’s author](https://github.com/wiris/html-integrations) who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
