### ISSUE TITLE
some features of ckEditor4 are not visible

### ISSUE THREAD

**Issue by monika1111** [ckeditor/ckeditor4#4350]
I have set toolbar like this 
![image](https://user-images.githubusercontent.com/16905883/97879670-b14eb980-1d39-11eb-8c0c-f04198f253be.png)
but I cant see any features, e.g. Font Size..

![image](https://user-images.githubusercontent.com/16905883/97879827-dba07700-1d39-11eb-8e14-0674f6daded7.png)

Can you please tell me the reason? Is it possible that I should install `ckeditor4-react-advanced` instead of `ckeditor4-react`?

Thanks

**Comment by Dumluregn** [comment]
Hello,
that's because by default `ckeditor4-react` integration uses [the standard preset](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html). If you need more features, you need to customise the used CKEditor 4 version - please refer to [this guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version) from our documentation.

**Comment by monika1111** [comment]
thanks
