### ISSUE TITLE
The notification is hidden by the dialog box when called from dialog

### ISSUE THREAD

**Issue by xillibit** [ckeditor/ckeditor4#4391]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

In CKeditor4, I have tried to show a notification when the dialog is opened at first time but the notification is displayed behind the dialog box. Is-there a way to show the notification at foreground ?

This is my code in the dialog part :

` CKEDITOR.dialog.add('MypluginDialog', function( editor ) {
    return {
        title: 'my plugin title,
        minWidth: 400,
        minHeight: 200,
        contents: 
        [
            {
                id: 'tab-basic',
                label: 'Dialog settings',
                elements: 
                [
                    {
                        type: 'text',
                        id: 'title',
                        label: 'My title',
                        default: ''
                    }                   
                ]
            }
        ],
        onOk: function() {
        },
        onShow: function() {
             var notification1 = new CKEDITOR.plugins.notification( editor, {
                message: 'Error occurred',
                type: 'warning'
             } );
             notification1.show();      
        }
    };
}); `

### Expected result

The notification shouldn't be hidden by the dialog

### Actual result

The notification is hidden by the dialog

## Other details

* Browser: Firefox 82.03
* OS: Windows 10 20H2
* CKEditor version: 4.15.1
* Installed CKEditor plugins: bbcode

**Comment by f1ames** [comment]
Hi @xillibit,

You may try to adjust notification element `z-index` via CSS to show up in front of dialog and it's overlay.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by xillibit** [comment]
I had already asked it on stackoverflow : https://stackoverflow.com/questions/64850031/ckeditor-notification-called-from-dialog-isnt-displayed-at-foreground but with nos answer until now

**Comment by f1ames** [comment]
@xillibit please see - https://stackoverflow.com/a/64985308/646871.
