### ISSUE TITLE
Check how docs build and works with updated highlight.js depndency

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4396]
## Type of report

Docs

## Provide a description of requested docs changes

Since Highlight.js dependency in Umberto was recently updated - from version 9 to 10 (see [changelog and breaking changes](https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md)), it will be good to check if nothing breaks and code samples looks the same as before (see Umberto `i/887` branch).

There were some changes in CKEditor 5 related to `plaintext` code type (see https://github.com/ckeditor/ckeditor5/pull/8506) so we might need to do the same.

**Comment by sculpt0r** [comment]
I manually modify highlight dependency in `ckeditor4-docs/node_modules/uberto/themes/umberto/source/assets/_scripts/highlight.pack.js`

Cleared `ckeditor4-docs/build/docs/assets/1.6.2/scripts` - `1.6.2` is my current `umberto` version.
Built docs with `grunt build-serve --dev`

After build, in browser console - verified that updated highlight was loaded - and it was.

According to CKE5 changes (' ```plaintext ' markers changed into ' ```nohighlight` ') - I found a few in `ckeditor4-docs` but after build they look the same as in online docs :thinking: 

I verify if my steps were correct and re-check docs.

**Comment by sculpt0r** [comment]
For sure, as they mention https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md - IE11 highlights are broken. Checked on BrowserStack.

**Comment by sculpt0r** [comment]
Also, I switch to the proper branch at `umberto` (with changes for hljs v.10) and then rebuild docs - but still - plaintext highlights remain the same.

If I good understand this conversation: https://github.com/highlightjs/highlight.js/issues/2363, which has more meaning to me than `changelog`:
- breaking changes mean something only if we would like to skip highlight. Since we do not skip it but highlight code block as no specific language - everything should work just fine?

But if we use \```nohighlight as CKE5 - then our code block stops highlighting at all. So we shouldn't do this.

**Comment by sculpt0r** [comment]
**Summary:**
> There were some changes in CKEditor 5 related to plaintext code type (see ckeditor/ckeditor5#8506) so we might need to do the same.

According to @pomek : CKE5 docs changes are on purpose to block default styling. They have their own.


>Since Highlight.js dependency in Umberto was recently updated - from version 9 to 10 (see changelog and breaking changes), it will be good to check if nothing breaks and code samples look the same as before (see Umberto i/887 branch).

The changelog is a little bit confusing about `plain` and `text` but:
- they are mention separately, not as `plaintext` since it's another 'language' marker for `highlight` library

- According to [README](https://github.com/highlightjs/highlight.js#plaintext-and-disabling-highlighting) and [usage](https://highlightjs.org/download/) page - `plaintext` is still valid. It have other purpose than `nohighlight`.
![image](https://user-images.githubusercontent.com/6498567/100592724-c8aca280-32f7-11eb-8e5e-14a8446719e8.png)


- According to [highlight library issue](https://github.com/highlightjs/highlight.js/issues/2363) - `plain` is no longer relevant, and `text` simple become alias for `plaintext`. The entire conversation seems to be more descriptive than changelog single sentence.

So `plaintext` marker in `umberto`  `highlight.worker.js` remains valid.
Codeblocks with '```plaintext' remains properly highlighted as no code blocks, but only with text.

Talked about this with @f1ames and seems that we don't have to make any changes in docs for CKE4 connected with `highlight` library upgradations.

Closed.

**Comment by f1ames** [comment]
One thing to mention is that Highlight.js v10 doesn't support IE11. I have checked how it works with v9 and v10 - my assumption would be that with v9 code coloroing works fine while with v10 it will be broken - however it seems to be working the same for both versions (probably there are already some issues in v9 in IE11):

![](https://user-images.githubusercontent.com/1061942/100604351-b84ff400-3306-11eb-811e-0335956eac66.png)

The only regression is that code samples doesn't "unfold" with v10:

![Peek 2020-11-30 12-24](https://user-images.githubusercontent.com/1061942/100604704-32807880-3307-11eb-96eb-3c5ba6fa9a20.gif)

But I think we can live with that since documentation is readable in IE11 and we don't aim to have perfect support for documentation there.
