### ISSUE TITLE
Drag and Drop in Angular Typescript

### ISSUE THREAD

**Issue by harivigneshs** [ckeditor/ckeditor4#4417]
## Type of report

Task

##I need the example code in typescript to drag and drop some element inside the div into ckeditor like the example give in javascript below,

https://ckeditor.com/docs/ckeditor4/latest/examples/draganddrop.html

*What steps should be taken to fulfil the task?*

## 1. Please give me the solution how to call  the dragstart function in ts file and create a event
2. And how to call CKEDITOR methods and functions in Typescript angular

* Browser: …
* OS: …
* CKEditor version: … 4
* Installed CKEditor plugins: … 4 , Angular

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
