### ISSUE TITLE
CKEditor 4.15.1 Unable to set default font to Arial

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#4418]
## Type of report

Bug

config.js:
Added
config.font_defaultLabel = 'Arial';

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result
![image](https://user-images.githubusercontent.com/36516764/101055798-e4aa8100-354f-11eb-8633-f7b23cf34fab.png)

*What is the actual result of the above steps?*

There is no default font
## Other details

* Browser: …
* OS: Windows 10
* CKEditor version: 4.15.1
* Installed CKEditor plugins: https://ckeditor.com/cke4/builder/4e3a4ca28d8cb0c407b480601a63d4b6

**Comment by f1ames** [comment]
@JohnCSMoodys, please keep in mind that Font dropdown value is set while editor is focused - as [API docs describes](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-font_defaultLabel):

> The text to be displayed in the Font combo if none of the available values matches the current cursor position or text selection.

Which means this value is based on editor selection, that's why it works after editor is focused. See below:

![Peek 2020-12-03 18-02](https://user-images.githubusercontent.com/1061942/101062670-38d65500-3592-11eb-8ad3-c6116859959e.gif)

Is this what you had in mind or you meant something different?
