### ISSUE TITLE
Cannot copy the content in word to the ckeditor4

### ISSUE THREAD

**Issue by 8debug** [ckeditor/ckeditor4#4442]
Chrome 87.0.4280.88
Windows10

Cannot copy the content in word to the ckeditor4 in [this url](https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html).

cannot show content and no formatter

[CKEditor4.PFW.Sample.Mixed_styles.docx](https://github.com/ckeditor/ckeditor4/files/5701974/CKEditor4.PFW.Sample.Mixed_styles.docx)

**Comment by f1ames** [comment]
Hi @8debug, could you provide exact reproduction steps and describe what doesn't work for you. Please also share your MS Word version.

I have checked mentioned sample with Chrome `87.0.4280.88` on Windows 10 and it's working fine for me.

**Comment by 8debug** [comment]
Microsoft Office Professional Plus 2016

step1 open this word
step2 ctrl+a
step3 ctrl+c
step4 open the url
step5 ctrl+a in ckeditor
step6 ctrl+v

images cannot show in ckeditor

![image](https://user-images.githubusercontent.com/3394927/102354612-c596ff00-3fe5-11eb-88a3-fa277abc8cd1.png)

**Comment by 8debug** [comment]
cannot show images When the content I pasted contains pictures

**Comment by f1ames** [comment]
Hi @8debug. I rechecked this issue with the steps you've provided but I'm still unable to reproduce it. Tested with Chrome `87.0.4280.88` on Windows 10. The only difference is MS Word which in my case is Office 365 `16.0.13426.20270` - I wonder if this could be the cause here.

@8debug do you see any errors in browser dev console when pasting?
