### ISSUE TITLE
Table cell  has not default width and height

### ISSUE THREAD

**Issue by hanyuhuang1** [ckeditor/ckeditor4#4460]
## Table cell  has not default value of height and width 
When i init my table , `<td>` has not `width` and `height`， like this
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
```
When i use  plugin to drag table, it likes this
```
<table border="1" cellpadding="1" cellspacing="1" style="width:514px">
	<tbody>
		<tr>
			<td style="height:24px; width:249px">&nbsp;</td>
			<td style="height:24px; width:252px">&nbsp;</td>
		</tr>
		<tr>
			<td style="height:23px; width:249px">&nbsp;</td>
			<td style="height:23px; width:252px">&nbsp;</td>
		</tr>
		<tr>
			<td style="height:25px; width:249px">&nbsp;</td>
			<td style="height:25px; width:252px">&nbsp;</td>
		</tr>
	</tbody>
</table>
```

version: 4.15.1
plugin: `Table Cells Selection` `Table Resize` `Table Resizer(Row and Column)`

**Comment by f1ames** [comment]
Hello @hanyuhuang1, this is an expected behavior. Any table cell initially have no dimensions defined so it can nicely stretched to content inside (this is native browser behavior). Since [Table Resize](https://ckeditor.com/docs/ckeditor4/latest/examples/table.html) changes cells and table sizing to fixed dimensions, `width` and `height` needs to be preserved in form of styling so it won't be changed by the browser itself.
