### ISSUE TITLE
Can't update dialog definition content onShow event.

### ISSUE THREAD

**Issue by armang98** [ckeditor/ckeditor4#4464]
## Type of report

Bug

## Provide detailed reproduction steps
Hi everyone, I'm using CKEditor 4 and now I have some problems with dialogDefinition.

CKEDITOR.on( 'dialogDefinition' , function( ev ) {}); 
on this event I can add some content on the Dialog Defintion once.( Screen below)
![image](https://user-images.githubusercontent.com/37144283/103445146-22ebab00-4c8a-11eb-9434-ce6250291b57.png)
Code: 
![image](https://user-images.githubusercontent.com/37144283/103445190-b3c28680-4c8a-11eb-9bc3-8d1f9ed38b9a.png)

But now in my case, I need to add content during onShow event on dialogDefinition every time. But I don't see the added element. (Screen below)
![image](https://user-images.githubusercontent.com/37144283/103445259-3fd4ae00-4c8b-11eb-82fe-698bf7f9fca7.png)

Code: 
![image](https://user-images.githubusercontent.com/37144283/103445267-4ebb6080-4c8b-11eb-80c3-f4583e150483.png)

### Expected result

*Expecting a fix for this bug or the correct way to code *

## Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version: full/4.14.0

**Comment by f1ames** [comment]
Hi @armang98, [`dialogDefinition` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#event-dialogDefinition) is fired only once when dialog is created as mentioned in the docs:

> Note that this event is called only the first time a specific dialog is opened. Successive openings will use the cached dialog, and this event will not get fired.

So it's not possible to change dialog definition every time dialog is shown. You may try with adding all fields once and the showing/hiding them or changing default values on dialog show.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your questions next time on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
