### ISSUE TITLE
Inserting content next to block widgets using keyboard navigation

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4467]
## Type of report

Feature request

## Provide description of the new feature

Currently, if two block widgets are inserted right after each other, there is no possibility to add content between them without either some copy&paste workarounds or [Magic Line plugin](https://ckeditor.com/cke4/addon/magicline). Could be useful if it was possible in some friendly way.

Since the issue only concerns block widgets, expected result would probably be inserting the paragraph after the widget (like with Magic Line, but without mouse interaction). The `enter` keystroke is already reserved for widget edition dialog, so we need another one. A possibility is `shift+enter`, which is currently doing nothing in such scenario (it should be investigated if `enterkey` plugin doesn't alter this behaviour though).

That part would solve the problem with adding content **between** two widgets or **after** the widget if it is placed at the end of the document. There is one more situation to consider which is a widget at the beginning of the document - we would need another keystroke for inserting the paragraph **before** the widget, but that may be an edge case worth further extracting.

For more context, there is https://github.com/ckeditor/ckeditor4/pull/4433 which probably enables removing the existing paragraph from between two widgets, which may cause the situation with two "glued" widgets more often, so it would be good to have it introduced in the same release as this feature.

**Comment by bunglegrind** [comment]
I looked into this issue (since it's related to #4433 that I've opened) and probably found a solution. Quite simple, indeed. 

Basically, I've add another case in the if else chain https://github.com/ckeditor/ckeditor4/blob/87c1c99c5897aa34f425478ed058c627324ef72c/plugins/widget/plugin.js#L3606 

in which when SHIFT+DOWN is pressed (or whatever you prefer) an empty paragraph is added as a sibling next to the widget wrapper I'm in. 

(the empty paragraph is filled with appendBogus).

Manual tests performed in FF, Chrome IE9-11 succeeded. With IE8 I'm experiencing some issues, probably related to the widget selection.

**Comment by quicksketch** [comment]
For final reference, documentation on how this works was added at https://github.com/ckeditor/ckeditor4/issues/4559

Docs: https://ckeditor.com/docs/ckeditor5/latest/features/keyboard-support.html#content-editing

Screenshot
![image](https://user-images.githubusercontent.com/100206/142373357-74a36074-4c48-4095-9c2f-3a1819c88f64.png)

Thanks @bunglegrind for your work on this, it really makes working with images (and other widgets) a lot better experience.
