### ISSUE TITLE
setData() not working on modal form

### ISSUE THREAD

**Issue by RossAWaddell** [ckeditor/ckeditor4#4468]
I have two CKEditor instance on my webpage: the first one is used with other form inputs to add a record to a bootstrap-table; the other is for editing that record in a modal form.

I've tried all different combinations of setData() for the modal (triggered by a button the table row):

**Throws error (with or without callback)**:

```
<script>
// This code is at bottom of <body> section

var editorModal = CKEDITOR.replace( 'editRemarks', {
    customConfig: '/contest/common/js/ckeditor_config_wf.js'
});

editorModal.setData( '<p>Hello World</p>', {
    callback: function() {
        this.checkDirty(); // true
    }
} );
</script>
```

**This doesn't throw an error but doesn't set the data**:

```
editorModal.on( "instanceReady", function( event ){
    editorModal.setData([row.htmlRemarks]);
 });
```
 
In the latter case, once the modal is shown I can set the contents from the console like this:

`editorModal.setData('<p>Hello World</p>');`

Since the table can include up to 10 records, I need to update the modal form inputs dynamically (via an edit button on the table row). What am I doing wrong?

I'm using CKEditor v4.15.1 • 09-11-2020

**Comment by sculpt0r** [comment]
Hi @RossAWaddell,  
> I've tried all different combinations of setData() for the modal (triggered by a button the table row):  

Could you provide some working example with for example:
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3
?

Also, an error message could be useful to find out what could go wrong.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by RossAWaddell** [comment]
I have posted this question to stack overflow before coming here, but so far no response:

[https://stackoverflow.com/questions/65553204/ckeditor-setdata-not-working-with-modal-form](url)

My HTML form is quite complicated so it will take a lot of work to strip it down.

**Comment by RossAWaddell** [comment]
This code:
`CKEDITOR.instances.editRemarks.setData([row.htmlRemarks]);`

produces:

```
plugin.js?t=KA9B:22 Uncaught TypeError: data.replace is not a function
    at dataIsEmpty (plugin.js?t=KA9B:22)
    at a.<anonymous> (plugin.js?t=KA9B:185)
    at a.l (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at a.setData (ckeditor.js:295)
    at e.click .editThisEntry (entryForm_TAB_WIZ_v3.php:694)
    at HTMLAnchorElement.<anonymous> (bootstrap-table.min.js:10)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
```

If I use the callback, there's  no error but but it doesn't update the field the 2nd time the modal is invoked. It looks like I have to destroy the CKEditor instance and recreate it each time.

**Comment by sculpt0r** [comment]
@RossAWaddell 

I'm closing this issue as it's more like a support question.

We are waiting for some more details on [https://stackoverflow.com/questions/65553204/ckeditor-setdata-not-working-with-modal-form.](https://stackoverflow.com/questions/65553204/ckeditor-setdata-not-working-with-modal-form.) There are comments to your question.   
  
I hope after some clarification we will be able to help you on StackOverflow.
