### ISSUE TITLE
Page scrolls down to bottom when I paste something in Ckeditor4

### ISSUE THREAD

**Issue by jj-theInvincible** [ckeditor/ckeditor4#4469]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

While pasting in Editor, the whole page scrolls down to bottom. I was using multiple editors on a single page.

## Other details

* Browser:Chromw
* OS:Windows 10
* CKEditor version:4.*

**Comment by sculpt0r** [comment]
Hi @jj-theInvincible ,  
  
The only way I was able to reproduce the issue according to your description (https://stackblitz.com/edit/js-9q8twn?file=index.html):

1.  Copy some text to the clipboard.
2.  Set focus on the bottom-most editor.
3.  Use scroll wheel over main page scroll to move the scroll bar to the top.
4.  Use `Ctrl + V` to paste the text.

Result: Main page scroll bar moved down to show newly pasted text.  
 

It looks like quite standard behaviour, but I'm not sure if this is your case?

If not, feel free to fork given example on stackblitz to provide some working example.

Could you check the exact CKEditor version? You can type `CKEditor.version` in the development console.

**Comment by jj-theInvincible** [comment]
I've checked the example on stackblitz, that's working fine, also, the editor works fine on any HTML page but there was an issue of scroll to down when I was using it inside a template engine. Maybe that error comes when the HTML isn't formatted correctly.

**Comment by sculpt0r** [comment]
> I was using it inside a template engine.

That is important information. Every detail about the CKEditor's environment is important.  
  
@jj-theInvincible   
Since there is third-party integration involved, and we don't have any working sample that proves CKEditor bug - I close this issue.  
  
If you provide some reproducible environment - we will probably re-open this issue.  
For now, according to the original issue description - there is no problem with CKEditor itself.  
  
Thank you for taking the time to create this issue.
