### ISSUE TITLE
FakeObjects (Protected) in Header

### ISSUE THREAD

**Issue by bhsmither** [ckeditor/ckeditor4#4506]
## Type of report

Bug - Question

## Provide detailed reproduction steps (if any)

CKEditor 4.15.1, added ShowProtected plugin, classic editor replacing a textarea
https://github.com/IGx89/CKEditor-ShowProtected-Plugin
ShowProtected requires 'dialog,fakeobjects'

In Source mode:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Invoices</title>
</head>
<body></body>
</html>
```
Switch to wysiwyg mode.

Note that the `<meta>` tag is affected and ShowProtected shows a code icon.

### Expected result
Expect only a slight variation.
Switching to Source mode:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Invoices</title>
</head>
<body>&nbsp;</body>
</html>
```

### Actual result
Out of order tags.
Switching to Source mode:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
</head>
<body><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></body>
</html>
<title>Invoices</title>
```

The question is:
Because FakeObjects is involved, and it replaces from _something_ to an image, is the function of FakeObjects appropriate for something to be affected in the `<head>` section?

**Comment by Dumluregn** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
