### ISSUE TITLE
CKEDITOR: IFrame tag content is missing while saving to the database

### ISSUE THREAD

**Issue by anandrajms** [ckeditor/ckeditor4#4513]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I have IFrame, Embed and Autoembed plugins already installed. When I use the url to embed into the ckeditor it is displaying nicely. When I see the source everything looks ok.

"<div data-oembed-url="https://twitter.com/Philae2014/status/610047412036595712">
<div style="max-width: 550px;">
<div style="left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;"><iframe allowfullscreen="" src="//cdn.iframe.ly/api/iframe?url=https%3A%2F%2Ftwitter.com%2FPhilae2014%2Fstatus%2F610047412036595712&amp;key=425af07acbdfb73a71a75e1cfd3f60a4&amp;autoplay=1&amp;mute=1&amp;app=1" style="border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;" tabindex="-1"></iframe></div>
</div>
</div>

<p>&nbsp;</p>"

but when I save to database it is skipping the IFrame tag content and saving.

How to fix this to save along with IFrame tag content.

**Comment by sculpt0r** [comment]
Hi, @anandrajms 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on \[Stack Overflow\](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at \[ Stack Overflow\](http://stackoverflow.com/questions/tagged/ckeditor).

Feel free to create another issue with a detailed description (according to our template) if you think that CKEditor contains some bug.
