### ISSUE TITLE
P tag are added to the text entered , how to stop this

### ISSUE THREAD

**Issue by ashrafmansuri7272** [ckeditor/ckeditor4#4524]
When we enter any text to the ckeditor the text is automatically appended with p tags , i want to remove them , i tried some solutions but that seems not working 
	                                                                         CKEDITOR.replace("question_" + qId,{
												toolbar : 'basic',
												enterMode : CKEDITOR.ENTER_BR,
												shiftEnterMode : CKEDITOR.ENTER_P
									         });

it still gives p tag to the text entered
![image](https://user-images.githubusercontent.com/60643228/106983321-b5043900-678b-11eb-92f5-49d122567244.png)

expected behaviour no p tags

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
