### ISSUE TITLE
Editor Resize Plugin - compatibility

### ISSUE THREAD

**Issue by Lugoma** [ckeditor/ckeditor4#4534]
Hi,

I'm submiting this issue just to ask a question. I know this isn't the proper place to do it. I apologize for it but I couldn't find any good place for asking it.  

We currently have this version of ckeditor:

/*
Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/

We would like to install an Editor Resize Plugin version compatible with it.  We couldn't find previous versions of it (currently 2021). Could you tell us any site where we can get it? 

Thanks for your time.

* Browser: not related
* OS: not related
* CKEditor version: 4.11.3
* Installed CKEditor plugins: not related

**Comment by sculpt0r** [comment]
Hi @Lugoma ,

The best place to ask implementation questions is [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

However, this plugin is downloadable on [our plugins page](https://ckeditor.com/cke4/addon/resize). Please note the table with the older version at the bottom. There isn't explicitly listed your version, but links lead you to [`https://download.ckeditor.com/resize/releases/resize_4.14.1.zip`](https://download.ckeditor.com/resize/releases/resize_4.14.1.zip) which can be easily replaced to `https://download.ckeditor.com/resize/releases/resize_4.11.3.zip`

I strongly recommend you to update your editor versions, since we made a lot of fixes (also security fixes!) since `4.11`.

> I'm submiting this issue just to ask a question. I know this isn't the proper place to do it. I apologize for it but I couldn't find any good place for asking it.

I close this issue. I hope my answer helps you somehow. If you have any further questions - please use [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor).
