### ISSUE TITLE
Unable to see bold text and symbols in a table without zooming in

### ISSUE THREAD

**Issue by idabarbour** [ckeditor/ckeditor4#4549]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create the attached table.
2. Bold text and em dashes contained in the table (users are unable to see that the text and symbol are bold).
3, Zoom in within the browser (users can now see that the text and symbol are bold).

### Expected result

See text and symbols displayed in bold without having to zoom in.

### Actual result

Unable to see which text and symbols are displayed in bold at 100% zoom.

## Other details

* Browser: Edge, Chrome
* OS: Windows 10 Enterprise
* CKEditor version: 4.15
* Installed CKEditor plugins: Table, Table Resize, Table Tools
[Table Source Code - Unable to see bold text and symbols.txt](https://github.com/ckeditor/ckeditor4/files/6044073/Table.Source.Code.-.Unable.to.see.bold.text.and.symbols.txt)

https://user-images.githubusercontent.com/78554945/109178847-48aba280-7757-11eb-8cae-537b967e77d4.mp4

**Comment by Dumluregn** [comment]
This is the matter of font and the specific symbol you chose. If instead of `-` you input some other character, like `&`, it is clearly visible if bold is applied or not. You can easily check it for yourself even for `-` symbol:

1. Type `-editor` in the table cell.
2. Select only `-`.
3. Toggle `Bold` button.

You'll see that there is a difference (when there is only `-` in cell, the fake selection kicks in and the effect is more difficult to spot due to flashing when style is approved - but it works just as it should).

I can only suggest using a font with more distinguishable bolded characters instead or increasing the font size used in the editor.
