### ISSUE TITLE
Multiple table columns are automatically adjusted when dragging the border of one column. Is it possible to turn off the auto adjustment setting?

### ISSUE THREAD

**Issue by idabarbour** [ckeditor/ckeditor4#4560]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a table using the attached source (Table Source Code 2.txt)
[Table Source Code 2.txt](https://github.com/ckeditor/ckeditor4/files/6102335/Table.Source.Code.2.txt)
.
2. Drag the right border of the first column to the left.

### Expected result

Only the width of the first column is adjusted.

### Actual result

All column widths are adjusted. See attached video (Auto width adjustments.mp4).

https://user-images.githubusercontent.com/78554945/110342663-a95d9980-7ff9-11eb-88b1-0d1e6cf5911f.mp4

## Other details

* Browser: Edge, Chrome
* OS: Windows 10
* CKEditor version: 4.15
* Installed CKEditor plugins: Table Resize, Table Tools Toolbar

**Comment by sculpt0r** [comment]
Hi @idabarbour ,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
