### ISSUE TITLE
Div inside span

### ISSUE THREAD

**Issue by e1sep0** [ckeditor/ckeditor4#4569]
I have a big problem with CKEditor:
I want to paste this:
```html
<span class="js-contacts-popup-content hidden-block">
	<div class="popup-large-text">
		<p>1</p>
		<p>2</p>
	</div>
</span>
```

But CKEditor convert it:
```html
<div class="popup-large-text">
<p><span class="js-contacts-popup-content hidden-block">1</span></p>

<p><span class="js-contacts-popup-content hidden-block">2</span></p>
</div>
```

I set `allowedContent:true`
Multiple variants with extraAllowedContent, but have no result/

Please help) Thank you

**Comment by sculpt0r** [comment]
Hi @e1sep0 ,
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
