### ISSUE TITLE
outputTemplate inserting plain text

### ISSUE THREAD

**Issue by drtanzil** [ckeditor/ckeditor4#4578]
`outputTemplate : '{body}',`

inserting codes as plain text.
![18-Mar-21 9-16-42 PM](https://user-images.githubusercontent.com/11825577/111653370-1101b900-8832-11eb-8fdc-e95ff1622ab1.png)

however `editor.insertHtml(body)` method works fine.

Does outputTemplate is coded to inseted Plain Text only? Is it a bug? anyway to use is like insertHtml ?

**Comment by Dumluregn** [comment]
You provided very little information, but I'm guessing you ask about [this property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_autocomplete.html#property-outputTemplate). Please notice that you should put the value in backticks (`) instead of quotes (') since this value takes `template` as an argument, not a string.

If that doesn't solve your problem, create a new issue but use [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
