### ISSUE TITLE
Wordcount plugin does not update the char counter on afterPage event

### ISSUE THREAD

**Issue by iliasmertzanos** [ckeditor/ckeditor4#4582]
Hi guys,

great job you have done!

I am having an issue with events in requard with wordcount plugin.

I am trying to catch the `afterPaste` event (ctrl+V) but at that moment the  counter `evt.editor.wordcount.charCount` is empty. 

I tried to set a timeout, so that the read of the worcount value waits a bit and it works.
That means somehow wordcount is updating his content at some point later.

Is there any specific Event from the wordcount plugin ?

**Comment by Dumluregn** [comment]
Hello,
The [Wordcount plugin](https://ckeditor.com/cke4/addon/wordcount) you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
