### ISSUE TITLE
Modifying HTML with third party APIs

### ISSUE THREAD

**Issue by NavnathKumbhar** [ckeditor/ckeditor4#4584]
## Type of report

Task

## Provide description of the task
Hello,
This is not a bug or feature request but I just need your opinion for a approach that I am using for Paste from Word task.

Currently, there are some issues with Paste From Word plugin such as : 
- Excel table borders does not retained
- Equation from Word is not pasted correctly
- Word table formatting is not retained after paste
- Numbering does not persist for the ordered list in Word after paste

Apart from these, there are other issues too.

I am using Aspose Word APIs for some MS Word content processing.
I analyzed that when I use some Aspose APIs to convert RTF data from clipboard [data copied from Word] into HTML, then some of the above issues get fixed.

But, I need your opinion to decide whether this is a good approach or not?
I learned that there is ACF (Advanced Content Filtering) concept in CKEditor. Will it affect to this approach in some way or the other?

What do you think of this approach from future CKEditor development perspective?

Thank you in advance for your feedback.

## Other details

* Browser: Chrome, MS Edge, Mozilla Firefox
* OS: Windows 10
* CKEditor version: 4.16

For your information, I have installed **pastefromword** plugin and its dependencies in my CKEditor.

**Comment by sculpt0r** [comment]
Hi @NavnathKumbhar ,

We definitely won't involve any third-party software / API / whatsoever as much as it's possible. I'm not sure what kind of transformation you are doing with Aspose API. It's a kind of a project development question, but if you can use only two different software, instead of three - there are smaller chances for failure. If you are able to make the same transformations with ACF (as you do with API) and it is fixing issues - I think it's a good choice.

Also, I want to ask you, to report all issues that you find in the paste from Word plugin - so that we could look at them.

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
