### ISSUE TITLE
Bug builder download WRONG version

### ISSUE THREAD

**Issue by Damien-Unsolite** [ckeditor/ckeditor4#4586]
Hi,
I selected some plugins (see with custom-build-id=79e0fdfb4ceff0c6ff4002eef9669752) like "placeholder_selected" in the online builder.
https://ckeditor.com/cke4/builder

And when run:
php bin/console ckeditor:install --release=custom --custom-build-id=79e0fdfb4ceff0c6ff4002eef9669752

**Or** download with the web site online builder with "Optimized" version, before Download button: a version **without this plugin** (and others) was download.

**But if I use** "Source (Big N’Slow)" version: the plug-in **was inside** the ZIP.

=> in our production server, we cannot add plug-in manually (don't have access to public directory, I just can add the command "ckeditor:install")
So if the ZIP download dosen't contains the plugins => X-(

Thank you :)

**Comment by Dumluregn** [comment]
Hello, did you start the editor and check if plugins are actually missing or base just on the content of `plugins` folder? I suspect your editor has all the plugins, but in the optimised version some of them are just merged inside the `ckeditor.js` file (and plugin folders are left only for those that need some external files like dialog definitions). So please examine if you are really missing any plugins.

If so, please upload your downloaded bundle here so that we could check it.

**Comment by Damien-Unsolite** [comment]
Hello. Thank you Dumluregn, you're all right: the file (optimized) was inside ckeditor.js
The error message "file not found" seems to appear because of the cache: I doesn't have it anymore.

So, I close this issue.
