### ISSUE TITLE
bgColor with different font sizes is not working as expected

### ISSUE THREAD

**Issue by sryarama** [ckeditor/ckeditor4#4613]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Launch ckeditor's demo full url https://nightly.ckeditor.com/21-04-09-06-04/full/samples/
2. Type some random text.
3. Select the back ground color.
4. Type some more text
5. Choose a bigger font size and type text.

### Expected result

Background color should be applied to the whole content of bigger size

### Actual result

Only specific portion is having background color. Below is the screeshot:
![image](https://user-images.githubusercontent.com/66038900/114246895-b0edc680-9948-11eb-9f96-e3d1178ec227.png)

**Comment by sculpt0r** [comment]
Hi @sryarama ,
I can confirm this issue. You didn't mention which version is affected, but as far as I checked - at least 4.13.0 and above.

Thank you for the report. 

Looks like both spans (each has a different style due to font size) should be also altered by background color. Currently, background-color style is applied on wrapper `span`.

**Comment by sculpt0r** [comment]
I talked with @f1ames and we decide to add `upstream` flag. Editor behavior is valid in this case (we provide proper HTML & style syntax). So finally it's the browser's responsibility to implement it in a valid way.

I've checked FF, Chrome, Edge & Safari - all of them display it incorrectly.

**Comment by sryarama** [comment]
> I talked with @f1ames and we decide to add `upstream` flag. Editor behavior is valid in this case (we provide proper HTML & style syntax). So finally it's the browser's responsibility to implement it in a valid way. Because of that, I have to close this issue.
> 
> I've checked FF, Chrome, Edge & Safari - all of them display it incorrectly.

Seems like that is not entirely true. Lets consider this scenario
1) Entered small text
2) Increased the font size.
3) Enter some more text.
4) Now selected smaller text & bigger text, then applied background color.

In the above scenario, editor is applying the background color properly. Below is the screenshot:
![image](https://user-images.githubusercontent.com/66038900/114637991-7608cd00-9c7f-11eb-9c6a-a7d5a24360d1.png)


I feel changing the DOM structure would resolve the original issue. Share me your thoughts on this.

**Comment by f1ames** [comment]
Hello @sryarama, as for [https://github.com/ckeditor/ckeditor4/issues/4613#issuecomment-819141262](https://github.com/ckeditor/ckeditor4/issues/4613#issuecomment-819141262) you are right that it works correctly in this case.

So we have two cases here, the one initially reported. In this case CKEditor 4 produces HTML like:

```html
<p>Some
    <span style="background-color:#2ecc71;">sample
        <span style="font-size:24px;">czxczxczx</span>
    </span>
</p>
```

And the second case (https://github.com/ckeditor/ckeditor4/issues/4613#issuecomment-819141262) which produces HTML like:

```html
<p>Some&nbsp;
    <span style="font-size:8px;"><span style="background-color:#2ecc71;">sample&nbsp;</span></span>
    <span style="font-size:36px;"><span style="background-color:#2ecc71;">text</span></span>
</p>
```

Both cases produces totally valid HTML. However in the first one the "background-color span" wraps regular text + "font-size span" while in the 2nd one there are separate "background-color spans" applied so those are slightly different cases. There are multiple reasons it was design and works that way (to provide the most semantic HTML possible, to not produce unnecessary spans) and this is the core architectural part of CKEditor 4 which is very time consuming to change and may result in backwards compatibility issues we would like to avoid.

As mentioned, the first case produces valid HTML and the fact that it is not rendered correctly is a browser issue, that's why it is marked as `upstream` issue. The workaround would be possible (changing the DOM structure as you mentioned) but due to the amount of changes required it's not on our roadmap.
