### ISSUE TITLE
paste (CTRL+V) pasteFromWordPromptCleanup

### ISSUE THREAD

**Issue by rlschilperoort** [ckeditor/ckeditor4#4614]
## Type of report

Docs

## Provide a description of requested docs changes

In [the standard version of ckeditor 4.16.0](https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.16.0/ckeditor_4.16.0_standard.zip) the pastefromword plugin is enabled.

From the documentation it is unclear to me what the result is for the behavior of the normal paste icon (CTRL+V)
It seems that both icons share the same shortcut (CTRL+V)

Adding the configuration option:
`config.pasteFromWordPromptCleanup = true;`
enables a prompt with the question "The text you want to paste seems to be copied from Word. Do you want to clean it before pasting?"
Both options in this prompt seem to paste the same result (formatted text from clipboard)

I have tested this behavior with the sample documents from https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html

Am I missing something in the documentation or in my test case?

**Comment by sculpt0r** [comment]
Hi @rlschilperoort ,
Actually pasting from Word allows to clean up the pasted content.

As [docs says](https://ckeditor.com/docs/ckeditor4/latest/features/pastefromword.html#advanced-paste-from-word-ckeditor-46): `Pasting from Word is, in general, as tricky as it can get. With plenty of possible combinations of Microsoft Word, operating system and browser versions Word output that comes through clipboard to CKEditor 4 can significantly differ.` So even if some samples look the same on certain devices, they may works differently on another OS.

Actually, PFW (Paste From Word) plugin adds some filters to the normal pasting process and those are activated only when the editor detects office content. However, if you use the PFW button, those filters are used forcibly.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by rlschilperoort** [comment]
Rephrased my question and left it on https://stackoverflow.com/questions/67086053/default-paste-prompt-paste-from-word
