### ISSUE TITLE
Default style of element

### ISSUE THREAD

**Issue by TheMixy** [ckeditor/ckeditor4#4615]
Is it possible to set default style of an element?

For example I would like that in the actual html generated by the control (what we then save to our database) all the `<p>` elements have `margin-bottom:20px`.

Browser: FF
OS: Windows 10
CKEditor version: 4

**Comment by sculpt0r** [comment]
Hi @TheMixy,

Of course, you can add custom styling to your elements. For example please take a look at [contentsCss config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss)

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by TheMixy** [comment]
This does not work when binding to a model in controller action (ASP.NET Core)

**Comment by f1ames** [comment]
@TheMixy, please see https://stackoverflow.com/a/67177317/646871.

**Comment by TheMixy** [comment]
This does not answer my question. The answer is simply no, one cannot set a default style to be automatically applied to everything a user enters...
