### ISSUE TITLE
CKEditor (I know it's an editor, but how is it used by a developer exactly?)

### ISSUE THREAD

**Issue by TrishaSeliya** [ckeditor/ckeditor4#4621]
I have been struggling with CKEditor for a while at work now, mainly because I sort of don't understand how everything fits together. https://appvn.onl/

The thing that confuses me is: what exactly is the "core" of CKEditor, and what constitutes a plugin?

Things that I thought would be in the core (UI buttons, toolbar, etc) are actually plugins. But what's the point of making them plugins when the editor is unusable without them? And every single CKEditor package available (basic, standard, advanced) comes with plugins preinstalled, and they are minified into the source code directly rather than existing in the plugins folder. So it's as if they aren't plugins but they are.https://shareit.onl/

And there's no way to upgrade your CKEditor without downloading in fresh and manually upgrading all of your plugins/config/etc. It seems there is no reliable way to manage plugins or add them into your editor other than with a fresh install.

CKEditor seems like kind of a mess to me, but maybe it's because I don't understand it. If anyone has any experience with it, please help me understand how a dev should work with CKEditor.

Thanks!

**Comment by sculpt0r** [comment]
Hi @TrishaSeliya ,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
