### ISSUE TITLE
Alternatives to CKEditor / help with imageupload

### ISSUE THREAD

**Issue by EvanaShankar** [ckeditor/ckeditor4#4622]
I'm trying to update a very basic CMS for a client and they have decided they want a bit more flexibility in places when adding content and a basic image upload.

I have added CKEditor without problems and it's fine when dealing with text, but I can't seem to get an image upload plugin to work. I have tried adding them manually and using the "builder". https://1921681001.id/

Manually I can get 90% of it working but have an issue with some of the paths to the upload directory not working (correct paths, they say they work but its a lie and they don't?) and if I use the "builder", the tool bar is completely missing.
 
Anyway, any pointers to what might be going wrong with CKEditor or recommendations for a different editor (PHP, open source preferably) - what are people using these days? https://19216811.cam/

**Comment by sculpt0r** [comment]
Hi @EvanaShankar ,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
