### ISSUE TITLE
contents.css file not loaded when divarea is used instead of the iframe based area

### ISSUE THREAD

**Issue by public-handle** [ckeditor/ckeditor4#4640]
## Type of report

Bug

### How to Reproduce
I included 4 simple examples in this fiddle: [https://jsfiddle.net/sx7nzuL0/](https://jsfiddle.net/sx7nzuL0/)
1. Open the Network tab in your console.
2. Run each in order and confirm the first two work which are based on the default iframe.
3. Run the last two which use the divarea editor and notice they don't work

### Expected result

config.contentsCss file should be loaded if specified or the fallback contents.css file should be loaded if not specified for the div based editing area

### Actual result

No contents.css file is being loaded for the div based editing area

## Other details

Here is an old bug that appears to have fixed this in the past, I'm guessing it has resurfaced:
**Old ticket:** [https://dev.ckeditor.com/ticket/13771](https://dev.ckeditor.com/ticket/13771)
**Bug Fix:** [https://github.com/ckeditor/ckeditor4/commit/8eb2434](https://github.com/ckeditor/ckeditor4/commit/8eb2434)

**Comment by Dumluregn** [comment]
Hello, this is expected behaviour. Divarea editor, just like inline editor, uses CSS provided for the website it is embedded on. For that reason it doesn't use its own stylesheet.

However this is not clearly stated in the documentation, so I've created an issue for improving the `contentsCss` config option description: https://github.com/ckeditor/ckeditor4/issues/4642.
