### ISSUE TITLE
Render React components inside the editor 

### ISSUE THREAD

**Issue by zainzin** [ckeditor/ckeditor4#4648]
Is it possible to render custom react components inside the editor? Something like this maybe,
<CKEditor data={"\<CustomComponent>\</CustomComponent>"}/>

Thank you,

**Comment by Comandeer** [comment]
You will probably need to [create a dedicated widget](https://ckeditor.com/docs/ckeditor4/latest/guide/widget_sdk_tutorial_1.html) for it.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
