### ISSUE TITLE
when edit other textbox, CKEditor text is fluctuating

### ISSUE THREAD

**Issue by kul1010** [ckeditor/ckeditor4#4649]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by kul1010** [comment]
Provide detailed reproduction steps (if any)
I am using this in react. I have sender mail text box, sender name and subject and mailbody as CKEditor(Also using defaultContent) element. But typing in any textbox CkEditor default text is fluctuating again and again. and hitting svc.webspellchek.net
Expected result
What is the expected result of the above steps?

Actual result
What is the actual result of the above steps?

Other details
Browser: …Chrome
OS: … Windows 10
CKEditor version: …
Installed CKEditor plugins: … "react-ckeditor-component": "^1.1.0",

**Comment by Comandeer** [comment]
The React component you are referring to (`react-ckeditor-component`) is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the components’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the components’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

You can also try the [official React integration](https://github.com/ckeditor/ckeditor4-react).

**Comment by kul1010** [comment]
Hello,
Issue has been resolved. 
I have installed  npm i ckeditor4-react -s 
and working fine
just using like below
`import CKEditor from "ckeditor4-react";`
```
const onChange = (evt) => {
		const newContent = evt.editor.getData();
		setContent(newContent);
		let changedData = {};
		changedData[name] = newContent;
		setFormik({ ...values, ...changedData });
		props.formik.setFieldValue(name, newContent, true);
	};

<CKEditor
data={content}
onChange={onChange}
/>
```
