### ISSUE TITLE
Javascript code doesn´t paste text 

### ISSUE THREAD

**Issue by luis-vera** [ckeditor/ckeditor4#4673]
Hi everybody:

I am trying to paste from Javascript code to a textarea replaced with CKeditor but the text can´t be visible except if I remove CKEDITOR.replace() from the original code.

I am using <textarea name="descripcion"></textarea> and CKEDITOR.replace('descripcion'). 

A button opens a popup where I display some information and I want to put in this textarea a specific text from this popup.

The javascript code in popup is:

<script language="javascript">
function selecciona(texto) {
	//alert(window.opener.name);
	window.opener.document.form1.descripcion.value = texto;
	top.close();
	}
</script>

How can I resolve this problem?

Thanks a lot for your help

**Comment by sculpt0r** [comment]
Hi @luis-vera 

Please analyze what is going on with DOM elements, after the editor is created. The original element is hidden, and a new element (with editor) is created. So if you try to interact with the original element - this has no effect. What is more, [CKEDITOR.replace](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-replace) returns editor instance. You can use it to invoke [editor.setData](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-setData) to put there your data. Please remember to wait until the editor [will be ready](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-instanceReady).

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
