### ISSUE TITLE
Justify styling is lost when applying font style

### ISSUE THREAD

**Issue by stanleyphu** [ckeditor/ckeditor4#4675]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add to configuration file:
```
config.font_style.element = 'div';
```
2. Write some text, center align it
3. Highlight the text, change text to something other than default

### Expected result

Text-align and font-family styles are both applied to the text

`<div style="font-family: Courier New, Courier, monospace; text-align: center;">`

### Actual result

Text-align styling is lost and replaced with just font-family styling

`<div style="font-family: Courier New, Courier, monospace; ">`

## Other details

* Browser: any
* OS: `macOS 10.15.7`
* CKEditor version: `4.11.0`
* Installed CKEditor plugins: `font`, `justify`

**Comment by Dumluregn** [comment]
Hello, I suppose the problem is with how you are changing the config. Please see my example where I've also changed the default element from `span` to `div` (and provided the other default values) and the `text-align` attribute is preserved. If this doesn't solve the issue, please provide a sample where it is reproducible.

**Comment by stanleyphu** [comment]
Hi, could you point me to the file where the default element is changed from `span` to `div`?
