### ISSUE TITLE
Revamp `ckeditor4-docs` repo install manual

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4679]
## Type of report

Docs

## Provide a description of requested docs changes

There are several people who had problems to set up the [`ckeditor4-docs`](https://github.com/ckeditor/ckeditor4-docs) project according to the provided guidelines on the clean workstation. It would be good to analyse the steps and update them.

**Comment by MMMalik** [comment]
That's a good idea. I spent some time recently before I was able to successfully run docs on my local machine. I noticed following missing info:

1. Use `rvm` rather than `sudo apt install ruby`. The latter command installs 2.x version and it requires `sudo` to install gems afterwards.
2. Where to look for latest `jsduck` gem?
3. Install `grunt` globally.
4. Running `grunt build-serve` can throw on `umberto` step due to too many open files. (maybe this happens only on my Windows 10 + WSL2 setup though...)

**Comment by Dumluregn** [comment]
AFAIR I've also had to install `Java Development Kit`, and to install gem I had to add a flag:
`gem install ckeditor-jsduck-0.0.9.gem -- --with-cflags="-Wno-error=implicit-function-declaration"`

Run on MacOS. I guess steps may vary depending on the OS and also one can already have some tools installed, but guide should assume you have _nothing_ besides OS.

**Comment by Dumluregn** [comment]
As for 
> Running grunt build-serve can throw on umberto step due to too many open files.

I had this issue on my old machinge (also macOS), the solution was to increase the limit (I don't remember exact command but it was something like `ulimit -n 200000`).

**Comment by f1ames** [comment]
> I had this issue on my old machine (also macOS but weaker hardware), the solution was to increase the limit (I don't remember exact command but it was something like `ulimit -n 200000`).

AFAIR I had the same issue on Linux machine :thinking:
