### ISSUE TITLE
Prevent image base64

### ISSUE THREAD

**Issue by vuongutc** [ckeditor/ckeditor4#4721]
## Type of report
I use ckeditor 4 version.

Feature request
prevent user paste or insert img base64 to sourcedialog
![Screenshot from 2021-05-20 08-45-56](https://user-images.githubusercontent.com/59592052/118907161-40739580-b949-11eb-925e-e25b18d57622.png)

## Provide description of the new feature

*What is the expected behavior of the proposed feature?*

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
