### ISSUE TITLE
Anchor link settings are automatically inserted when copying and pasting from ms word

### ISSUE THREAD

**Issue by nguyenthihaitk** [ckeditor/ckeditor4#4732]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1.Open CKEditor 4 sample.(https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html)
2.Paste content from
[pastefromword_testing.docx](https://github.com/ckeditor/ckeditor4/files/6543809/pastefromword_testing.docx)

### Expected result
All the contents are pasted correctly.
![image](https://user-images.githubusercontent.com/75294208/119602204-a1a5d800-be25-11eb-845a-74142995cbb0.png)

### Actual result
The flag stands and the text color turns blue.
Anchor link are automatically inserted. 
![image](https://user-images.githubusercontent.com/75294208/119601893-0b71b200-be25-11eb-96c3-cac73a922dfc.png)

## Other details

* Browser: Chrome
* OS: OS
* CKEditor version: 4
* Installed CKEditor plugins:pastefromword

**Comment by sculpt0r** [comment]
Hi @nguyenthihaitk ,
Thank you for the report. I can confirm this issue with latest (`4.16.1` and `4.16.0`) samples. At least with Chrome & FF.

But it works for `4.15.0` so I'm adding `regression` label.

**Comment by sridharravva** [comment]
Any update on this anchor link issue? Please let me know, as I am also getting the similar issue on chrome browser whenever I am copying/pasting numbered lists from MS work into CKEditor. I am using CKEDitor 4.16.1 standard package.

Basically, here it is the issue with numbered bullet list while copying the content with numbered bullet list from MS word and pasting into CKEditor using the "paste from word" button, then it puts lot of images, red anchor tags in the CKEditor content, messing up the actual numbered bullets.

Example:

Original Content that we are copying from MS Word :

![OriginalContent_NumeredBulletList](https://user-images.githubusercontent.com/77024903/125855111-bf5186d4-e556-445d-8263-8815f4edfb7c.png)


After Copy and Paste above original content into CKEditor using "Paste from word" button, then we get the below result and this the issue with copy/paste for numbered bulleted list:

![AfterCopyPasteIntoCKEditor_UsingPasteFromButton_UnderChromeBrowser](https://user-images.githubusercontent.com/77024903/125855204-f4e01062-ed63-4ce5-84ef-7e372a246e4a.png)

**Comment by Dumluregn** [comment]
Hello, we haven't handle this issue yet. Please follow this thread if you want to be up to date.

**Comment by sridharravva** [comment]
Thanks for letting me know.

**Comment by Comandeer** [comment]
It seems that this issue is not a regression. It does not reproduce in docs for older CKEditor 4 version due to the fact that Anchor button is disabled there. However on full preset of CKEditor 4 it can be reproduced back to CKEditor 4.5.0.

Additionally the behaviour of CKEditor 4 seems to be correct, as Word provides content with an anchor inside it. It's caused by the fact that there is a hidden bookmark inside the Word document used for testing:

![Bookmarks dialog with the list of hidden bookmarks that contain one bookmark](https://user-images.githubusercontent.com/1078728/129475599-0eaef1f7-8666-4a49-8880-f836e6333b7c.png)

This bookmark then, correctly, appears as anchor inside CKEditor 4.
