### ISSUE TITLE
Colors are removed when copy -> refresh -> paste

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor4#4747]
## Type of report

When I copy text that has styles (text color or color background using *Color buttons* plugins) and then reload page (F5 in browser) and paste it to ckeditor colors are removed. It is not happening if I paste it to the same ckeditor window without refreshing page.

## Provide detailed reproduction steps (if any)

As above

### Expected result

Colors should remain

**Comment by Comandeer** [comment]
Such behaviour is present only in Safari and Chrome-based browsers and it's connected with the default paste filter that is applied in these browsers. You can switch off this filter via a [config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter).

The part with refreshing the page is interesting. It seems that paste filter is applied only to the external paste data. In such a case the copied content is treated as one, because the source editor no longer exists. Therefore there is no sensible way to detect if the content originates from CKEditor 4's instance.

I'll close the issue as there is no real solution to the refreshing part of the issue, but the issue as whole can be workarounded by a mentioned config variable.
