### ISSUE TITLE
Add text highlighting for react

### ISSUE THREAD

**Issue by Garrett-Freddo** [ckeditor/ckeditor4#4749]
Currently I am using react to implement CKeditor4. I can't seem to figure out how to add a highlight feature, as seen in the Color Button package. I just can't figure out how to configure the toolbar to add this feature without having to click styles and select the highlight feature there on the editor, which is very inconvenient. This is my code at the moment: 

`        <CKEditor
          data={text}
          onInit = {editor => {
            setText('');
          }}
          onChange={onEditorChange}
        />`
I know it is possible to configure with the config field, but I cannot find a package/document that explains how to do this in react so any help is appreciated!

**Comment by Comandeer** [comment]
Adding configuration to React component is described in [our documentation](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html). Please refer to it.

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
