### ISSUE TITLE
Image Pasting Issue

### ISSUE THREAD

**Issue by conductexam-rk** [ckeditor/ckeditor4#4760]
When i am pasting a image from my word file it will not pasting the image. i have to paste one by one is there any solution to paste the multiple image and text at once

**Comment by sculpt0r** [comment]
Hi @conductexam-rk 

Could you provide more information about your situation? Especially CKEditor version, sample code with the editor (+ your config). You can use on of those:
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

It's hard to say what is going on without those pieces of information.

Currently our pasting images to base64 solution allows us to paste just a single image - so that may be the case?
