### ISSUE TITLE
filebrowserBrowseUrl and react integration

### ISSUE THREAD

**Issue by arbabi2010** [ckeditor/ckeditor4#4765]
Hi , how can i use rfilebrowserBrowseUrl and filebrowserUploadUrl for react ckeditor for custom filemanager? 
I found this but i can't us it
[https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html)

**Comment by sculpt0r** [comment]
Hi @arbabi2010 

We have a [ckeditor4-react repo](https://github.com/ckeditor/ckeditor4-react) for issues related to this integration.

Take a look, at [our react guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#config) which shows you how to use custom config with react integration.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
