### ISSUE TITLE
(Higher Priority) CKeditor 4.16.1 Standard- Issue with Paste from word button not working in chrome and firefox browsers

### ISSUE THREAD

**Issue by sridharravva** [ckeditor/ckeditor4#4780]
Hi,
I am using CKeditor 4.16.1 Standard version - Whenever I use "Paste from word" button in **chrome and firefox browsers** after copying content from MS Word, then I keep getting the error message saying **"Press Ctrl+V to paste. Your browser doesn‘t support pasting with the toolbar button or context menu option.".**
I am not sure how to resolve this issue, could someone please help in looking at this issue?
Please let me know if there is any config changes or custom css that we need to change in order to make this work in  in chrome and firefox browsers. Thanks in advance!

![image](https://user-images.githubusercontent.com/77024903/124159142-cadf0700-da68-11eb-8275-72e82ace498f.png)

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
