### ISSUE TITLE
CK editor doesn't reflect new changes with format dropdown

### ISSUE THREAD

**Issue by AnaMarie94** [ckeditor/ckeditor4#4785]
The CK editor doesn't seem to reflect changes using the `format` dropdown.

I am using the CK editor with `Magnolia`.

I have this in the config file:
```
	// Enable a limited set of text formats:
	config.format_tags = 'p;h3;h4;h5';
	config.format_p = { element: 'p', attributes: { 'class': 'formal' } };
```

The P element uses the class `formal` which uses this CSS:
```
.formal {
	@include robotoFormal;
	font-style: normal;
	@media (min-width: $breakpoint-lg) {
		@include robotoPrimary;
	}
}
```
When using the ck editor if I choose the `normal` dropdown which is the P tag the font doesn't update to `roboto` in the editor. It looks to me like it's using a default font.
![ck editor](https://user-images.githubusercontent.com/72869609/124452964-cd9a6e80-dd7e-11eb-829a-da6b3b2596ca.PNG)

Yet when I click save the font has updated correctly.

![roboto](https://user-images.githubusercontent.com/72869609/124453137-f4f13b80-dd7e-11eb-82cb-0349cbd714d3.PNG)

Does anybody have any ideas how to get the changes to reflect accordingly within the CK editor **before** hitting save?

**Comment by sculpt0r** [comment]
Hi @AnaMarie94 ,
It looks like you have an external css with styles for your `.class`. Might be the case, that you need to add it to the editor, not only to your website. Take a look at [our guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_styles.html#how-do-i-customize-the-styles-drop-down-list).

I'm not sure what your `save` button do, but assume it leads to display editor content to the page. In that case, your css style starts working.

Also, I'm not sure what `Magnolia` is? If this is some custom framework, that use CKEditor inside - maybe it could be issue with it?

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
