### ISSUE TITLE
[Chrome/Edge] Unable to correctly set caret with POSITION_AFTER_START / END

### ISSUE THREAD

**Issue by sven-eitelboess** [ckeditor/ckeditor4#4786]
## Type of report

Bug

## Detailed reproduction steps

URL: https://js-eaoayg.stackblitz.io/

1. Set the caret inside a bold element (test the problem)
2. Try to set the caret with the plugin AFTER_START or AFTER_END ![image](https://user-images.githubusercontent.com/45480679/124606249-fd27a480-de6c-11eb-8427-99604bffc499.png)
3. Start writing letters

### Expected result

The caret should go to the correct position and the letters should turn up at the start of the bold element or directly after.

### Actual result

Setting it AFTER_START is the same result as BEFORE_START and AFTER_END has the same result as BEFORE_END. It looks like it was set to the correct position but changes when entering a keystroke.

## Other details

Works fine on IE and Firefox.

* Browser: Chrome/Edge Chromium
* OS: Windows 10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: only sample plugins to show behaviour

Here is the sample plugin for testing purposes:

[quicknav.zip](https://github.com/ckeditor/ckeditor4/files/6770275/quicknav.zip)

**Comment by sculpt0r** [comment]
Hi @sven-eitelboess ,
The URL you provided is not working. For me - it is loading endlessly. I try on two different PC and networks - with the same effect.

As I can see, you are using [moveToPosition](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-moveToPosition) method. From our site it looks like everything is fine with this method. Are you sure, that start element of the range is the one you are expecting? It could be affected by the [trim method](https://github.com/ckeditor/ckeditor4/blob/460c9506860f3c9508e417defcec9f63dc55621d/core/dom/range.js#L1189) - which changes the inner representation of the range.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by sven-eitelboess** [comment]
Hi @sculpt0r 

Thank you for the reply. Sorry but it seems my example-url is broken in the meantime.

I tried to replicate this issue with the native selection and i get the same result, so i guess it's a browser bug after all.
[rangeBug.zip](https://github.com/ckeditor/ckeditor4/files/6790737/rangeBug.zip)
