### ISSUE TITLE
Paste with CTRL+V or RIGHT-CLICK -> PASTE doesn't function on Firefox version > 90

### ISSUE THREAD

**Issue by albertomanzini** [ckeditor/ckeditor4#4806]
### Type of report
Bug

### Provide detailed reproduction steps (if any)

    1. Install CKEditor 4.4.6
    2. Go on sample
    3. Copy text from Word
    4. Paste in CKEditor with CTRL+V
    
### Expected result

Print of copied text

### Actual result

Nothing pasted

### Other details

    I have pastefromWord plugin installed.
    With older version of Firefox bug doesn't appear

    Browser: Firefox > 90
    OS: Windows 10
    CKEditor version: 4.4.6

**Comment by sculpt0r** [comment]
Hi @albertomanzini ,
I hope it's misspelled with `4.4.6` version? Because it is very old and I strongly recommend you upgrades. Even small step by step until the newest version will be reached.

However, if it's not:
- I'm unable to paste anything by `ctrl+v` in CKEditor 4.4.6 in FF >90. 🤔
- I'm able to paste word content with the usage of the toolbar icon (paste from the world).

In the newest version `4.16.1` it works fine.

I have to close this issue because we are not making fixes for the old versions.
