### ISSUE TITLE
Failing test: plugins/widget/widgetsintegration [SAFARI]

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4815]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Failing test: `test content is removed after cutting (single widget)`

Full test path:
`/plugins/widget/widgetsintegration#tests%2Fplugins%2Fwidget%2Fwidgetsintegration%20test%20content%20is%20removed%20after%20cutting%20(single%20widget)`

### Expected result

*What is the expected result of the above steps?*

Test passed.

### Actual result

*What is the actual result of the above steps?*

Test failed.

```
selection is collapsed
Expected: true (boolean)
Actual:   false (boolean)
```

## Other details

* Browser: Safari 14.1.2
* OS: MacOS 11.5.1
* CKEditor version: DEV (pre-released 4.16.2)
* Installed CKEditor plugins: -

**Comment by sculpt0r** [comment]
It is **not** failing on Safari 13.1 🤔 
Also, **not** failing on Chrome, FF

**Comment by f1ames** [comment]
DUP of https://github.com/ckeditor/ckeditor4/issues/4759.

**Comment by f1ames** [comment]
In fact https://github.com/ckeditor/ckeditor4/issues/4759 lists more than one failing test with not that much information so let's leave this open and close #4759.

We had already concluded that this is new Safari upstream not caused by changes in CKEditor 4 itself. Still, it would be good to check if it's only the test which is failing or something is broken with drag and drop handling. cc @sculpt0r

**Comment by sculpt0r** [comment]
Duplicate: https://github.com/ckeditor/ckeditor4/issues/4691
