### ISSUE TITLE
Where is the code for automatically uploading pictures when processing words and pictures copied from word

### ISSUE THREAD

**Issue by OnePsycho** [ckeditor/ckeditor4#4832]
## Type of report

Docs

## Provide a description of requested docs changes

Can you show me a screenshot of code

**Comment by sculpt0r** [comment]
Hi @OnePsycho 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
