### ISSUE TITLE
Who can tell me how to convert the pasted pictures (the pictures copied from word are pasted together with the text, and the path is the local picture path) into Base64 format and display them in rich text in the version?

### ISSUE THREAD

**Issue by OnePsycho** [ckeditor/ckeditor4#4836]
## Type of report

Who can tell me how to convert the pasted pictures (the pictures copied from word are pasted together with the text, and the path is the local picture path) into Base64 format and display them in rich text in the version?

## Provide description of the new feature

Who can tell me how to convert the pasted pictures (the pictures copied from word are pasted together with the text, and the path is the local picture path) into Base64 format and display them in rich text in the version?

**Comment by sculpt0r** [comment]
HI @OnePsycho 

Could you provide more information about the editor version, the browser, and the office you are using? Currently, modern browsers support conversion to base64 without any problems 🤔

**Comment by OnePsycho** [comment]
> HI @OnePsycho
> 
> Could you provide more information about the editor version, the browser, and the office you are using? Currently, modern browsers support conversion to base64 without any problems 🤔

chorme lastest version and ckEditor4.0 and my office is WPS

**Comment by sculpt0r** [comment]
Hi @OnePsycho 

From my experience, the images are pasted correctly as base64 in the newest chrome. If you encounter issues, feel free to open another issue with a bug description.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
