### ISSUE TITLE
Not Working with boostrap 4 modal

### ISSUE THREAD

**Issue by kingtuan8** [ckeditor/ckeditor4#4846]
the plugin worked well, but when using with modal bootstrap 4, it not working.

Please fix this

thanks so much

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
