### ISSUE TITLE
MathJax version to update

### ISSUE THREAD

**Issue by zhangzhuoya** [ckeditor/ckeditor4#4857]
I want to use  MathJax version 3.0, but your  MathJax version is 2.0. If I want to use version  MathJax 3.0, what can I do? Do you need to update it to  MathJax？

**Comment by sculpt0r** [comment]
Hi @zhangzhuoya ,

We have a special option for that: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxLib, so you can provide your own URL here to version 3.0. Also, we have an article about MathJax in our [docs](https://ckeditor.com/docs/ckeditor4/latest/features/mathjax.html).

**However** we can't guarantee that the newest version will be compatible with CKE4 for now.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
