### ISSUE TITLE
How to get email templates in CKeditor

### ISSUE THREAD

**Issue by Tarun481** [ckeditor/ckeditor4#4893]
## Type of report

Feature request
Email temolates
## Provide description of the new feature
How to implement email templates in ckeditor and bind Html elements with database fields
*What is the expected behavior of the proposed feature?*

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
