### ISSUE TITLE
Failing CI on `major` branch

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#4903]
## Type of report

Task

## Provide description of the task

CI is regularly failing on `major` branch with full runs: https://app.travis-ci.com/github/ckeditor/ckeditor4/builds/238229402
![image](https://user-images.githubusercontent.com/10279586/134461985-ec820fbc-9c6c-49c9-bff0-505dd6ba5ea8.png)

**Comment by sculpt0r** [comment]
Looks very similar to: https://github.com/ckeditor/ckeditor4/issues/3364 🤔

**Comment by sculpt0r** [comment]
`tests/plugins/wysiwygarea/contentscss` probably fails due to changes in https://github.com/ckeditor/ckeditor4/pull/4852

**Comment by sculpt0r** [comment]
It turns out, that justify tests fails due to the same PR as `contentscss` https://github.com/ckeditor/ckeditor4/issues/4903#issuecomment-927803899

Because of a new way of linking assets in the editor (full URL), our tests assets (additional stylesheet) could not be found. And 'justify tests' verify the state of justifying buttons based on command state. Justify plugin updates commands state by default based on the computed style of the element
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-useComputedState
https://github.com/ckeditor/ckeditor4/blob/8d9239df44c7af7bf6bb78da0ad1a6cb394c78a3/plugins/justify/plugin.js#L16

In those tests, text wasn't aligned by inline styles but with CSS class names https://github.com/ckeditor/ckeditor4/blob/8d9239df44c7af7bf6bb78da0ad1a6cb394c78a3/tests/plugins/justify/justify.js#L85
So the computation happened with the missing stylesheet and gives unexpected results.

I'm going to think about a solution for that. Also, I try to find out (second time) if this PR didn't break anything more...

**Comment by jacekbogdanski** [comment]
I see that also presets CI is failing especially for some CSS differences in export to pdf plugin, see https://app.travis-ci.com/github/ckeditor/ckeditor4-presets/jobs/540190398

So indeed this PR could break other plugins.
