### ISSUE TITLE
Ckeditor dialog plugin  content should be set from onShow methode

### ISSUE THREAD

**Issue by yasir-rafiq** [ckeditor/ckeditor4#4906]
Hi, I want to set dialog contents elements on run time
 like I want to show the attributes of clicked element in dialog its load first time. But when i click on any other element dialog shows the old values because dialog is already there.
 
 Something required to update elements from onShow every time new.
 
 
 Thanks

**Comment by sculpt0r** [comment]
Hi @yasir-rafiq ,
I'm not sure if you are reporting a bug or feature request 🤔 

In our samples, you can see that after double click on the link element, the dialog contains all link details. I think I do not fully understand your intentions. You can also bind to the dialog events described here: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog.html

Could you provide some clarification - like steps you are performing on the casual editor and your expected results (like in the issue template)?

**Comment by yasir-rafiq** [comment]
@sculpt0r hi thanks for the answer, let me give you a detailed understanding.
Actually, I want to show the attributes of clicked/selected element in the dialog, first, it does properly but when I close the dialog and open for any other element its show the prev attributes list because *let listAttrElements = getListOfItems(elAttributes);*
this line won't run again until reloading the page.
I just want to update the list whenever the modal opens for any element.
`


// Our dialog definition.
CKEDITOR.dialog.add( 'abbrDialog', function( editor ) {
	let selection = editor.getSelection();
	let element = selection.getStartElement();
	let elAttributes = Object.keys(element.getAttributes());
	let listAttrElements = getListOfItems(elAttributes);

	
	return {
		// Basic properties of the dialog window: title, minimum size.
		title: 'Attributes',
		minWidth: 400,
		minHeight: 200,

		// Dialog window content definition.
		contents: [
			{
				// Definition of the Basic Settings dialog tab (page).
				id: 'basic',
				// label: 'Basic Settings',

				// The tab content.
				elements: listAttrElements
			}
		],
		// Invoked when the dialog is loaded.
		onShow: function() {
			console.log('here in on show');
		},

		// This method is invoked once a user clicks the OK button, confirming the dialog.
		onOk: function() {
			CKEDITOR.dialog.getCurrent().reset();
		},
		onLoad: () => {
			console.log('loaded')
		}
	};
});


function getListOfItems (attrObj) {
	return attrObj.map ((el, index) => { return {
		// Text input field for the abbreviation text.
		type: 'checkbox',
		id: index,
		label: el,

		// Called by the main setupContent method call on dialog initialization.
		setup: function( element ) {
			console.log('new setuop require')
			this.setValue( element.getText() );
		},

		// Called by the main commitContent method call on dialog confirmation.
		// set value onchange
		commit: function( element ) {
			element.setText( this.getValue() );
		}
	}});
}
`

Thanks

**Comment by sculpt0r** [comment]
Thank you @yasir-rafiq for the explanation. I think, now, I understand. You want to have a single `dialog` definition, that dynamically adjusts the list of elements in that dialog. The CKE4 dialogs, as you can see, are implemented more like static dialogs. So you define each dialog for attributes that you want to maintain for some element.

You can try to look at our [emoji plugin](https://github.com/ckeditor/ckeditor4/blob/major/plugins/emoji/plugin.js), so you may be able to figure out something.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
