### ISSUE TITLE
What's the best site to track Firefox 4 issues?

### ISSUE THREAD

**Issue by jasminben11** [ckeditor/ckeditor4#4950]
kindly give some good suggestions

**Comment by jacekbogdanski** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by freddwoods** [comment]
I am an [essay writer](https://perfectessaywriting.com/) when I usually use firefox and get some issue than I Restart Firefox in Troubleshoot Mode
