### ISSUE TITLE
Need Support for Bulletin with Bracket in Ckeditor

### ISSUE THREAD

**Issue by Kovair-Engneering** [ckeditor/ckeditor4#4975]
How can we support numbered Bulletin with Bracket (like word) i.e. (1), (A), (I), (i), (a) etc. in Ckeditor??
So, We need some support from Ckeditor end point since we have this requirement and we need help from you to implement it. This is stated below.
(1) This is a new paragraph.
(2) This is second paragraph

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
