### ISSUE TITLE
I want to take the image address and add it to data-original="image url"

### ISSUE THREAD

**Issue by Adalente** [ckeditor/ckeditor4#4980]
Sample : <img src="Bengal-kedisi.jpg" data-original="Bengal-kedisi.jpg"  class="lazy w-100 ortalaimg">

`  on: {
    instanceReady: function() {
      this.dataProcessor.htmlFilter.addRules( {
        elements: {
          img: function( el ) {
            if ( !el.attributes["data-original"])
              el.attributes["data-original"]= 'images URL';
            el.addClass( 'lazy w-100 ortalaimg' );

          }
        }
      } );
    }
  }
`

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
