### ISSUE TITLE
Use custom tag as placeholder in Placeholder plugin

### ISSUE THREAD

**Issue by KeldJ** [ckeditor/ckeditor4#4992]
## Type of report

Task

## Provide description of the task

To access the placeholder in DOM using $("placeholder") I would like to replace the [[]] with a custom tag (<related>) i replaced the code in the plugin as below

//var placeholderReplaceRegex = /\[\[([^\[\]])+\]\]/g;
var placeholderReplaceRegex = `/<related>(.*?)<\/related>/g;`

When doing that i can find the placeholder but when processing its stripped again 

I made a hack 

if (node.parent.name == 'related')
   `text` = `'<related>'` + text + `"</related>";`
   
  Which makes the placeholder unselectable but its reproducing itselfs when changing code 
`<related><related>text</related></related>`

## Other details

* Browser: …
* OS: …
* CKEditor version ckeditor_4.17.1
* Installed CKEditor plugins: placeholder, widget ryv

**Comment by sculpt0r** [comment]
Hi, @KeldJ

If I good understand:
- you try to customize `placeholder` plugin
- currently, we use `spans`: https://github.com/ckeditor/ckeditor4/blob/3ec1aa9190a41042a2406f64eef1a2b83228b6b3/plugins/placeholder/plugin.js#L39
- you want it to be `related` tag instead of `span`
- additionally, you want to get rid of `[[]]` inside tags and you want to put there `()` instead

All above leads you to malfunction `placeholder` plugin? Is that correct? 

Would you like to have some config option for that plugin - that allows you to set custom template? Or, you want us to help you with the implementation?

**Comment by KeldJ** [comment]
Hi again

Instead of the placeholder [[]] i would like to use tags where i can put attributes like <div class="placeholder" data-id="25789"></div>

I made a change so i just use css to make the div un editable <div contenteditable="false" class="placeholder" data-id="25789"></div>
