### ISSUE TITLE
Change listener not called after setData() or insertHtml()

### ISSUE THREAD

**Issue by fipro78** [ckeditor/ckeditor4#5006]
Hi,

I have created a SWT widget that actually uses an SWT Browser control and integrates the ckeditor to provide a RichText editor in SWT.

https://github.com/eclipse/nebula/tree/master/widgets/richtext

The integration works pretty well and I have even added an option to add toolbar actions via SWT API.

There is currently one issue I am investigating, but I don't know where to look at. Maybe you can help me on this:

If the editor is opened and a text is set to the editor via setData() or insertHtml() the change listeners are not notified if characters are deleted via DEL or BACKSPACE. If the focus is set into the text area and a character is inserted or ESC is pressed, the change events are fired correctly. And from that point on, the change Events are fired correctly everytime. It is only the corner case when setting some text programmatically into the text area and then directly trying to delete something. It looks like the change handling needs to be activated via keypress in the textarea, but DEL or BACKSPACE doesn't seem to trigger that activation.

Any idea what could be the reason for that behavior? I tried several options, but nothing worked out. Would it be possible to trigger the change activation somehow or as a workaround trigger for example a ESC keypress for the activation?

The template that integrates the ckeditor is located here:
https://github.com/eclipse/nebula/blob/master/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/resources/template.html

Any insights or ideas are highly appreciated.

**Comment by fipro78** [comment]
I know it was a bot, but there are no questions for further information, so I am not sure how to keep this issue open until someone responds. Hopefully this will do it.

**Comment by jacekbogdanski** [comment]
@fipro78 sorry for the late response. I'm not sure what do you mean by writing:
>If the editor is opened and a text is set to the editor via setData() or insertHtml() the change listeners are not notified if characters are deleted via DEL or BACKSPACE.

I did some quick check with:

```js
editor.on( 'change', function() { console.log( 'called' ); } );
editor.setData( '<p>foobar</p>' );
```

and focusing + deleting characters using DEL and BACKSPACE triggers change events. I assume that this issue is specific to your custom widget? Could you share some simplified codepen or other online JS editor with a demo?

Note that you can also trigger `change` event by yourself if your implementation changes editor execution flow or this event is expected based on your use cases

**Comment by fipro78** [comment]
@jacekbogdanski 

Thanks for the reply. Unfortunately I can't provide a simplified demo with plain JS or HTML. I am using SWT BrowserFunctions to provide a bi-directional integration of Java code and JS code. This is necessary so SWT developers can initialize and interact with the widget as they are used to with Java code, and states and events can be passed from the ckeditor javascript to the Java layer. This works pretty fine, it is only the special case of deleting characters directly after setting a value before any other typing happened.

Interestingly the deletion causes change events correctly after typing happened. It is only directly after the initialization. 

I use a config object to initialize the editor. Looking closer again to the config I realized the following:

```
//ensure the key pressed event is fired if Enter is pressed
'key'				: function(event) { event.data.preventDefault(false); },
```

I added that because otherwise pressing Enter does not cause a keyPressed event. If I remove that line, the reported issue is gone, but then I get no keypress on Enter. Is there any other way I could get the keypress on Enter?

**Comment by jacekbogdanski** [comment]
`enter` key seems to be correctly propagated for me either. You can take a look at events priority for `on` listener which may help you with that problem - https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-on

Since your implementation changes the code flow of the keystroke handler, I'm closing this ticket as it doesn't seem to be CKE4 bug. If you find out that the issue is on the editor side, please let us know so we can reopen this ticket. In case of support questions, you may like to use [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
