### ISSUE TITLE
Codecogs Eqneditor is not working with CKEditor

### ISSUE THREAD

**Issue by sashank-karanam** [ckeditor/ckeditor4#5011]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Donwload and add the eqneditor in the plugins folder (https://ckeditor.com/cke4/addon/eqneditor) 
2. Include eqneditor in the ckeditor config
3. Include EqnEditor in the toolbar
4. Open eqneditor by clicking on the 'fx' icon 

### Expected result

*What is the expected result of the above steps?*
A dialog with various special symbols to facilitate math equation typing is expected

### Actual result

*What is the actual result of the above steps?*
The symbols are not loading hence unable to type the required equation 

## Other details

* Browser: Google Chrome - Version 96.0.4664.110 (Official Build) (64-bit) 
* OS: Ubuntu 16.04
* CKEditor version: 4.7.1
* Installed CKEditor plugins: eqneditor (https://ckeditor.com/cke4/addon/eqneditor)

**Comment by jacekbogdanski** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
