### ISSUE TITLE
There is no lineheight plugin

### ISSUE THREAD

**Issue by Junfeizhao** [ckeditor/ckeditor4#5015]
I use ckeditor4. Now I need to use the linheight plugin. Where can I find it

**Comment by gandhar-workik** [comment]
Hey @Junfeizhao, you can use this plugin
[https://ckeditor.com/cke4/addon/lineheight](https://ckeditor.com/cke4/addon/lineheight)
I use it too.

**Comment by sculpt0r** [comment]
Hi @Junfeizhao 
As you already get an answer from the @gandhar-workik I can only say, that on our plugin page is a search option. So in case, the build-in plugins are not enough - please check there for extra plugins :)

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
