### ISSUE TITLE
Paste as plaintext does not work

### ISSUE THREAD

**Issue by mohsen** [ckeditor/ckeditor4#5027]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Download this [build config](https://ckeditor.com/cke4/builder/072796f87a88e5241cb9d3fc6f17c279)
2.  Unzip.
3. Run sample index.html using Chrome 96.0.4664.110
4. Copy a paragraph. Paste using Ctrl+Shift+V.

### Expected result

Paste as plain text.

### Actual result

Paste as plain text does not work. The following error is thrown in the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'exec')
    at CKEDITOR.plugins.clipboard.dataTransfer.h [as getData] (ckeditor.js:1467)
    at a.<anonymous> (ckeditor.js:764)
    at a.q (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at u (ckeditor.js:737)
    at ckeditor.js:747
```

## Other details

* Browser: Google Chrome 96.0.4664.110 (64 bit)
* OS: Windows 10
* CKEditor version: 4.17.1
* Installed CKEditor plugins: https://ckeditor.com/cke4/builder/072796f87a88e5241cb9d3fc6f17c279

**Comment by Comandeer** [comment]
The plugin that causes the issue is [Paste From Excel](https://ckeditor.com/cke4/addon/pastefromexcel) and it is a third-party one, not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
