### ISSUE TITLE
[SharedSpace] Inline editor buttons not disappearing when saving comments in XWiki

### ISSUE THREAD

**Issue by SimpelMe** [ckeditor/ckeditor4#5045]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

We use the XWiki inline editor with ckeditor plugin SharedSpace. (For accessibility reasons we don't like jumping editor buttons.)

Therefor we add in the XWiki admin pages in ckeditor config:

```java
config.sharedSpaces = {
    top: 'cke_anchor'
};
```
That #cke_anchor had this style:
```css
/* Inline-Editor soll oben sticky sein - #cke_anchor ist selbst erzeugt */
#cke_anchor {
    position: sticky;
    top: 0;
    margin-left: -2px;
    z-index: 1;
}
```
The #cke_anchor itself is created this way in XWiki:
```javascript
// DIV für Inline-Editor erzeugen für das Plugin 'sharedspace'
try {
  let wikiparent = document.querySelector("#xwikicontent");
  let newDiv = document.createElement("div");
  newDiv.id = "cke_anchor";
  wikiparent.insertAdjacentElement('beforebegin', newDiv);
} catch (e) {
  console.log('Konnte keinen Achor-DIV für Inline-Editor erstellen')
};
```
While editing XWiki articles inline everything is fine and editor buttons appear. When saving editor buttons disappear.

When writing a comment inline editor buttons appear but does **not** disappear when saving. Only reload of the page makes the buttons disappear.

I know that this is a bit tricky. Which component is messing around? Could be SharedSpace or CKEditor or XWiki or we with our js or css.

PS: Asked for help at XWiki too - https://forum.xwiki.org/t/plugin-sharedspace-inline-editor-buttons-not-disappearing-when-saving-comments/9739

### Expected result

When saving XWiki comments the inline editor buttons should vanish.

### Actual result

The whole buttons strip keeps visible.

## Other details

* Browser: actual Google Chrome and Brave
* OS: Windows 10 V 20H2 / OSX Monterey V12.1
* CKEditor version: don't know but CKEditor 4
* XWiki version: XWiki Jetty HSQLDB 13.1
* Installed CKEditor plugins: sharedspace v4.16.2, a11ychecker v1.1.1

**Comment by sculpt0r** [comment]
Hi @SimpelMe 

The implementation you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the implementation's author -  what you already did - who should be able to review the problem and suggest a solution.

If, however, after contacting the implementation maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
