### ISSUE TITLE
Problem to change the lengend table

### ISSUE THREAD

**Issue by lkf77081** [ckeditor/ckeditor4#5048]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. upload a picture
2. color legend for picture
3. change the width of the table

### Expected result

The boarder of table can be dragged to change the width always.

### Actual result

Some times the border of the right can't be selected to drag.

## Other details

* Browser: Edge
* OS: win10
* CKEditor version: …4.14.1
* Installed CKEditor plugins: …

**Comment by lkf77081** [comment]
![image](https://user-images.githubusercontent.com/54166758/151097535-c7d07366-964b-475d-86d2-9967b4e6cc56.png)

**Comment by sculpt0r** [comment]
Hi @lkf77081 

Thank you for the report. Could you provide some more information so that we can eventually confirm the issue? Which plugin to handle images are you using? I assume you use [Table Resize](https://ckeditor.com/cke4/addon/tableresize) plugin? Could you list the plugins that are used and any configuration option that is different from the default one?

I'm not sure if actually uploading the image cause issues with the table? Are those steps necessary or maybe other actions that change the content cause trouble?
