### ISSUE TITLE
FontAwesome icons not showing in Editor after setData from HTML file

### ISSUE THREAD

**Issue by AndrewDawnbringer** [ckeditor/ckeditor4#5073]
Hello there!

Not sure if it's a bug, or I'm just missing something. 

So I've the basic editor structure:
```
<form action="" method="" data-sample-short>
      <textarea name="editor1">
    
      </textarea>
  </form>
  <button id="AJAX">Save</button>
  <script>
    CKEDITOR.replace('editor1', {
      removeButtons: 'PasteFromWord'
    });
  </script>
```

And I'm loading a HTML file into the textarea upon DOM Ready:

```
$.get({
          url: loadurl,
        }).done(function(returndata) {
          //console.log(returndata);
          CKEDITOR.instances.editor1.setData(returndata);
        })
        .fail(function(returndata) {
          console.log( "fail" );
        })
        .always(function(returndata) {
          console.log( "Trying to load: "+loadurl );
        });
```

I made some adjustments to config:
```
CKEDITOR.config.extraPlugins = 'language,ckeditorfa';
CKEDITOR.config.fullPage = true;
CKEDITOR.config.extraPlugins = 'autogrow';
CKEDITOR.config.autoGrow_maxHeight = 400;
CKEDITOR.config.autoGrow_minHeight = 800;
CKEDITOR.config.allowedContent = true;
CKEDITOR.config.protectedSource.push( /<i class[\s\S]*?\>/g );
CKEDITOR.config.protectedSource.push( /<\/i>/g );
CKEDITOR.dtd.$removeEmpty['i'] = false;
CKEDITOR.dtd.$removeEmpty['span'] = false;
CKEDITOR.config.contentsCss = '/../../css/font-awesome.min.css';
```

And also included FA in the head. My problem is, the textarea does not show FontAwesome icons. The actual page is OK, it's only affecting the editor. Attaching images for clarification.

In the editor:
![editor](https://user-images.githubusercontent.com/14193735/152307493-c2a051fa-6eff-45f2-99ee-0102a604bd13.png)

On the page itself:
![page](https://user-images.githubusercontent.com/14193735/152307511-c3e578bc-53c3-4a27-ba45-becbe13f3e7a.png)

**Comment by AndrewDawnbringer** [comment]
I also found this: https://stackoverflow.com/questions/17589747/adding-fontawesome-to-ckeditor

Removing the 
```CKEDITOR.config.protectedSource.push( /<i class[\s\S]*?\>/g );
CKEDITOR.config.protectedSource.push( /<\/i>/g );```
lines made icons show up in the editor, however, it's not that easy to use them.

**Comment by Comandeer** [comment]
Theoretically, the following config should be enough to make them work:

```
CKEDITOR.dtd.$removeEmpty.i = false;

CKEDITOR.replace( 'editor', {
	contentsCss: [ 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css' ],
	extraAllowedContent: 'i(*)',
	coreStyles_italic: {
		element: 'em'
	}
} );
```

However, it seems that bug in `basicstyles` plugin prevents the correct behaviour of icons (see #5075). The easiest workaround is to switch from `i` to `span` elements for icons: [https://jsfiddle.net/Comandeer/shgLueax/](https://jsfiddle.net/Comandeer/shgLueax/)

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
