### ISSUE TITLE
event.data.dataTransfer.$.files on editor.on('paste') is empty on Chrome but not in Firefox

### ISSUE THREAD

**Issue by celsowm** [ckeditor/ckeditor4#5099]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
```js
function init(editor) {
        if (editor.addFeature) {
            editor.addFeature({
                allowedContent: 'img[alt,id,!src]{width,height};'
            });
        }
		
		CKEDITOR.on('instanceReady', function(event) {
			event.editor.on('paste', resize, null, {editor: editor});
		});

    }

function resize(event){
    console.log(event.data.dataTransfer.$.files);
}
```

### Expected result

If you drag one image on firefox the result is something like:

```
FileList [ File ]
​0: File { name: "one_pixel.JPG", lastModified: 1645238370564, size: 631, … }
```

### Actual result

But on Chrome:

[FileList {length: 0}](url)

## Other details

* Browser: firefox and chrome
* OS: windows
* CKEditor version: 4.17.2 (full)
* Installed CKEditor plugins: all

**Comment by Comandeer** [comment]
The difference between Firefox and Chrome is connected to how these browsers handle `DataTransfer` objects. Chrome allows getting its content only synchronously, inside `paste` event listener – saving it in the variable and trying to read it outside the original `paste` listener would result in the empty `DataTransfer` object. On the other hand, Firefox allows saving `DataTransfer` "for later" – [demo](https://jsfiddle.net/h49w6nta/2/) (Firefox should display 1 after dropping an image and Chrome should display 0).

This difference is visible in this particular case because the Clipboard plugin has [built-in support for drag&dropping images.](https://github.com/ckeditor/ckeditor4/blob/9eb0475a151e1d62a0763bf00f3fa8386e7ca421/plugins/clipboard/plugin.js#L149-L203) In short, it binds a listener with a super high priority which intercepts all dropped images and cancels the original `paste` event. However, it then fires another `paste` event with an image already transformed into Base64-encoded Data URL and `DataTransfer` from the original event – and that second event is the one observed by your `paste` listener. Due to the difference in browsers' behavior, Firefox still provides access to the original `DataTransfer` while Chrome doesn't and such behavior is completely unrelated to CKEditor 4.

However, that issue can be bypassed by creating a listener with even higher priority (in this case `0` or some negative number) – such listener would be fired before the one in the Clipboard plugin ([proof](https://jsfiddle.net/eo547z1p/)  – when an image is pasted the number of files inside `DataTransfer` should be logged; for both browsers the first event should contain 1 file). The other solution is to use [`config.clipboard_handleImages` option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-clipboard_handleImages) to completely disable built-in support for drag&dropping images.
