### ISSUE TITLE
CKEditor removes &nbsp; when font is changed ( Font change, Make Bold etc)

### ISSUE THREAD

**Issue by sudheerb** [ckeditor/ckeditor4#5137]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add data to CK editor **source** mode with contents of the attached **Input_Data** file/as seen below.
```
<div>1</div>

<div>&nbsp;</div>

<div>2</div>

<div>&nbsp;</div>

<div>3</div>

<div>&nbsp;</div>

<div>4</div>
```
2. Go back to design mode and select all data and change font - select all and click on **Bold** plugin.
3. The `&nbsp;` is lost in the source mode as seen in the **Output_Data** file/below.
Go and check data in Source mode:
```
<div><span style="font-weight:bold;">1</span></div>

<div><span style="font-weight:bold;"></span></div>

<div><span style="font-weight:bold;">2</span></div>

<div><span style="font-weight:bold;"></span></div>

<div><span style="font-weight:bold;">3</span></div>

<div><span style="font-weight:bold;"></span></div>

<div><span style="font-weight:bold;">4</span></div>
```

Note:
To make font changes, say make data bold we are using 
`<div><span style="font-weight:bold;"` instead of `<p><strong>`

### Expected result

`&nbsp;` should continue to exist even after data is made bold.

### Actual result

&nbsp is removed and its empty. This actually removes the space/newline that was present in the data.

## Other details

* Browser: Chome/Firefox
* OS: Mac/Windows
* CKEditor version: 4.16.2
* Installed CKEditor plugins: standard

**Comment by sculpt0r** [comment]
Hi @sudheerb,
Thank you for the report. I can't reproduce the issue in the standard editor. But, as you mentioned:

> To make font changes, say make data bold we are using `<div><span style="font-weight:bold;"` instead of `<p><strong>`

Could you elaborate on that? How exactly you are manipulating the styles? Could you provide some samples in one of those:
* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report

Please include every config and non-standard option you are using, because they might have impact on the editor behaviour.
