### ISSUE TITLE
Selecting RTL language is not changing the text direction

### ISSUE THREAD

**Issue by omidshojaee** [ckeditor/ckeditor4#5154]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … Add any RTL language to the config eg ```'fa:Farsi:rtl', 'en:English'```
2. … Select the Farsi language from editor's menu

### Expected result

The entire widget should switch to RTL. Tooltip of menu items, dialogs and messages should display in Farsi.

### Actual result

Basically nothing happens only ```<p dir="rtl"">``` is added to the source.

## Other details

* Browser: …Microsoft Edge
* OS: … Windows 10
* CKEditor version: … 4.18.0
* Installed CKEditor plugins: … All plugins and languages maintained by CKEditor.

**Comment by omidshojaee** [comment]
I'm expecting this functionality :

https://ckeditor.com/docs/ckeditor4/latest/examples/uilanguages.html

Selecting any RTL language is changing the UI entirely.

**Comment by KarolDawidziuk** [comment]
Hello, @omidshojaee

For now, I cannot confirm your report because it looks like everything works well. 
Tested on macOS and Windows 10.

Can you provide the reproduction sample with your editor config that will be able to show your issue?

I encourage you to use one of our samples to create it:

* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report

**Comment by omidshojaee** [comment]
Hello,

I'm having this issue on django-ckeditor so I can't provide the
reproduction sample, but that's not important because django-ckeditor is
just a wrapper.

I'll send you a screen record shortly.

**Comment by sculpt0r** [comment]
Hey @omidshojaee 

Seems that you changed only content language. From https://github.com/ckeditor/ckeditor4/issues/5154#issuecomment-1097858721 I assume you try to change the language for the entire CKEditor. Please take a look at https://ckeditor.com/docs/ckeditor4/latest/examples/uilanguages.html (which is also linked at the documentation page you mentioned in the above comment). Maybe that helps you? However - I'm not sure how the django integration is working 🤔 

The django-ckeditor you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by omidshojaee** [comment]
Hello

django-ckeditor is just a wrapper.

What's happening is that I add Language to the toolbar and it doesn't work
as intended.

**Comment by jacekbogdanski** [comment]
There are a couple of options you can use to change editor language. As an example take a look at [`config.contentsLangDirection`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsLangDirection).

Please, take a look at our documentation for more information - https://ckeditor.com/docs/ckeditor4/latest/examples/language.html

If you see that there is something wrong with the editor itself, provide reproduction steps using the online editor of your choice from the list that was proposed in the issue template:

* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report

We are not able to investigate issues that are missing proper reproduction steps and are based on 3rd party software (including web frameworks).

**Comment by jacekbogdanski** [comment]
Regarding:
>I'm expecting this functionality :

> https://ckeditor.com/docs/ckeditor4/latest/examples/uilanguages.html

> Selecting any RTL language is changing the UI entirely.

CKEditor 4 is not allowing to change the whole editor language dynamically (only content). What you are seeing there is a custom integration replacing an editor instance with another one and setting the proper `config.language` option. You can simply write a similar feature on your own with a couple of lines of code (or just peek dev console how it has been configured on the page).

**Comment by omidshojaee** [comment]
Thanks for clarification.

**Comment by omidshojaee** [comment]
Quick question: if Language plugin is not changing the language of the editor, and is not setting the paragraph direction to RTL/LTR according to the selected language, and I have to click on RTL menu button for that, then what this plugin is doing?
Get BlueMail <https://bluemail.me> for Desktop
Jacek Bogdański wrote:
Regarding:
I'm expecting this functionality :
https://ckeditor.com/docs/ckeditor4/latest/examples/uilanguages.html <https://ckeditor.com/docs/ckeditor4/latest/examples/uilanguages.html> 
Selecting any RTL language is changing the UI entirely.
CKEditor 4 is not allowing to change the whole editor language dynamically (only content). What you are seeing there is a custom integration replacing an editor instance with another one and setting the proper config.language option. You can simply write a similar feature on your own with a couple of lines of code (or just peek dev console how it has been configured on the page).
