### ISSUE TITLE
Paste from excel

### ISSUE THREAD

**Issue by Luiscat** [ckeditor/ckeditor4#5182]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
When paste cells from excel it paste and image of the cells and then paste the excel cells itself, duplicating the information.

### Expected result
It should only past the cells that can be edited on a table.

## Other details
This started to happen when i add the plugin to paste images.
Before didn't happened.

* Browser: … Chrome
* OS: … Windows 10
* CKEditor version: … 4
* Installed CKEditor plugins: …See build config attached
[build-config.zip](https://github.com/ckeditor/ckeditor4/files/8633717/build-config.zip)

**Comment by Comandeer** [comment]
The issue is most probably connected with `pastebase64`. However, you don't need any additional plugins for pasting images as Base64 string – this feature is now built-in into the official [Clipboard plugin](https://ckeditor.com/cke4/addon/clipboard). Therefore the easiest solution to the issue is to remove the plugin for pasting images.

The plugin that causes the issue is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue if you decide to keep the plugin inside your editor. In that case, please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
