### ISSUE TITLE
Render math formulas by MathJax not MathType

### ISSUE THREAD

**Issue by chrisooo3** [ckeditor/ckeditor4#5245]
I am using Ckeditor `v4` and MathType to write math formulas.
The default rendering of math formulas in CKEditor is done by sending a `MathML` snippet to the MathType server and then this server returns the math formula as an image.

As you can imagine, it can be very slow, if you have a lot of formulas(a lot of requests has to be made to MathType server)

As you may know, there is a perfect frontend library to render math(MathML) formulas called [MathJax][1]

How can I render formulas in CKEditor using MathJax, a fronted library?

  [1]: https://www.mathjax.org/

**Comment by Comandeer** [comment]
The MathType is a third-party plugin developed by [Wiris](http://www.wiris.com/). Please report a ticket directly to [its repository](https://github.com/wiris/html-integrations/issues).

However, there is also a [separate MathJax plugin for CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/features/mathjax.html) which can be used instead of the MathType one. Unfortunately, currently there is no way of integrating them.

**Comment by chrisooo3** [comment]
Hi @Comandeer,
thanks for the answer, one more question, how to use your [repo](https://github.com/ckeditor/ckeditor4/blob/master/plugins/mathjax/plugin.js) to render formulas written in MathML, not latex?

**Comment by Comandeer** [comment]
Sorry for the delayed reply.

Unfortunately, there is no way to use the Mathjax plugin with non-LaTeX syntax.
