### ISSUE TITLE
ckeditor dropdown menu does not open after first time.

### ISSUE THREAD

**Issue by kertom** [ckeditor/ckeditor4#5246]
## Type of report

Dropdown menu does not open after first time touch.
Bug occurs only on device/iPad and not locally.

Touch a dropdown menu so that it opens. Afterwards touch another dropdown menu(maybe the one next to it) . This does not open . You have to touch it two times more in order for it to open.

This does not happen locally but only on the device/iPad.
Could you help me ,please?

Codepen: https://codepen.io/thomas-kertsalis/pen/abqrzmE

All dropdown menus should open directly once they get touched.

*What is the actual result of the above steps?*

## Other details

* CKEditor version: 4
* Installed CKEditor plugins:  dropdownmenumanager

**Comment by kertom** [comment]
What do you mean by “CKEditor 4's docs” ,please? The issue exists only on the device(e.g iPad) and not on the browser(locally). I “patched” it by forcing a second click after the first time. However this is just a temporary and not the ideal solution. I was wondering if you could test the ckeditor dropdown menu on an ipad in order to reproduce the issue ,please? As i mentioned, this happens only after the first time a dropdown menu opens. When one drop down menu is open and the user tries to open another one, then the second does not open.

**Comment by Comandeer** [comment]
> What do you mean by “CKEditor 4's docs” ,please?

I meant CKEditor 4 samples that are available in our official documentation, e.g. [https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html)

I've tested them with an iPad and I'm not able to reproduce the issue there. Could you check if it's reproducible there on your device? If not, then the issue is probably connected with some of your 3rd party plugins, like the `dropdownmenumanager` one.
