### ISSUE TITLE
Hyperlinks not "sticking" after being added 

### ISSUE THREAD

**Issue by missenc** [ckeditor/ckeditor4#5264]
I'm using elFinder with CKEditor4.  Plenty of things are working superbly, but not hyperlinking.

I can right-click on the HTML file in elFinder, the file opens cleanly in a full-screen CKEditor, and I can add text, tables, and images flawlessly.

However, when I try to create a hyperlink, the pop-up box opens as normal, I either "browse the server" or type in my URL, as I have for many years with CKEditor (which goes all the way back to the "FC" days), but when I press OK, I return to the editor screen and nothing has happened.  Looking at the source code, there's no sign of the hyperlink code.

All of this works perfectly on the demo and in my past experience, so I'm assuming that I screwed something up when installing and customizing this version.  

Has anyone seen this before?  Is there a cure?

Thanks,

-- Cliff

**Comment by sculpt0r** [comment]
Hi @missenc 

The `elFinder` you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
