### ISSUE TITLE
Issue with zero width non-breaking space characters on Chromium Edge

### ISSUE THREAD

**Issue by vaishnavsivadas** [ckeditor/ckeditor4#5292]
## Type of report

Bug

## Issue Details

This was a query for an issue which was already raised (and confirmed as an issue on the ckeditor side for the webkit based browsers) 
To give an overview, we are facing issues with navigating between characters inserted into the editor due to the zero-width space characters getting randomly inserted between the same. The browser where the issue is seen is Chromium Edge.

Adding the link to the same issue which was earlier raised in this forum here: https://github.com/ckeditor/ckeditor4/issues/4939

The block of [code](https://github.com/ckeditor/ckeditor4/blob/master/core/selection.js#L2283) which is causing the issue is also identified and it exists within the core/selection.js file

Adding code for reference below:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/20839626/180191385-9c9fe874-6026-4d89-8d55-110b81884a5b.png">

To understand the purpose of this code block (where the filling character gets inserted into the range), I tried looking into the ckeditor [ticket](https://dev.ckeditor.com/ticket/1272) which was given as reference within the if check (please refer to the screenshot above) but the ticket mentioned there was raised for an issue faced in safari and I couldn't find a correlation between the same. 

Reading through the comment given, it says the zero-width space characters are required for restricting the webkit based browsers from manipulating the selection by itself. To understand the actual issue mentioned here I updated the if check of this block as per our requirement, that is by excluding chromium edge from the list of webkit based browsers thus preventing the zero-width space character insertion. 

Adding the updated if condition for reference below:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/20839626/180194374-34dc1f35-ee89-422f-af65-475516589f97.png">

`The inEdgeContext() in the if condition call would return true only if the browser is chromium edge.`

After making the change, I tested the workflows related to navigation and selection of characters within the editor and couldn't find any issues as mentioned in the comment added to the if block. But to understand the actual impact of making this change, it would be helpful if someone could help me understand what exactly the issue mentioned in this [comment](https://github.com/ckeditor/ckeditor4/blob/master/core/selection.js#L2284) was so that testing could be done around the same thoroughly before finalising on this workaround.

**I am providing the same re-creation steps as mentioned in the original issue ticket which was raised, so that it gives more clarity**:

## Provide detailed reproduction steps (if any)

- CodePen: https://codepen.io/vamseek/pen/vYJEPEw

1. Use the above code pen project, in the editor enter two words and press enter. The cursor will move to second line and goes to end of first line. (all the words will be marked as misspelled as the function to check for spelling is mocked to return a promise which resolves to false always)
2. Now click on enter again, the cursor will be on the third line instead of the second, and the type two words and navigate to the start of third line and the zero width spaces will be present at the start of third line and we would need additional key presses (7) to move it back to second line.
3. When the zero width spaces are present in between a word, double clicking to select the word selects only portion of the word before or after the zero width spaces. This issue can be reproduced when we type random words fast and clicking on enter several times.

### Expected result

1. Cursor should stay on the new line when enter is pressed after a misspelled word
2. Zero width non-breaking spaces should be removed when using arrow keys and cursor should not stuck in between them

### Actual result

1. Cursor goes back to previous line when enter is pressed after a misspelled word
2. Zero width non-breaking spaces are not being removed when using arrow keys and cursor gets stuck in between them

## Other details

* Browser: Chromium Edge (any webkit browser)
* OS: Windows
* CKEditor version: 4.14.0
* Installed CKEditor plugins: None

**Comment by vaishnavsivadas** [comment]
Does someone have an update on this?

**Comment by jacekbogdanski** [comment]
@vaishnavsivadas sorry for the late response but the issue you raised requires additional verification from our side. I will try to get back to you as soon as possible (hopefully, today).

**Comment by vaishnavsivadas** [comment]
Sure, Thanks @jacekbogdanski

**Comment by vaishnavsivadas** [comment]
Hi @jacekbogdanski,  Just a gentle reminder that we were waiting for your response. Just to make the expectation clear, more than a fix for the issue here, I'd like to understand why the if block (which introduced the issue) was introduced to the source code in the first place and whether the proposed fix (which I have added in the description above) would have an impact which I should know about so that I could specifically test those scenarios. As of now I haven't found any issues after making this change in the Edge environment.

Really appreciate your time looking into this issue. 
Thanks.

**Comment by jacekbogdanski** [comment]
@vaishnavsivadas in WebKit-based browsers it's not possible to place an editable selection inside empty elements. That problem was described in the upstream issue reported by our team on the [WebKit issue tracker in 2007](https://bugs.webkit.org/show_bug.cgi?id=15256) (unfortunately, with no fix so far):

> For example, suppose we have the following HTML:
> 
>     Some <b></b>text.
> 
> 
> When using the DOM range and selection to move the caret inside the <b></b>, the editing point will be after it instead:
> 
>     Some<b></b>|text.
> 
> The expected result:
> 
>     Some<b>|</b>text.

That bug forces rich text editor creators to come up with different workarounds to put selection inside empty elements ( especially in the case of the user interaction), so when a user types some text inside that selection, the element is properly expanded.

In the case of CKEditor 4, we decided to create a special [Filling Char Sequence](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_selection.html#property-FILLING_CHAR_SEQUENCE) content that is used to _fake_ an existence of some content allowing to put a selection into that element. As an example, CKEditor 5 uses a more thoughtful technique by adding a special `<br>` element.

I took a look at the consequences of disabling the code you mentioned in [`/core/selection.js#L2286`](https://github.com/ckeditor/ckeditor4/blob/cd1dc1a3e0357b7e8e80b2d478ded67b67a5f07b/core/selection.js#L2286) and I was able to easily reproduce the first bug without digging too much into other cases:
1. Put a selection into the editor.
2. Apply **bold** style.
3. Start typing.

https://user-images.githubusercontent.com/10279586/181376941-1e83e7cf-cbdd-44b0-bfe0-48fc2725dbe6.mov

As you can see, I wasn't able to properly apply bold, italic (or any other style) to the selection, as elements created for these styles are empty. It's not possible to place a selection inside such an element if it has no content. I'm pretty sure there are more issues like that - but for the most part they will be related to content styling.

I didn't dig into https://github.com/ckeditor/ckeditor4/issues/4939 myself, as the code provided in that ticket is beyond our capabilities of debugging it outside paid support offer - so if you need more help with the code you provided, I can only recommend contacting our support team.

I'm closing that ticket for now, as it basically is more like a question about editor functionality than a bug report (and such questions should be asked using support contact or stack overflow), but if you are able to provide some easily reproducible test steps allowing us to reproduce a bug with that mechanism, we can always reopen that issue.
