### ISSUE TITLE
There isn't input for label "Phone number" in "Link" dialog

### ISSUE THREAD

**Issue by katonator** [ckeditor/ckeditor4#5298]
Bug

Steps to reproduce.

1. Download (https://ckeditor.com/cke4/builder/download/8711cf5ac169f48eaa99388b61279d04);
2. Unpack folder;
3. Go to Samples and double click **index.html**;
4. Click the "Link" button;
![image](https://user-images.githubusercontent.com/58665331/181461407-05136ed6-ff4b-4bf5-9e3e-9a42999134a8.png)
5. Select Phone in combo box "Link Type".
![image](https://user-images.githubusercontent.com/58665331/181462136-e0119e93-c83f-4402-ac09-85ba6813bc96.png)

**Expected result**
input for "Phone number" is displayed

**Actual result**
input for "Phone number" is not displayed

Other details
![image](https://user-images.githubusercontent.com/58665331/181463057-72f9b3cc-a2ef-4b19-a956-5eee212a9bcc.png)
There isn't class "cke_dialog_ui_input_tel" in CSS files..
I tried to create different builds, but I always have this bug.

Could you please help me with this problem?

**Comment by sculpt0r** [comment]
Hi @katonator - thank you for the report.

I can confirm this issue. Looks like issue with styles, because the default style works fine 👍

**Comment by katonator** [comment]
Hi @sculpt0r .

https://ckeditor.com/cke4/builder/8711cf5ac169f48eaa99388b61279d04 (was created recently for an experiment)
Is it enough? I've found this link in build-config.js.

additional:
https://ckeditor.com/cke4/builder/7573d85ad942909727b3c6bbcdea948b (I use this build in my app (last update - v 4.17.1))

**Comment by sculpt0r** [comment]
@katonator 
I downloaded and extracted the editor from the first link you provided. Inside the main directory, there is also `skins` directory which contains separate directories for each style that might be used by this built version. In your case, there is `bootsrapck` style:
![Screenshot 2022-08-01 at 14 01 57](https://user-images.githubusercontent.com/6498567/182143666-45112cd6-5dd0-470e-b774-f9d3fe278c88.png)

Please note that not all available plugins are maintained by CKEditor4 team. They were created by third-party developers and it is their responsibility to eventually update them to make sure they have no bugs. The skin you selected is an example of third-party themes - not supported by the CKEditor team. You can take a look at https://ckeditor.com/cke4/addons/skins/all?sort_by=field_custom_downloads_value&sort_order=DESC and select the skin that has full support by looking at `Author` field. If CKSource is the author - then plugin/skin is supported. For example https://ckeditor.com/cke4/addon/moono-lisa

The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
