### ISSUE TITLE
 Toolbar List number are not accessible under 'Issue Information'.

### ISSUE THREAD

**Issue by msftedad** [ckeditor/ckeditor4#5337]
## Type of report
Bug

## Provide detailed reproduction steps (if any)
1. Navigate to URL [https://gethelptest.powerappsportals.com ](https://gethelptest.powerappsportals.com/)and login with valid credentials.
2. Then Get Help home page appears, Navigate all the controls of this page.
3. Enter some case number like 123 and select next button.
4. 'Before We proceed' page appears, Navigate all the controls of 'Issue Information' like all the text formats options like bold, bulleted lists etc.
5. Verify if toolbar List number and others are not accessible under 'Issue Information' or not.

### Expected result
Toolbar List number and others controls must be accessible under 'Issue Information'.
Example: Toolbar 'Bold, italic' is accessible using shortcut keys but Bullet number and others also should be accessible under 'Issue Information'.

### Actual result
Toolbar List number and others controls are not accessible under 'Issue Information'.
Observation: Toolbar 'Bold, italic' is accessible using shortcut keys but Bullet number and others also should be accessible under 'Issue Information' but these icons are accessible using mouse.

## Other details

OS Version: Version 22000.978 Build 21H2
Browser: Edge Version 105.0.1343.42 (Official build) (64-bit)

**Comment by Comandeer** [comment]
The software you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
