### ISSUE TITLE
Picture tag with source doesn't work

### ISSUE THREAD

**Issue by js-writer** [ckeditor/ckeditor4#5346]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. In hippo/blomreach document use ckeditor and choose source. 
2. Type for example
`<picture><source media="(min-width: 800px)" srcset="https://www.euroflorist.pl/img/300x/_big800@pl/BOU20_33.jpg" /> <img alt="" src="https://www.euroflorist.pl/img/300x/_big800@pl/BOU20_33.jpg" /></picture>` 
3. And then when you click save, ckeditor will change `<picture><source>` into `<picture><audio><source>`

### Expected result

*What is the expected result of the above steps?*
Don't wrap source tag with audio in picture tag

### Actual result

*What is the actual result of the above steps?*
Changing `<picture><source>` into `<picture><audio><source>`

## Other details

Settings for my hippo/bloomreach component:
ckeditor.config.overlayed.json: '{allowedContent: true}'
htmlprocessor.id: no-filter
* hippo/bloomreach version: 12.9.25
* Browser: chrome
* OS: windows 10
* CKEditor version: 4.16.0-h2
* Installed CKEditor plugins: image, image2,

**Comment by Comandeer** [comment]
Could you provide a sample reproduction? I was not able to reproduce the issue – https://codepen.io/Comandeer/pen/wvjRaZQ

Probably the issue is not connected with the CKEditor 4 itself but with plugins used by the hippo/blomreach.

**Comment by js-writer** [comment]
So your example is good. But when you click Save in hippo/bloomreach it fires some filter of something and add `<audio>` before `<source>`
This is how it look for me.
Before save:
![image](https://user-images.githubusercontent.com/5675915/195120832-cd793f31-9717-4cc7-87e5-e3ed85fd43b4.png)
after save:
![image](https://user-images.githubusercontent.com/5675915/195121015-2aa775f6-29a4-4af2-8ceb-a999026fea49.png)

**Comment by Comandeer** [comment]
In this case, the issue seems to be connected with the hippo/bloomreach software, not directly with CKEditor 4. As hippo/bloomreach is a third-party product, and it is not maintained by CKSource, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
