### ISSUE TITLE
Potential XSS

### ISSUE THREAD

**Issue by spaceintotime** [ckeditor/ckeditor4#5348]
[REDACTED]

**Comment by jacekbogdanski** [comment]
@spaceintotime Security issues _need_ to be reported by our support as the valid security issue will pose threat to existing users. Posting security issues and publicity put other all users at risk that use the editor.

I know we discussed the issue you quoted on supports, as I also took a part in the validation of that issue whether that's a valid vulnerability or not. From our research, the issue is not valid and it's caused by not following our best practices regarding content sanitization on the server side and with the preview plugin:

* https://ckeditor.com/docs/ckeditor4/latest/guide/dev_best_practices.html#filter-content-server-side
* https://ckeditor.com/docs/ckeditor4/latest/guide/dev_best_practices.html#validate-preview-content

However, if you still have doubts regarding that issue, I will be more than happy to extend the research regarding the reported problem and help you (or our development team) to understand if the issue can cause any harm if all best practices are applied by the editor integrators.

I will contact you via the support platform soon!
