### ISSUE TITLE
Colorbutton plugin not using additional styles.

### ISSUE THREAD

**Issue by mihilion** [ckeditor/ckeditor4#5352]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create custom css file.
2. Override style for `span.cke_colorbox` in custom file.
3. Use custom file with `CKEDITOR.config.contentsCss = ['/path/to/custom.css'];`

### Expected result

Custom style should be applied to colorbutton plugin.

### Actual result

Custom style is not applied to colorbutton plugin

## Other details

Reason for that:
```
panel: {
	css: CKEDITOR.skin.getPath( 'editor' ),
```
Better solution found in Format plugin
```
panel: {
	css: [ CKEDITOR.skin.getPath( 'editor' ) ].concat( config.contentsCss ),
```

**Comment by mihilion** [comment]
I have added proposed change and created a pull request. Looking forward for review and merge.

**Comment by Comandeer** [comment]
I've changed the issue type to feature request as the proposed solution (using [`config.contentsCss`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss)) would result in a breaking change. The mentioned config variable is used to style the content in the editor, not the UI of the editor. If the user passed a path to the custom stylesheet, it would result in unexpected styling of the color button panel. Therefore, such styling should be implemented as a separate config variable, e.g. `config.colorButton_css`.

As for using `config.contentsCss` in the "Format" plugin: this plugin's UI presents styles that can be used in the editor's content. Due to that, it reuses its style to better reflect the end result, e.g. by applying a correct font family.

**Comment by mihilion** [comment]
Ok, PR updated and waiting for review.
