### ISSUE TITLE
What is the accepted pattern for plugin api integration with the editor

### ISSUE THREAD

**Issue by Enquier** [ckeditor/ckeditor4#5379]
## Type of report

Docs

## Provide a description of requested docs changes

I am trying to understand the cases where a plugins editor API might be located under CKEDITOR._ vs CKEDITOR.plugins. This is for the purposes of better understanding in my TS application. Hopefully this makes sense and sorry if it's been asked before

**Comment by KarolDawidziuk** [comment]
Hello @Enquier 

The `CKEDITOR._` property is private and it should not be used outside of the library.

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
