### ISSUE TITLE
lang / de, es, ja: add missing txtNoEmbed key

### ISSUE THREAD

**Issue by nipandeBMC** [ckeditor/ckeditor4#5382]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Switch to any of above language and click Youtube Icon. Not able to see the label.
You can use one of our samples to create the reproduction sample:

![image](https://user-images.githubusercontent.com/118510263/205016395-2d236a3a-6d72-4828-b9f0-becdae6eea20.png)
-->

1. …
2. …
3. …

### Expected result

Should able to see labels when we change to these languages.

### Actual result

Not able to see keys when switched to above languages.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by nipandeBMC** [comment]
![image](https://user-images.githubusercontent.com/118510263/205016550-6e369003-e071-4c04-9dd6-71227047aab3.png)

**Comment by KarolDawidziuk** [comment]
Hi @nipandeBMC 

The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
