### ISSUE TITLE
Failing tests in Chrome version >= 108

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#5385]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

1. Run all tests.

### Expected result

Tests are passed.

### Actual result

Tests are failing but when we run every single failing test in a separate browser tab, the tests will pass.

![image](https://user-images.githubusercontent.com/18471998/205296984-fe735d27-2228-4fda-9c2f-48e2ada996b7.png)

## Other details

* Browser: Chrome
* OS: …
* CKEditor version: 4.20.1
* Installed CKEditor plugins:

**Comment by KarolDawidziuk** [comment]
I've digged a little during working on this bug and it looks that since 108 version of Chrome selection works differently while using [`bender.editorBot.prototype.setData()`](https://github.com/ckeditor/ckeditor4/blob/master/tests/_benderjs/ckeditor/static/bot.js#L240-L253).

The main issue with all these test is the fact that during checking [`if ( range.checkReadOnly() )`](https://github.com/ckeditor/ckeditor4/blob/master/core/editable.js#L1763) range is undefined causing throwing a TypeError.

The possible cause of this issue is using the bender `setData()` method after changes in Chrome.
Based on [example](https://github.com/ckeditor/ckeditor4/blob/master/tests/plugins/easyimage/pasteintegration.js#L27-L32).

```
// Before using setData - range is available.

bot.setData( '', function() {
  // Range disappeared.
  bender.tools.range.setWithHtml( editor.editable(), '<p>[]</p>' );
  bender.tools.emulatePaste( editor, pastedData );
 
 //...
``` 

Another difference that I noticed between browser versions is native selection.
In the older version native selection points to thr `p` element but in the latest is pointing to `document`:
`editor.getSelection().getNative()`:
* Older:
![image](https://user-images.githubusercontent.com/18471998/207341059-b1293db5-bb48-4e81-90c4-c5df46ec56b4.png)
![before](https://user-images.githubusercontent.com/18471998/207344233-81a33a90-8fa4-4e2f-9b8e-25781d382e5d.png)
* Latest:
![image](https://user-images.githubusercontent.com/18471998/207341136-f49a20cd-4b57-46ff-a61e-24963930c6ab.png)
![after](https://user-images.githubusercontent.com/18471998/207344232-0ae1d856-ca8e-4c25-bc7e-ae9ed3d43102.png)

To fix these failed tests, we can simply change this `setData()` function to `setHtmlWithSelection()`, but this is more of a temporary fix.

**Comment by Comandeer** [comment]
Some more observations:

* tests seem to fail only in the `iframe`-based editor, they work correctly in the inline ones;
* it seems that setting the editor's data to `''` anchors the selection inside the `document` (as @KarolDawidziuk mentioned) and it somehow breaks our selection's cache (it's empty and due to [its usage in `Selection#getRanges()`](https://github.com/ckeditor/ckeditor4/blob/0150a16041546fdf71ca3313be87ad500f44c200/core/selection.js#L1813) all other operations are fired upon the non-existent range).

**Comment by Comandeer** [comment]
It seems that it's connected with the [`framedWysiwyg#setData()` method](https://github.com/ckeditor/ckeditor4/blob/2648362516004bdf435dae71a102df97f26bb910/plugins/wysiwygarea/plugin.js#L429-L592). For some reason, we recreate the whole frame's document from scratch using `document#write()` each time something sets the editor's data. This causes Chrome to point selection at the very beginning of the `document` (`document` common ancestor + `0` offset) and later our selection sees it as a selection outside of the editor, resulting in the error and failing tests. In that case, Firefox indicates that the selection is at the beginning of the `body` element, while Safari – in the `document` but with `1` offset.

The issue is visible only in tests as we often just set the data to `''` and then assume that there's still selection in the editor. However, simple focusing of the editor after setting data should do the trick (it sets the selection to the beginning of the `body`). In the case of "normal" editor usage, nearly all interactions (except maybe via devtools) require focus – so the selection is fixed.

Yet there's another issue: the fact that these tests are connected mainly with widgets and widgets are represented by the `[contenteditable=false]` elements, which don't work properly in Chromium-based browsers and it can make the whole fix more complex (e.g. requiring us to actually create a fake selection inside the editor instead of simply focusing it).
