### ISSUE TITLE
Code Snippets plugin problem

### ISSUE THREAD

**Issue by Anonymus0999** [ckeditor/ckeditor4#5390]
## Type of report

Bug

I created an online build of CKEditor 4.20.1 with the plugin [Code Snippets](https://ckeditor.com/cke4/addon/codesnippet). It is working fine. But if I set the toolbar on the page then the code Snippet button is not showing in the toolbar. all other toolbar buttons working fine with this.  
`<textarea name="text_editor" id="text_editor" ></textarea>
CKEDITOR.replace( 'text_editor', {toolbar:[['Source','codeSnippet','Table']],
height:['350px']
}`
with the above code source and table buttons (icons) visible. but codeSnippet button is not visible.

* CKEditor version: 4.20.1
* Installed CKEditor plugin: Code Snippets

**Comment by KarolDawidziuk** [comment]
Hi @Anonymus0999

Looks like you missed adding `extraPlugins: 'codesnippet'` in your editor configuration.
For more information, check out our [plugin installation guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_plugins.html).

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore if adding missing `extraPlugins` property would not help please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
