### ISSUE TITLE
Paste <option> 

### ISSUE THREAD

**Issue by fforfabio** [ckeditor/ckeditor4#5393]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Hi,
I selected the **flat** skin.
I try the index.html inside the samples folder and I had an unpleasant behaviour (see the image below) when I click on all the paste options in the toolbar (in the image is the paste from word option)
![flat](https://user-images.githubusercontent.com/120016875/207626041-377eb83b-7998-46bc-9c7a-ff702bcb64a9.png)

### Expected result
This one, with **Moono-Lisa** skin: 
![moono](https://user-images.githubusercontent.com/120016875/207625983-781acdac-c9a4-4749-bf10-7badf42aaa0d.png)

## Other details

* Browser: Chrome, Firefox, Edge
* CKEditor version: 4.20.1

**Comment by KarolDawidziuk** [comment]
Hi @fforfabio

The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
