### ISSUE TITLE
Two Text Areas On Same Page Destroys Editor and Loads In Second Text area With Tags  

### ISSUE THREAD

**Issue by Ali-Raza-Tawary** [ckeditor/ckeditor4#5403]
When I use one <textarea  in form it loads fine when i put another <textarea on the same page with different id and name for other use perivious Editor destry and its tags load in second text area with tags . i tried on every lastest standard and full version but problem is same ..  I cant use 2 textareas tags on same page .. if i text editor destroys.

**Comment by Comandeer** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
