### ISSUE TITLE
feature plan about document.domain in ckeditor

### ISSUE THREAD

**Issue by Ravikantsolanki** [ckeditor/ckeditor4#5412]
Currently most of the browsers are going to deprecate the setters for document.domain method.

Here mentioning about deprecation https://developer.mozilla.org/en-US/docs/Web/API/Document/domain. Please refer this article as well.

However, ckeditor.js or others js are still using document.domain method to set document.domain. Please refer the below link where you will find out the document.domain setter.
https://github.com/ckeditor/ckeditor4/blob/f63100689a26032b4df7002bf4cb1ba6f2b494e8/core/tools.js#L1410

We wanted to know your feature plan about document.domain. Means are you planning to use any alternative way or it will still be used in feature? In that case it might be create an issue if setters for document.domain will be deprecated.

**Comment by Comandeer** [comment]
As it's stated in the [documentation of this method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-fixDomain), it's used only in Internet Explorer, and due to that it won't be affected by the deprecation.

However, it seems that there is one place in our codebase where this method is accidentally used also in Firefox → https://github.com/ckeditor/ckeditor4/blob/0150a16041546fdf71ca3313be87ad500f44c200/plugins/preview/plugin.js#L224
That's probably something we need to fix.

**Comment by tmajumda1** [comment]
@Comandeer 
In the meantime, say if document.domain setters stop working completely, will it have any major impact in CKEDITOR?

**Comment by Comandeer** [comment]
As I already said, we use it only in the Internet Explorer which means that disabling setters for `document.domain` shouldn't be an issue for us.
