### ISSUE TITLE
Fix or workaround for the `change` event not firing on emoji inputs

### ISSUE THREAD

**Issue by wxie333** [ckeditor/ckeditor4#5413]
This is the same issue as https://github.com/ckeditor/ckeditor4/issues/3950. Since there is no follow-up on that issue ticket, I am curious if this issue has been fixed in any later version or if there is any workaround ?

**Comment by KarolDawidziuk** [comment]
Hi, @wxie333 

This issue occurs and for now, we don't have an ETA for this issue.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
