### ISSUE TITLE
&lt; character not 

### ISSUE THREAD

**Issue by csvega** [ckeditor/ckeditor4#5417]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The part containing '**&lt**;' character cannot be loaded.

The source code is below.

HTML file:

```
...
<textarea id='content' name='content'> #include &lt;stdio.h&gt; </textarea>
...
```

```
<script src="ckeditor/ckeditor.js"></script>
<script>
        window.onload = function(){
                CKEDITOR.replace( 'content', {
                        extraPlugins: 'codesnippet',
                        codeSnippet_theme: 'xcode',
                })
        };
</script>
```

### Expected result

> #include <stdio.h>

### Actual result

> #include

## Other details

* Browser: Chrome
* OS: Win 10
* CKEditor version: 4.11.4
* Installed CKEditor plugins: codesnippet

**Comment by Comandeer** [comment]
As it can be seen in [our docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_framed.html#creating-a-classic-editor-with-a-textarea), using the `textarea` element to initialize the editor requires encoding all HTML elements (e.g. `<p>` becomes `&lt;p&gt;`). Due to that, the `&lt;stdio.h&gt;` fragment is treated as `<stdio.h>` HTML element and is removed by the [Advanced Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) mechanism.

To correctly display the code as editor's content, you need to double escape it:

```html
<textarea id="content" name="content"> #include &amp;lt;stdio.h&amp;gt; </textarea>
```

or use the `div` element instead of `textarea`:

```html
<div id="content" name="content"> #include &lt;stdio.h&gt; </div>
```
