### ISSUE TITLE
Hi, everyone, how can I adjust the order of the upload tag in the image dialog window to the default display?

### ISSUE THREAD

**Issue by nottellyou** [ckeditor/ckeditor4#5429]
## Ask for Help

Hi, everyone, how can I adjust the order of the upload tab in the image dialog window to the default display? 
Because this function is most used: every time I upload an image, I have to click the upload tab to upload the image, which makes me click once more.

## Other details

* Browser: …chrome
* OS: …win7
* CKEditor version: …4.6.0
* Installed CKEditor plugins: …image

**Comment by KarolDawidziuk** [comment]
Hi @nottellyou 

I'm not sure if I understand your question. could you specify it or prepare a simple working example that will show your issue?
You can use one of our samples to create the reproduction sample:

* [CodePen](https://codepen.io/karoldawidziuk/pen/LYzJvdx)
* [JSFiddle](https://jsfiddle.net/Kratek_95/nhwe5uLq)
* [JSBin](https://jsbin.com/gubepar/edit?html,js,output)
* [StackBlitz](https://stackblitz.com/edit/ckeditor4-bug-report)

Also, It looks like your picture was not added in the [next comment](https://github.com/ckeditor/ckeditor4/issues/5429#issuecomment-1432790137).

**Comment by nottellyou** [comment]
Hi, @KarolDawidziuk

Because of the instability of my network, the picture was not uploaded successfully. I put the picture here http://apptj.net/tmp/snipaste20230216_172206.jpg 。
I want to adjust the order of the upload tab in the image dialog window to the default display.

**Comment by KarolDawidziuk** [comment]
@nottellyou, you can use the `dialogDefinition` event to change the default displayed tab.
For more information please see: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_dialog_windows.html#how-do-i-set-a-specific-dialog-window-tab-to-open-by-default

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them and due to that, I'll close this report.

If the steps in the above link don't help and you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

**Comment by nottellyou** [comment]
Hi, @KarolDawidziuk

Thank you very much for your kind help. I realized this function. thank you.
I will go to Stack Overflow to ask questions later.
