### ISSUE TITLE
Regarding accessibility shortcut keys for Mac users

### ISSUE THREAD

**Issue by Revan-indi** [ckeditor/ckeditor4#5444]
_As per the Documentation of the Official website of CKEDITOR toolbars control, mentioned Accessibility shortcut keys to access the toolbar in the document. We can use the shortcut key "alt+F10" to enter the toolbar and it is operable with tab key and Up/down arrow keys,_ 

What the shortcut for Mac is to use via keyboard and if there are no function buttons.

Could you please help me out?

**Comment by KarolDawidziuk** [comment]
To enter the toolbar on macOS please use `fn+option+F10`.

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
