### ISSUE TITLE
CkEditor4 paste icon/plugin is not working its showing not supporting

### ISSUE THREAD

**Issue by pushpanjali-patil** [ckeditor/ckeditor4#5453]
![image](https://user-images.githubusercontent.com/56927198/229112938-3f8c23cb-eead-4b7f-b57d-dea21c0749d6.png)

please find below image for the same im unable to paste using that paste icon

**Comment by Comandeer** [comment]
Please see [https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192](https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192) for an explanation of the current paste button behavior. Unfortunately, most browsers do not allow pasting via a button, and due to that, we display that message.
