### ISSUE TITLE
Paste Icon is not working also pastefromword icon and pasteas plain text icon not working

### ISSUE THREAD

**Issue by pushpanjali-patil** [ckeditor/ckeditor4#5457]
paste icon,pastefromword icon and paste as plain text icon not working its showing your browser not supporting try to enter ctr + v
attching image for the same
![image](https://user-images.githubusercontent.com/56927198/230290575-dc117448-9ee5-43a1-a9c2-00793d46baf4.png)

**Comment by Comandeer** [comment]
Please see [https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192](https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192) for an explanation of the current paste button behavior. Unfortunately, most browsers do not allow pasting via a button, and due to that, we display that message.
