### ISSUE TITLE
Source button is not showing on Page but it is showing on Design page of Kentico 11 CMS.

### ISSUE THREAD

**Issue by vikramnmore** [ckeditor/ckeditor4#5487]
Hi Team,

I have upgraded CKEditor to 4.21.0 in Kentico 11 CMS. I have downloaded CKEditor 4.21.0 from https://ckeditor.com/cke4/builder. 
When I am trying to click on editable text in Kentico 11 CMS then Source button is not showing on Page but it is present in Design tab.

Am I missing anything there. Please help me.
![1](https://github.com/ckeditor/ckeditor4/assets/99478563/a14302a7-0424-48ee-bfbc-b38216012afa)
![2](https://github.com/ckeditor/ckeditor4/assets/99478563/bc28243a-6467-4348-ac6e-ffbd7feddb14)

Thanks!

**Comment by Comandeer** [comment]
Kentico 11 CMS you are referring to is a third-party software, and it is not maintained by CKSource. Since we cannot fix issues with code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software's author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
